### ISSUE TITLE
[Bug]: Telegram do not send any notification anymor (sound notifications also)

### ISSUE THREAD

**Issue by MadelineProtoFan** [ferdium/ferdium-app#1000] opened 2022-06-30 00:05 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Ferdium Version

6.0.0-nightly.81

### Recipe Name

Telegram

### Recipe Version

3.3.3

### Steps to reproduce

Login to telegram web and send the message to yourself. There will be no notifications

### Expected Behavior

Notifications

### Actual Behavior

0 Notifications

### Additional Information

Please fix it

**Comment by jasmines** [comment] 2022-06-30 06:45
Same here.
https://github.com/ferdium/ferdium-app/issues/1009

**Comment by MadelineProtoFan** [comment] 2022-06-30 12:02
Please fix it

**Comment by MadelineProtoFan** [comment] 2022-07-01 11:26
> Same here. ferdium/ferdium-app#1009

Its not the same. Started 3 days ago. Your topic is not about this problem. It is an old problem bro

**Comment by MadelineProtoFan** [comment] 2022-08-14 10:04
1,5 month past. I do not have any sound notifications in both versions on Windows. I lost a lot of money because of it
Very bad situation

**Comment by vraravam** [comment] 2023-05-29 13:46
Duplicate of #434

**Closed as completed by vraravam** 2023-05-29 13:46 UTC
Labels: bug :beetle:, recipe :bookmark_tabs:
