### ISSUE TITLE
Bug: Deleting a chat in WhatsApp gives a weird unrelated error message

### ISSUE THREAD

**Issue by frankhommers** [ferdium/ferdium-app#613] opened 2022-09-12 19:22 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.1.0

### What Operating System are you using?

Windows

### Operating System Version

10

### What arch are you using?

x64

### Expected Behavior

I want just the delete popup not a ferdium warning

### Actual Behavior

When I delete a chat I see this:

![image](https://user-images.githubusercontent.com/7355878/189738061-7dad61ec-1f6e-4660-9c00-f7e99c27d153.png)

### Steps to reproduce

Go to WhatsApp
Right click on a chat and select delete
Observe the warning ;-)

### Screenshots

![image](https://user-images.githubusercontent.com/7355878/189738143-ae97dc58-b1da-4e24-a71e-a40f1065ef55.png)

**Comment by vraravam** [comment] 2022-09-13 01:54
@frankhommers - please also search in the close issues before opening a new one. This has already been fixed and is available in one of the latest nightlies.
Duplicate of #595

**Closed as completed by vraravam** 2022-09-13 01:54 UTC
Labels: bug :beetle:

**Comment by frankhommers** [comment] 2022-09-14 21:11
OK Sorry, I couldn't find it.. Will try to do better next time.
