### ISSUE TITLE
Installer or Ferdium close Ferdium before getting go ahead from user

### ISSUE THREAD

**Issue by mishaxz** [ferdium/ferdium-app#1226] opened 2023-06-03 18:37 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

latest

### What Operating System are you using?

Windows

### Operating System Version

W11

### What arch are you using?

x64

### Last Known Working Ferdium version

still works

### Expected Behavior

see actual

### Actual Behavior

doesn't care about the yes/no dialog for closing in installer

### Steps to reproduce

1. got prompted for update
2. chose update while ferdium open
3. installer popped up
4. ***Ferdium Closed**
5. saw yes / no close dialog in installer (not sure if it opened just prior to ferdium closing or after, I wasn't watching it)
6. just to be clear, Ferdium had closed - and I didn't manually close it
7. so it is closed right now
8. then I click Yes to close (but it is already closed)

### Debug link

https://dont.know

### Screenshots

n/a

### Additional information

I have no more information to offer. if you wait for follow up info, I might not even see the message for weeks as I rarely check github. I suggest trying to solve it based on info provided.

**Comment by Alphrag** [comment] 2023-06-03 19:51
@mishaxz thanks for reporting this issue. I however have trouble understanding what you mean. First of all we need to know exactly what version you were on since "latest" is not clear considering how quickly we move from one nightly or stable version to another (e.g. we need something like `6.3.0-nightly.15`). 
The way we do the update is that we prompt the user to click on the button to "Restart and update". As long as they do not do click on it, nothing should happen. Once they do so (which corresponds to your step 2.) it will quit the app and launch the installer, which will prompt the user to choose the install location (behaviour since versions `6.3.0-nightly.12` when it was silent before). 
If I follow your steps, nothing is going wrong since you chose to update in 2. which quit Ferdium and launched the installer as expected. The only thing that could make you wonder if you closed Ferdium is that depending on your computer, it can take a dozen of seconds to actually finish all Ferdium processes and the installer tells you that "Ferdium is still running, do you want to close it?" which actually is simply trying to do the install again after asking the processes to close.

Unless I have misunderstood anything in your steps, what you describe is the expected behaviour. I will close this issue as such, but feel free to comment back on it if you have more precise information to share (especially some screenshot/gif).

**Closed as completed by Alphrag** 2023-06-03 19:51 UTC
Labels: bug :beetle:, windows
