### ISSUE TITLE
Feature: Ability to add plugin from chrome browser

### ISSUE THREAD

**Issue by martysl** [ferdium/ferdium-app#670] opened 2022-10-12 13:24 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

idea is to add option to load chrome extension

### Proposed Solution

it can be loaded from settings load ziped extension from file for example

### Alternatives Considered

or also can be from web based extension directory hosted on public server

**Comment by vraravam** [comment] 2022-10-12 13:27
Duplicate of #135 
Please do not create duplicate bugs! TIA

**Closed as completed by vraravam** 2022-10-12 13:27 UTC
Labels: enhancement :sparkles:
