### ISSUE TITLE
Bug: Latest version of Ferdium opens to a blank screen

### ISSUE THREAD

**Issue by cg00001** [ferdium/ferdium-app#235] opened 2022-06-12 10:21 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

ferdium-bin-6.0.0-nightly.57-1

### What Operating System are you using?

Other (specify below)

### Operating System Version

Arch Linux

### What arch are you using?

x64

### Last Known Working Ferdium version

Previous

### Expected Behavior

Work like previous version did.

### Actual Behavior

Empty screen.

### Steps to reproduce

I tried the following Arch Linux packages:
ferdium
ferdium-bin
ferdium-git

### Debug link

Help is empty

### Screenshots

![k_20220612-131843](https://user-images.githubusercontent.com/38960370/173228642-76ea852b-5e86-4bf8-8223-ed736ff774f3.png)

**Comment by yarons** [comment] 2022-06-12 10:29
I'm experiencing the same thing on Manjaro Linux, `.cache` folder seems intact.

**Comment by SpecialAro** [comment] 2022-06-12 11:03
I'm experiencing the same on W11.
Bisecting to see the culprit

**Comment by SpecialAro** [comment] 2022-06-12 11:08
On Dev mode, the latest nightly seems to be working fine

**Comment by NathanaelGandhi** [comment] 2022-06-12 11:42
Duplicate #230

**Comment by nathanaelhoun** [comment] 2022-06-12 11:55
Closing as it is a duplicate of #230.

**Closed as completed by nathanaelhoun** 2022-06-12 11:55 UTC
Labels: bug :beetle:, duplicate :mirror:
