### ISSUE TITLE
Feature: Allow Workspaces drawer to be resizes or allow for different set widths like the sidebar width settings

### ISSUE THREAD

**Issue by PiotrKrzyzek** [ferdium/ferdium-app#849] opened 2022-12-16 19:41 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The Workspace drawer only has three options: always open, closed, opened on command. This limits our usability as 'always open' takes up a lot of space, and having it closed decreased productivity (such as in the case of using workspaces to jump between client oriented workspaces).

### Proposed Solution

Allow for one of two things:

(a) The Workspaces drawer should have a width settings in the Settings -> Appearance tab similar to the width / size setting for the sidebar (example: wide, extra wide, slim, normal, etc.)

(b) Allow users to click-and-drag-resize the Workspace drawer to their own preferred size.

### Alternatives Considered

Editing the CSS for the whole app might work, but that requires nerdy knowledge which is out of the wheelhouse of most users.

**Comment by vraravam** [comment] 2022-12-17 04:19
Duplicate of #139

**Closed as completed by vraravam** 2022-12-17 04:19 UTC
Labels: enhancement :sparkles:
