### ISSUE TITLE
Unable to authenticate Google Calendar without a workaround

### ISSUE THREAD

**Issue by stephenpearce** [ferdium/ferdium-app#1064] opened 2023-03-18 10:30 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.6-nightly.7

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 version 22H2

### What arch are you using?

x64

### Last Known Working Ferdium version

6.2.4

### Expected Behavior

If I recall correctly, the service used to immediately take you to a page where you could log in. You were then forwarded to the calendar after successful authentication. It was all within Ferdium and never opening my default desktop browser.

### Actual Behavior

After having added a Google Calendar service to Ferdium, you are taken to a Google Workspace page. When clicking "Sign-in" there, the link doesn't open within Ferdium but instead your desktop's default web browser. Continuing the sign-in process means that your desktop browser is getting the authentication and not Ferdium.

The service setting "Open URLs within Ferdium" doesn't help the situation either.

### Steps to reproduce

1. Add a Google Calendar service to your Ferdium services.
2. Attempt to sign in.
3. Observe that you cannot sign-in, because the link opens in your default web browser.
4. Try setting "Open URLs within Ferdium" and observe that the link still opens in the default web browser.

### Debug link

https://debug.ferdium.org/a274e28f-19ef-446f-979b-5500205d5590

### Screenshots

![Untitled](https://user-images.githubusercontent.com/1271004/226099745-a8f334e1-f016-48a1-b935-ff0fa9bceaff.png)

### Additional information

For the time being, I have been able to work around the problem with the following steps:

1. In the service settings, change the custom server URL to:
https://accounts.google.com/

2. The service will reload, at which point you'll be able to authenticate with Google.

3. Once authenticated, change the custom server URL again to:
https://calendar.google.com/

4. The service will reload again and you should be looking at your calendar.

**Comment by rikikamano** [comment] 2023-03-22 06:14
me too

**Comment by rvega** [comment] 2023-03-28 18:09
+1

**Comment by robnoon** [comment] 2023-03-29 08:27
Me too ... using Mac  osx Ventura 13 and Ferdi 5.8.1 

Used work around and worked well ... see above

**Comment by AtosDev** [comment] 2023-03-29 09:20
+1

**Comment by Alexand3-R** [comment] 2023-03-30 01:56
Maybe this also has something to do with the new "require-trusted-types-for" CSP.

**Comment by bjoerrrrn** [comment] 2023-04-03 04:02
+1

**Comment by AtosDev** [comment] 2023-04-06 17:12
[bjoerrrrn](https://github.com/bjoerrrrn)

**Comment by cdelacombaz** [comment] 2023-04-11 05:59
+1

**Comment by cr3ation** [comment] 2023-04-11 09:12
+1

**Comment by robnoon** [comment] 2023-04-11 09:14
Work around above worked for me... if your having issues use the work around

**Comment by DarkwaterV3** [comment] 2023-04-21 10:07
Thank you for the workaround.

**Comment by antbono** [comment] 2023-04-28 09:50
+1, thank you for the work around!

**Comment by ollidoetsch** [comment] 2023-04-28 10:38
Same here but the workaround works great, thank you for that!

**Comment by marie-bnl** [comment] 2023-04-28 11:31
This issue happens on various Google websites, such as Google Classroom, about which I marked the issues above as duplicate of this one (kept this one because it seems to have a bit more activity on it than the two other ones). As far as I know it occurs because the log-in link has a `target="_blank"` attribute which tells the browser to open the link in a new tab, so Ferdium opens it in an external browser. ~~A workaround would be to remove that attribute from the service’s `webview.js`, but it is a bit dirty and would use performance for no reason for logged-in users. However it is the best solution I found yet. See my full answer on the other issue here: https://github.com/ferdium/ferdium-app/issues/1135#issuecomment-1525792994.~~

Edit: I see this has already been tackled here: https://github.com/ferdium/ferdium-recipes/commit/be1bdd785b7ba739ea6c51c2d960499b04052501 in version 2.3.2. I’ll try to reproduce it to see if it works with the up-to-date service.

Ferdium still downloads version 2.3.1 indeed. All that if left to do is wait until it gets updated to version 2.3.2. I’ll make a pull request to apply the fix in Google Classroom as well.

While waiting for the services to get updated, a nice workaround is to just right-click on the link and click “Open link in Ferdium”.

**Closed as completed** 2023-04-29 20:17 UTC
Labels: bug :beetle:

**Comment by jwmh** [comment] 2023-05-14 16:07
For a newbie,
This has NOT been fixed for "Google CALENDAR"
i.e. maybe it was fixed for "Classroom" only?

I installed via https://ferdium.org/download
using the .debi file:
Alternative Downloads
DEB
amd64 deb
[website download page links to: ]
https://github.com/ferdium/ferdium-app/releases/download/v6.2.7/Ferdium-linux-6.2.7-amd64.deb

After installing on top of 6.2.6,
6.2.7. then gave me a [very minimal] little red dot in Settings, which led me to "Reload Services."
{Sidebar: I think the UI isnt ready for nontechheads just yet...} ... so I reloaded services.
(still no joy after manually going to Settings -reloading services!)
>
then I also deleted my GoogleCalendar services completely.
Then re-added them.
I've also tried quitting & restarting the app.

None of this fixes this issue #1064 for me:
It still insists on opening the login page in my primary web browser (as described above by others).


half an hour *after* giving up on this 
 -- 
and then fiddling around with an unrelated issue later...

EDIT:
OK, some new stuff happened.
*Please Read Below*

I:
1. tried to clear the ferdium cache (for an unrelated issue);
2. said "couldn't clear all cache", so i:
3. disabled every single service;
4. cleared cache again;
5. still didn't clear all cache (i guess that's impossible? but so then i) killed the ferdium browser process, which quit ferdium entirely;
6. restarted ferdium;
7. cleared cache *again*;
8. and *now* i [redundantly??? since i'd already done it before????] get a pop-up saying "Some of your services have been updated" with a big "Reload Services" button (which supposedly i had already done);
9. did so [again];

... 
and now it's working.

I'm opening a new issue around this.
It shouldn't take this much hassle to update GCalendar -- or any other module/service --
and there should be an automatic process to handle all of it built-in -- immediately upon upgrade...
(maybe in the 'running post-installation scripts' portion?)

... so
1. users don't get confused; and
2. y'all dont get pinged with lots of messages like this from people like me lol

**Comment by rh-jelabarre** [comment] 2023-06-14 17:51
The workaround (setting to accounts.google.com then back to calendar.google.com) worked for me.  What was happening was since I was already logged into Google work account in Firefox, clicking on the "Sign In" would just redirect right over to Calendar in te browser.  The Accounts workaround brought me to the company SSO page instead, and I was able to get the Calendar service to authenticate.
It would be nice to have a superset of services, where you could select a group of services to use the same authentication, as I just know I will likely have to re-authenticate to our SSO server for each service, rather than once per session.
