### ISSUE TITLE
QuickSwitch start without focus

### ISSUE THREAD

**Issue by Dominiquini** [ferdium/ferdium-app#1023] opened 2023-02-25 01:04 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

When I open the QuickSwitch (CTRL + S), the popup opens, but without focus!
E need to click in the QuickSwitch's window to start searching or navigating my recipes

### Proposed Solution

When I open QuickSwitch, the popup should start focused. I should be able to start searching or navigating my recipes without the need to use my mouse!

### Alternatives Considered

---

### Additional Information

OS: Windows 10 x64
Ferdium Version: 6.2.4

**Comment by vraravam** [comment] 2023-06-01 07:47
This is something that I would also like to get fixed - but, haven't found the root cause. It has to do with how electron treats focus for overlays

**Comment by mcmxcdev** [comment] 2024-04-13 23:34
Closing as duplicate of https://github.com/ferdium/ferdium-app/issues/341

**Closed as completed by mcmxcdev** 2024-04-13 23:34 UTC
Labels: enhancement :sparkles:
