### ISSUE TITLE
Incorrect display of the text in the dialogue windows

### ISSUE THREAD

**Issue by gxgo** [ferdium/ferdium-app#1917] opened 2024-10-09 16:21 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.6.7

### What Operating System are you using?

Ubuntu

### Operating System Version

Kubuntu 24.04 LTS

### What arch are you using?

x64

### Expected Behavior

Text to be displayed in the language selected in application settings

### Actual Behavior

Instead of letters, squares are displayed so that the text is indistinguishable.

### Steps to reproduce

The first screenshot is the save window of a file received via WhatsApp.
Second screenshot is a confirmation dialog for changing languages.

### Screenshots

![Fendium-screenshot_20241009_184958](https://github.com/user-attachments/assets/aab1002f-1e3f-4f06-9f18-dda3d1935b6d)
![Fendium-screenshot_20241009_190222](https://github.com/user-attachments/assets/952a1ce1-2c18-40a2-b156-e68666181f58)

### Additional information

Current language is English. The problem persist even if  I change to other language.

**Comment by SpecialAro** [comment] 2024-10-09 19:14
Duplicate of https://github.com/ferdium/ferdium-app/issues/435

**Closed as not planned by SpecialAro** 2024-10-09 19:14 UTC
Labels: duplicate :mirror:
