### ISSUE TITLE
No notifications 

### ISSUE THREAD

**Issue by vncloudsco** [ferdium/ferdium-app#1105] opened 2023-04-10 10:38 UTC
### Your issue

we don't receive any notifications from apps,  all messages on my apps are not receiving any notifications, the number of incoming messages is displayed next to the icon but there is no notification of new messages how can i fix this problem?

**Comment by marie-bnl** [comment] 2023-04-21 09:50
What service are you expecting getting notifications from? Ferdium by itself does not send notifications. Thus you can only get notifications from services that send them, i.e. services you get notifications from on the web browser. If a website does not send web notifications, Ferdium can’t do it for it. This is because it has no system to read the messages’ sender information and content.

**Comment by collindutter** [comment] 2023-04-21 15:56
@victorbnl I'm not receiving notifications on Gmail. A notification badge appears on the Ferdium icon, but I receive no alerts. This is on macOS 13.3, Ferdium 6.2.6.

**Comment by marie-bnl** [comment] 2023-04-23 12:44
Do you receive notifications from GMail on your web browser?

**Comment by gschafra** [comment] 2023-06-27 07:14
Same here for WhatsApp, see #1182. After fixing the not working message count in the badge the missing notifications problem popped up, which I've been trying to solve. And then, while looking into the API doc and the code, I realized that Ferdium does not send notifications but the service does or should do....

**Comment by akatarmo** [comment] 2023-06-27 07:32
> Ferdium by itself does not send notifications. Thus you can only get notifications from services that send them, i.e. services you get notifications from on the web browse

Since Ferdi died I have been using Ferdium. And I have **always** received WhatsApp notifications. But it's been about a month since the notification banner in the statusbar on the right is not displayed.

And of course Whatsapp sends them because I am now using **Rambox** until the problem is fixed in Ferdium and in Rambox I receive notifications as expected.

**Comment by marie-bnl** [comment] 2023-07-18 15:10
I was able to reproduce the issue, WhatsApp does send notifications on Firefox and not on Ferdium. I’ll try to investigate it.

**Comment by marie-bnl** [comment] 2023-07-18 15:21
So, here is the state of affairs. Some services do send notifications as expected, I receive notifications from ProtonMail. Some don’t send notifications but it seems to be the website’s issue, on GMail I don’t receive notifications, but neither do I on Firefox. Last, interestingly, WhatsApp does send notifications on Firefox and not on Ferdium. I wonder if it happens with other services as well. In the case of WhatsApp I noticed updates don’t work (click update and refresh the page, the update button will still be there, which doesn’t happen on Firefox), and I wonder if it could be the cause of the issue.

**Comment by PingWeb** [comment] 2023-07-31 18:26
Any update on this one? I am not getting any notification banners (only the sounds) for a few months now. It is a key feature, without this I need to find another app. Would rather keep using Ferdium, because except for this it works really good.

**Comment by Catarax** [comment] 2023-08-18 10:48
Same issue here. sound and icon only.

**Comment by PingWeb** [comment] 2023-09-25 16:48
It suddenly started working again here, without any update of Ferdium. So I expect an update on the side of WhatsApp fixed it.

**Comment by marie-bnl** [comment] 2023-09-25 18:27
I hadn’t noticed it until you said it, but it started to work again on my side too.

**Comment by PingWeb** [comment] 2023-09-26 14:22
It did work yesterday, but today (again without any changes or updates) it stopped working again... 😕

**Comment by donihalim** [comment] 2023-10-11 04:59
Any update on this?

**Comment by chaoscreater** [comment] 2023-11-14 22:22
I'm not getting notifications for Outlook and Teams. In both my Outlook and Teams account settings, I've configured notification to be allowed and Ferdium notification is enabled. I see the unread notification banner on Teams icon in Ferdium, but I don't get any notifications.

In Chromium based browsers, you have to also grant notification permission on the site itself under Site Settings. Here's an example:
vivaldi://settings/content/siteDetails?site=https%3A%2F%2Foutlook.office.com

By default, the notification permission for Site Settings would be Ask instead of Allow. I'm not sure how to get to this in Ferdium.

**Comment by NgoHuy** [comment] 2023-12-27 10:10
I disabled this option and got first notification, after that no notification at all. debug is needed
![image](https://github.com/ferdium/ferdium-app/assets/1238112/d8524c79-f8ed-48f1-a6d1-730c44b0e3a6)

**Comment by NgoHuy** [comment] 2023-12-27 14:53
I saw that only notification when new chat came, not new message on existing chat. look at the code now

**Comment by Martzy303** [comment] 2024-02-02 02:37
> I'm not getting notifications for Outlook and Teams. In both my Outlook and Teams account settings, I've configured notification to be allowed and Ferdium notification is enabled. I see the unread notification banner on Teams icon in Ferdium, but I don't get any notifications.
> 
> In Chromium based browsers, you have to also grant notification permission on the site itself under Site Settings. Here's an example: vivaldi://settings/content/siteDetails?site=https%3A%2F%2Foutlook.office.com
> 
> By default, the notification permission for Site Settings would be Ask instead of Allow. I'm not sure how to get to this in Ferdium.

Same, I can hear the sound but no notification.
And I think I know why, in browsers the notification from Outlook are not browser/push notifications, they are some notifications made by them, Ferdium displays push/browser notifications, the ones that outlook send can't be "catched" by Ferdium, at least not with some real work.

**Comment by chaoscreater** [comment] 2024-02-02 02:42
> > I'm not getting notifications for Outlook and Teams. In both my Outlook and Teams account settings, I've configured notification to be allowed and Ferdium notification is enabled. I see the unread notification banner on Teams icon in Ferdium, but I don't get any notifications.
> > In Chromium based browsers, you have to also grant notification permission on the site itself under Site Settings. Here's an example: vivaldi://settings/content/siteDetails?site=https%3A%2F%[2Foutlook.office.com](http://2Foutlook.office.com)
> > By default, the notification permission for Site Settings would be Ask instead of Allow. I'm not sure how to get to this in Ferdium.
> 
> Same, I can hear the sound but no notification. And I think I know why, in browsers the notification from Outlook are not browser/push notifications, they are some notifications made by them, Ferdium displays push/browser notifications, the ones that outlook send can't be "catched" by Ferdium, at least not with some real work.

But when you enable notifications in Outlook web app, it prompts for Notification permission by the browser. So it must be using some sort of push/browser notification? And I thought Ferdium is Chromium based, so why wouldn't it work? My Outlook notifications work fine on all other Chromium browsers.

Anyway, I manage to workaround my issue by using Chrome to create a PWA for Outlook and I get notifications and sound just fine. It's kinda nice this way, as the cookies for Microsoft domains such as Azure or Outlook or Teams are not necessarily working well in all Chromium browsers. Brave browser for example always requires you to login to Azure and doesn't save the cookies, but it's not the case for Chrome. By using Ferdium, I run into some of those issues.

**Comment by Cozynezz** [comment] 2024-03-01 21:14
I have the same problem here

**Comment by nerdCopter** [comment] 2024-04-09 20:33
i went form no Teams notifications, to double-notifications.

Debian 12, XFCE 4.18, Ferdium 6.7.2, Teams Service. "New Teams" UI that was recently released Mar/Apr 2024.

**Closed as completed** 2024-05-13 21:31 UTC
