### ISSUE TITLE
Bug: Services are loading infinitely in some conditions

### ISSUE THREAD

**Issue by MagicLegend** [ferdium/ferdium-app#157] opened 2022-05-16 07:02 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.37

### What Operating System are you using?

Ubuntu

### Operating System Version

Linux <name> 5.13.0-41-generic #46~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What arch are you using?

x64

### Expected Behavior

It works.

### Actual Behavior

6 out of 8 newly added services get stuck at `Loading <service>`.

### Steps to reproduce

1. Install Ferdium
2. Add multiple services
3. Some should get stuck on loading

### Screenshots

![image](https://user-images.githubusercontent.com/3169104/168537000-ca262412-4a53-4cd1-96a2-e5883f1a03a5.png)
![image](https://user-images.githubusercontent.com/3169104/168537015-f6e6d5a0-2c81-4c94-813e-d687c297f8fc.png)
![image](https://user-images.githubusercontent.com/3169104/168537031-ce6fe102-ac37-4543-ab7a-e7af311898f0.png)

### Additional information

While writing this issue it seems that Gmail and Outlook got un-stuck.
Reloading the service was not enough (although the service did refresh), only reloading Ferdium fixed it.

**Comment by SpecialAro** [comment] 2022-05-16 09:33
I was able to replicate this issue when adding 7 services. Only 1 got stuck (Messenger) and the reload of the service didn't work - only the reloading of Ferdium (as @MagicLegend indicates) solved the problem.

**Comment by Evan-aja** [comment] 2022-05-16 10:27
> I was able to replicate this issue when adding 7 services. Only 1 got stuck (Messenger) and the reload of the service didn't work - only the reloading of Ferdium (as @MagicLegend indicates) solved the problem.

I have encountered this issue as well a few days ago. in my setup there is __one enabled__ (WhatsApp) service and __six disabled__ (2 Gmails, 2 Elements, Discord, and Telegram) at all time. 

And the loading indicator bug shows up randomly at startup and i don't know why. My way of circumventing this issue is by holding any nightly update until the error occurs, updates when it occurs, hold it again from updating, rinse and repeat (tested on both __ArchLinux__ and __OpenSUSE Tumbleweed__).

**Comment by vraravam** [comment] 2022-05-17 21:46
I have sporadically experienced this issue as well on my mac. The only thing that I could attribute this to was the network lag.  When many services are trying to use the same available limited bandwidth (for eg if I was tethering from my phone and restarting Ferdium, then this is pretty consistent when multiple services are initializing). I'm not too sure whether this is a high priority bug though.

**Comment by CPickens42** [comment] 2022-05-17 23:09
I also experienced this issue several times. It can also happens when switching to another workspace (without adding any services), but it's more rare. I don't think it's caused by a network lag, I have a very good connection, and the website/service always seems loaded. It feels like the loading display "just not received the message" that the service has been loaded for some reason. :thinking:

**Comment by maxecharel** [comment] 2022-05-22 23:17
same issue here (Kubuntu 22.04, snap install); reloading (C-R) do not systematically work though. I also had to disable then re-enable the service, which is not really convenient

**Comment by vraravam** [comment] 2022-05-23 12:07
Is this a duplicate of #181 ?

**Comment by maxecharel** [comment] 2022-05-23 12:32
> Is this a duplicate of #181 ?

#181 specifically targets waking up services, but according to your diagnosis @vraravam the roots of the problem are the same

**Comment by vraravam** [comment] 2022-05-23 13:52
> > Is this a duplicate of #181 ?
> 
> #181 specifically targets waking up services, but according to your diagnosis @vraravam the roots of the problem are the same

Yes - to me they both have the same root cause

**Comment by MagicLegend** [comment] 2022-05-24 12:41
I did not install it through snap though - I manually installed the deb with apt.

**Comment by kris7t** [comment] 2022-06-12 15:55
@vraravam It seems we set `isLoading = true` on the `Service` model if the `did-start-loading` event fires on the webview, and set `isLoading = false` either if the `did-fail-load` event fires (not ideal), or either of the `did-frame-finish-load` or `did-navigate` event fires. I wonder if there can be some kind of race condition there can be some race condition in there.

One option would be to also listen for the [`did-stop-loading`](https://www.electronjs.org/docs/latest/api/web-contents#event-did-stop-loading) event to be more robust. But the semantics of the event here seem to have subtle differences (the `-loading` family of events seem to be connected to the tab spinner in chromium, while the `-load` events refer to the actual page load).

In particular, the subtle this is that `did-stop-loading` also fires if there's an error, so we'd have to be extra careful to still be able to report errors on `did-fail-load` (if there's indeed a race condition).

---

Contrast this with the logic I came up with in sophie (which is barely tested and probably similarly buggy in some ways, but attempts to use the `did-stop-loading` event):

https://gitlab.com/say-hi-to-sophie/sophie/-/blob/main/packages/main/src/stores/Service.ts#L195-233

https://gitlab.com/say-hi-to-sophie/sophie/-/blob/main/packages/main/src/infrastructure/electron/impl/ElectronServiceView.ts#L86-153

**Closed as completed** 2022-06-19 23:03 UTC
Labels: bug :beetle:

**Comment by maxecharel** [comment] 2022-06-20 11:00
just upgraded Ferdium and the related issue disappeared; for me this is a game changer. Thanks a lot @kris7t and others!

**Comment by Moortu** [comment] 2022-08-27 13:13
It's back for me
![Untitled2](https://user-images.githubusercontent.com/29175880/187031798-b2683cb1-9a13-4b47-ab06-199e1a713050.png)

version 6.1.0

**Comment by SpecialAro** [comment] 2022-08-28 08:56
> It's back for me
> ![Untitled2](https://user-images.githubusercontent.com/29175880/187031798-b2683cb1-9a13-4b47-ab06-199e1a713050.png)
> 
> version 6.1.0
> 

Please hard restart Ferdium, that should work.

**Comment by giuseppecarrera** [comment] 2023-01-11 12:09
![2023-01-11_13-00](https://user-images.githubusercontent.com/38856297/211802493-2c301747-1f2b-47b9-a1d8-ca9f20956f67.jpg)

Ferdium 6.2.3
Ubuntu 22.04 LTS
The messagge you can see below appears often when you start a service, non allowing to use it. I have to quit Ferdium and then restart.

**Comment by vraravam** [comment] 2023-01-11 13:52
@giuseppecarrera - you don't need to quit Ferdium completed. If this situation occurs, you can reload only that service with `Cmd+R` (macos) or `Ctrl+R` (windows/linux)

**Comment by giuseppecarrera** [comment] 2023-01-11 19:48
@vraravam I already tried but it doesn't works, at least for me.

**Comment by jpsnyder** [comment] 2023-02-02 14:13
Same issue happens for me. `Ctrl+R` will reload the service, but the spinning wheel is still there.

**Comment by MagicLegend** [comment] 2023-02-03 08:02
Reloading all of Ferdium does fix it, but it's essentially a restart of course.

**Comment by giuseppecarrera** [comment] 2023-02-03 09:53
Of course.

Il giorno ven 3 feb 2023 alle ore 09:02 MagicLegend <
***@***.***> ha scritto:
