### ISSUE TITLE
Bug: Badge count does not reset

### ISSUE THREAD

**Issue by leoheck** [ferdium/ferdium-app#770] opened 2022-11-15 14:59 UTC
I could not reset this count. Any idea on how can I workaround this?

![image](https://user-images.githubusercontent.com/1277920/201951985-2b9f2907-e3a6-4979-ab18-b053ebd22e18.png)

Version: 6.2.1-nightly.7
Server: No Server
Electron: 21.0.1
Chrome: 106.0.5249.61
Node.js: 16.16.0
Platform: Linux 5.15
Arch: x64
Build date: Fri Sep 30 2022 00:32:10 GMT-0300 (Brasilia Standard Time)
Git SHA: 81cc1752
Git branch: nightly

**Comment by leoheck** [comment] 2022-11-15 15:03
Upgrading it to the latest version did not fix it. 

Version: 6.2.1-nightly.44
Server: No Server
Electron: 21.2.2
Chrome: 106.0.5249.168
Node.js: 16.16.0
Platform: Linux 5.15
Arch: x64
Build date: Fri Nov 11 2022 22:06:42 GMT-0300 (Brasilia Standard Time)
Git SHA: afff1d9c
Git branch: nightly

**Comment by leoheck** [comment] 2022-11-15 15:03
Reloading the service did not fix it too.

**Comment by MazzMat** [comment] 2022-11-15 15:03
Me too with stable release

Version: 6.2.0
Server: No Server
Electron: 20.2.0
Chrome: 104.0.5112.124
Node.js: 16.15.0
Platform: macOS Monterey
Arch: arm64
Build date: Thu Sep 22 2022 18:47:30 GMT+0200 (Ora legale dell’Europa centrale)
Git SHA: 84613b5b
Git branch: release

**Comment by vraravam** [comment] 2022-11-15 15:32
Closing as a duplicate of [#ferdium-recipes#230](https://github.com/ferdium/ferdium-recipes/issues/230)

**Closed as completed by vraravam** 2022-11-15 15:32 UTC
Labels: bug :beetle:
