### ISSUE TITLE
Feature: Hide app menu

### ISSUE THREAD

**Issue by FANMixco** [ferdium/ferdium-app#530] opened 2022-07-30 20:26 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently, there is no option to hide the top menu:

<img width="350" alt="image" src="https://user-images.githubusercontent.com/1666156/181995096-b521d978-361c-4369-bf40-864f017379c8.png">

### Proposed Solution

Add a new option to hide the menu in the Settings => Appearance where we can have a new option called, "Hide top menu".

### Alternatives Considered

N/A

**Comment by mcmxcdev** [comment] 2023-10-01 19:31
Hey @FANMixco, it seems the functionality you wish for is actually implemented:

[Screencast from 2023-10-01 13-28-53.webm](https://github.com/ferdium/ferdium-app/assets/16797721/27483e02-ce7d-4dc6-84a7-1db18a81a372)

Let me know if this works for you!

**Comment by FANMixco** [comment] 2023-10-01 19:43
> Hey @FANMixco, it seems the functionality you wish for is actually implemented:
> 
>  Screencast.from.2023-10-01.13-28-53.webm 
> Let me know if this works for you!

It doesn't work in my case:

<img width="344" alt="image" src="https://github.com/ferdium/ferdium-app/assets/1666156/c8a4f26f-4898-4af7-902d-7d648cb10a5e">

<img width="676" alt="image" src="https://github.com/ferdium/ferdium-app/assets/1666156/5adcc741-4765-4754-b0a1-56cfe72a0561">

<img width="344" alt="image" src="https://github.com/ferdium/ferdium-app/assets/1666156/caf33b04-247f-45c6-a0a0-6f399648191c">

**Comment by mcmxcdev** [comment] 2023-10-01 20:09
Thanks for the reproduction!

I see now that this problem is Windows-specific, closing as duplicate of https://github.com/ferdium/ferdium-app/issues/513

**Closed as completed by mcmxcdev** 2023-10-01 20:09 UTC
Labels: enhancement :sparkles:
