### ISSUE TITLE
Bug: WhatsApp pulling wrong notification count from archived chat

### ISSUE THREAD

**Issue by fenglengshun** [ferdium/ferdium-app#1118] opened 2023-04-18 08:12 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.6 (Flatpak)

### What Operating System are you using?

Other Linux

### Operating System Version

Linux tuxedo-laptop 6.2.0-10005-tuxedo #5 SMP PREEMPT_DYNAMIC Wed Mar 22 12:42:40 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 22.04-based)

### What arch are you using?

x64

### Expected Behavior

WhatsApp pull current total notification correctly, or just indicate there is a notification in the main inbox.

### Actual Behavior

It randomly uses one of the notification counts of the archived chats. It correctly uses the total current chat IF there isn't any unread chats in the archived chats

### Steps to reproduce

1. Use WhatsApp service
2. Have archived chats
3. Get new messages in archived chats.

### Additional information

Will take a screenshot later, just finished clearing my unread archived chats.

**Comment by marie-bnl** [comment] 2023-04-22 21:37
I made the pull request such that the unread counter counts messages from non-archived conversations only. To be sure, is it the expected behaviour?

**Comment by Alphrag** [comment] 2023-04-24 22:53
I am also quite puzzled by this since I have not had the problem you describe with unread messages in my archived chats: if I have some unread messages in archive chats, then this number is reflected in the total count. Maybe this should only be added to the indirect count? 
@bayazidbh If you can provide a screenshot that would indeed be quite useful to see what is going on to better understand the problem 🙂

**Comment by marie-bnl** [comment] 2023-04-25 09:54
I don’t know if a screenshot it really that useful but here it is

<p>
<img width="300px" src="https://user-images.githubusercontent.com/39555268/234240784-ca969a0d-4ad4-4380-b976-305efdc3c722.png">
&nbsp;
<img width="300px" src="https://user-images.githubusercontent.com/39555268/234241078-90d65c0a-8e62-4903-b416-6b4d31923e1f.png">
</p>

**Comment by fenglengshun** [comment] 2023-04-25 17:10
> @bayazidbh If you can provide a screenshot that would indeed be quite useful to see what is going on to better understand the problem slightly_smiling_face

@Alphrag  I'll try to get some next week -- I had just cleared out my unread chats before making this report, and haven't used WhatsApp that much in the past week since I am currently off from work.

What makes me convinced it's the Archived Chat is because the badge at the Ferdium sidebar shows "23", regardless of me marking things as read, up until I also marked as read an archived chat that has "23" unreads.

Is there any extra steps I could do to get extra logs, since it might take a while for it to occur again?

**Comment by marie-bnl** [comment] 2023-04-25 19:51
> What makes me convinced it's the Archived Chat is because the badge at the Ferdium sidebar shows "23", regardless of me marking things as read, up until I also marked as read an archived chat that has "23" unreads.

We can second that just by looking at the code anyway − the loop that goes through every chat in order to add their counter to the main one doesn’t do any check to see if it’s an archived one.

> Is there any extra steps I could do to get extra logs, since it might take a while for it to occur again?

There is no need to, since we’ve clearly identified the issue, where it comes from, and how to solve it.

---

All we need now is to find an agreement on what should be the behaviour. That is, choose between

1. Don’t count archived conversations at all
2. Count archived conversations in the indirect counter
3. Keep the current behaviour considering it not-a-bug, and keep counting archived conversations in the direct messages counter (I’m putting it here as an eventuality, even though I don’t know if it makes much sense to do so)

What would you expect Ferdium to do?

**Comment by Alphrag** [comment] 2023-04-26 10:58
> What makes me convinced it's the Archived Chat is because the badge at the Ferdium sidebar shows "23", regardless of me marking things as read, up until I also marked as read an archived chat that has "23" unreads.

This is what surprises me. There is no reason why it overrides the unread count, it should only increment it further. I have also noticed recently that some of my normal chats or "community" chats are not counted appropriately. But then, it was also a problem on the web version in a normal browser, so I guess that whatsapp has an inherent bug there.

> All we need now is to find an agreement on what should be the behaviour. That is, choose between [options 1,2 and 3]
> What would you expect Ferdium to do?

Personally, I think that archived chats should still be counted but put into the indirect count, that is, putting the test on line 42 instead:
https://github.com/ferdium/ferdium-recipes/blob/bd164b034506954076b7bb164cbfeeadbb927d5a/recipes/whatsapp/webview.js#L42

**Comment by marie-bnl** [comment] 2023-04-26 13:33
> This is what surprises me. There is no reason why it overrides the unread count, it should only increment it further. I have also noticed recently that some of my normal chats or "community" chats are not counted appropriately. But then, it was also a problem on the web version in a normal browser, so I guess that whatsapp has an inherent bug there.

Oh my bad I had misread the message. This is strange indeed.

> Personally, I think that archived chats should still be counted but put into the indirect count

I think that makes sense.

**Comment by fenglengshun** [comment] 2023-04-27 04:25
> What would you expect Ferdium to do?

While I wouldn't mind them being counted in some way IMHO people uses chat archival so that they wouldn't be bothered, so I think it shouldn't be counted. _Maybe_ there could be a webview.js option for reverting it to the old behavior if people need it, but I personally think it should err on the side of assuming archived chats are something people don't need to know of all the time in badges/titles.

**Comment by marie-bnl** [comment] 2023-04-27 10:54
I updated my pull request to add archived unread counts as indirect. What is left to do now is test it to see if the bug still occurs.

**Comment by fenglengshun** [comment] 2023-04-28 07:12
So, I managed to record the issue, and based on what I remembered of the last time I got it, it seems that the bug only gets triggered when there are three archived chats:

https://user-images.githubusercontent.com/26621899/235078913-4ac47aaa-0053-4de7-9ba3-2215ee0c86e0.mp4

As can be seen, the unread counts reads my main chats unreads (2) + one of the archived chats unreads (12). Once I clicked on the unread main chat, it drops from 14 to 12. I clicked on the unread archived chats, one by one, until I got to the last one, which has 12 unreads. Then the unread badge disappear.

Coincidentally, I have two pinned chats, so that might be a factor?

**Comment by marie-bnl** [comment] 2023-04-28 11:17
Can you update your services (either wait for it to be updated or manually download the whatsapp recipe for the ferdium-recipes repository and replace that in `~/.config/Ferdium/recipes` by the downloaded one) and make sure you are using WhatsApp version 3.4.10, and see if the issue is fixed?

**Comment by fenglengshun** [comment] 2023-05-02 09:00
@victorbnl currently waiting for more archived chats, so far the issue didn't crop up again, so now I'm pretty sure it only pop up when I have more than 2 separate chats with unread in archive. I'll make sure to test once I got 3 different unread chats in archived.

**Comment by fenglengshun** [comment] 2023-05-10 09:36
Sorry it took me a while @victorbnl but I can confirm that it's fixed. Before I updated the recipe, it was counting the bottom-most of the unread archived chats, after I updated the recipe and restarted Ferdium, it no longer does that.

**Comment by mcmxcdev** [comment] 2023-08-06 22:12
Seems like the OP of this issue confirmed it as fixed, closing.

**Closed as completed by mcmxcdev** 2023-08-06 22:12 UTC
Labels: bug :beetle:

**Comment by ahmed-zhran** [comment] 2023-11-02 00:04
the problem come back again after this commit [Fix WhatsApp count](https://github.com/ferdium/ferdium-recipes/commit/fd169b7b2ad80abce5b044909d5234f0ea6a1c27)
