### ISSUE TITLE
Discord and Microsoft Todos not automatically signing in 

### ISSUE THREAD

**Issue by katastrophe92** [ferdium/ferdium-app#1124] opened 2023-04-24 07:21 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.2.6

### Recipe Name

Discord and built in Microsoft Todos tab

### Recipe Version

1.7.9

### Last Known working version of the recipe

I do not know

### Steps to reproduce

1. Start Ferdium app
2. Go to Discord

### Expected Behavior

Not log in every time

### Actual Behavior

Asking for Discord password

**Comment by Rihcus** [comment] 2023-05-31 01:56
I have same issue. Closing feridium or hibernating the discord service seems to cause this.

**Comment by genna87** [comment] 2023-10-27 12:03
Same issue on Windows and Linux

**Comment by Hatko** [comment] 2024-01-12 09:38
Quite a serious issue - every time I open the app, or turn on my laptop, I have to spend up to a minute on signing in into both apps

**Comment by katastrophe92** [comment] 2024-01-22 09:09
@mydarkstar Hey! Is this bug still unfixed? Thanks

**Comment by mydarkstar** [comment] 2024-01-24 00:34
> @mydarkstar Hey! Is this bug still unfixed? Thanks

I don't use Discord in Ferdium myself, and I cannot reproduce the issue, as /login just redirects me into the app if I'm already logged in.
However, I now created a PR to set the `serviceURL` to `/app` instead, which should hopefully work better.

If anybody who experiences the issue could review this change, it would be great to receive feedback.
But it should be merged either way, since it seems to be the better approach.

**Comment by mydarkstar** [comment] 2024-01-24 00:56
I cannot reproduce any issue with Microsoft To Do.
Please make sure to select "Yes" when the login wizard asks you whether you'd like to "Stay signed in?"

**Closed as completed** 2024-01-24 11:08 UTC
Labels: bug :beetle:, recipe :bookmark_tabs:

**Comment by Arkonos** [comment] 2024-01-24 11:18
I've changed 
`"serviceURL": "https://discord.com/login",` to `"serviceURL": "https://discord.com/app",` in `~/.config/Ferdium/recipes/discord/package.json `. Then I terminated the running program and launched it again. Logged into discord, closed and reopened Ferdium, but sadly, still the same issue.

**Comment by Michaelknubben** [comment] 2025-02-13 08:31
This was closed, but I'm still currently having this issue with Discord. I see an attempt to fix it, but it's unclear to me why this was closed as there was no confirmation of it having the desired effect?
