### ISSUE TITLE
Bug: WhatsApp modals are broken by Ferdium intervention

### ISSUE THREAD

**Issue by lolmaus** [ferdium/ferdium-app#595] opened 2022-09-02 08:40 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.1.1-nightly.1 (later nightlies have this problem too)

### What Operating System are you using?

Ubuntu

### Operating System Version

Windows 10, Linux Mint (Ubuntu-based)

### What arch are you using?

x64

### Last Known Working Ferdium version

6.0.0 maybe

### Expected Behavior

I open a modal in WhatsApp.
I'm able to confirm it.

### Actual Behavior

Ferdium seems to have special override for the Dark Theme modal: it inserts a warning and removes the OK button, preventing you from setting a Dark Theme with WhatsApp and instead encouraging to do it with Ferdium.

The problem is that Ferdium erroneously applies this override to ALL WhatsApp modals.

E. g. this is what I see when trying to make a user an admin: (screenshots attached below)

### Steps to reproduce

1. Open any modal in WhatsApp.

(e. g. try making a user an admin in a group chat)

### Debug link

https://debug.ferdium.org/0f728c83-782e-44ff-a86d-7c54e0061e5d

### Screenshots

![image](https://user-images.githubusercontent.com/200884/188100433-72e96474-403f-4fa5-8bce-c150441323e4.png)

**Comment by SpecialAro** [comment] 2022-09-02 08:55
Duplicate of https://github.com/ferdium/ferdium-app/issues/573

**Closed as not planned by SpecialAro** 2022-09-02 08:55 UTC
Labels: duplicate :mirror:
