### ISSUE TITLE
Discord crashes Ferdium when trying to share screen

### ISSUE THREAD

**Issue by AnghelRA** [ferdium/ferdium-app#1099] opened 2023-04-06 09:12 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.6

### What Operating System are you using?

Other Linux

### Operating System Version

Nobara 37

### What arch are you using?

x64

### Expected Behavior

I want to share my screen in a discord call.

### Actual Behavior

When I try to share my screen, ferdium crashes.

### Steps to reproduce

1. Open discord
2. Join a server voice chat
3. Press Share Your Screen

### Debug link

https://debug.ferdium.org/60474834-6b78-4681-92ee-cb0135a49932

### Additional information

I am using the flatpak version of Ferdium on wayland with pipewire, with nvidia gpu and kde desktop. Had the same issue on garuda linux wayland, not reproducible on x11.

**Comment by hadogenes** [comment] 2023-04-08 17:09
It is electron bug
duplicate #1044

**Comment by vraravam** [comment] 2023-04-08 17:41
Electron just released a new version, which we have integrated to and released as a new [nightly](https://github.com/ferdium/ferdium-app/releases/tag/v6.2.7-nightly.3) - please try it out and get back if this fixes your issue.

**Comment by SimonSchwendele** [comment] 2023-04-08 20:16
@vraravam 
I just updated to `6.2.7_nightly.4-1` and screensharing still crashes in Discord, Jitsi and Teams.

```bash
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
...
...
Error occurred in handler for 'GUEST_VIEW_MANAGER_CALL': Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at node:electron/js2c/renderer_init:2:16905
    at EventEmitter.<anonymous> (node:electron/js2c/renderer_init:2:11094)
    at EventEmitter.emit (node:events:513:28)
    at Object.onMessage (node:electron/js2c/renderer_init:2:9197)
```

```bash
Version: 6.2.7-nightly.4
Server: No Server
Electron: 24.0.0
Chrome: 112.0.5615.49
Node.js: 18.14.0
Platform: Linux 6.3
Arch: x64
Build date: Sat Apr 08 2023 02:50:16 GMT+0200 (Central European Summer Time)
Git SHA: 5661f54c
Git branch: nightly
```

Im on Fedora 37 using the rpm.
```bash
CPU: AMD Ryzen 9 6900HS with Radeon Graphics (16) @ 4.925GHz 
GPU: NVIDIA Geforce RTX 3070 Ti Laptop GPU
GPU: AMD ATI Radeon 680M 
```

**Comment by taz40** [comment] 2023-04-12 18:31
I am experiencing the same issue on Arch linux with both the AUR and Appimage versions (both nightly).
The application segfaults immediately after attempting to start a screen share in discord.
```
Version: 6.2.7-nightly.4
Server: No Server
Electron: 24.0.0
Chrome: 112.0.5615.49
Node.js: 18.14.0
Platform: Linux 6.2
Arch: x64
Build date: Fri Apr 07 2023 18:50:16 GMT-0600 (Mountain Daylight Time)
Git SHA: 5661f54c
Git branch: nightly
```

System Info:
```
OS: ArcoLinux x86_64
CPU: Intel i5-8250U
GPU: Intel UHD Graphics 620
Desktop: SwayWM
```

**Comment by dan-myles** [comment] 2023-04-27 20:41
When manually switching electron version to `"electron": "21.4.2"` in the package.json, and building from latest git commit `6.2.7-nighty.7`, ferdium will *not crash* when sharing screen. However screensharing still does not work as no QT menu is popping up to select screen as it does in Chrome, however this is definitely a separate issue.

```
                 `ooo/                   OS: Arch Linux x86_64
                `+oooo:                  Host: MS-7D08 1.0
               `+oooooo:                 Kernel: 6.2.12-arch1-1
               -+oooooo+:                Uptime: 14 hours, 38 mins
             `/:-:++oooo+:               Packages: 762 (pacman)
            `/++++/+++++++:              Shell: zsh 5.9
           `/++++++++++++++:             Resolution: 2560x1440
          `/+++ooooooooooooo/`           DE: Hyprland
         ./ooosssso++osssssso+`          Theme: Layan-Dark [GTK3]
        .oossssso-````/ossssss+`         Terminal: tmux
       -osssssso.      :ssssssso.        CPU: Intel i9-10900K (20) @ 5.300GHz
      :osssssss/        osssso+++.       GPU: NVIDIA GeForce RTX 3080
     /ossssssss/        +ssssooo/-       Memory: 3231MiB / 31991MiB

```

**Comment by SimonSchwendele** [comment] 2023-05-21 21:49
Still broken on `6.3.0-nightly-8`...
Guess we'll have to wait a long while longer

**Comment by vraravam** [comment] 2023-05-22 04:20
no one is working on this atm. so please do not spam for each nightly that this is still not fixed.

**Comment by maurerle** [comment] 2023-06-07 22:02
Just want to mention that this is not limited to Discord but also crashes in other apps for example MS Teams.
Maybe the title should be changed here.

But of course, this issue still occurs on 6.4.0 (including nightly) using Debian 12 Bookworm with Wayland

Downgrading to v6.2.3 helped for me:
https://github.com/ferdium/ferdium-app/releases/tag/v6.2.3

**Comment by AnghelRA** [comment] 2023-07-14 15:56
I just downloaded v6.4.1-nightly.4 and the issue is fixed, it looks like electron was updated to use xdg-desktop-portal.

**Comment by SimonSchwendele** [comment] 2023-07-15 13:17
> I just downloaded v6.4.1-nightly.4 and the issue is fixed, it looks like electron was updated to use xdg-desktop-portal.

Apparently you're right.
For some reason I have to select an application before I can choose to share the whole screen :/

When sharing the whole screen it however freezes after a few seconds and flooding my terminal with:
```
[22753:0715/151121.000978:ERROR:shared_screencast_stream.cc(940)] Dropping DMA-BUF modifier: 72057594037927935 and trying to renegotiate stream parameters
[22753:0715/151121.012640:ERROR:egl_dmabuf.cc(608)] Failed to record frame: Error creating EGLImage - EGL_NOT_INITIALIZED
```

But those might be as well gnome/mutter/pipewire errors

**Comment by srwi** [comment] 2023-09-02 14:45
This crash will be fixed by upgrading to electron 26.0 as it includes the corresponding fix: https://github.com/electron/electron/pull/39264
According to my understanding this fix is not backported to older versions of electron.

Unfortunately upgrading to 26.0 causes #1317. Currently that issue was solved by downgrading to electron 25.

**Comment by mcmxcdev** [comment] 2023-09-02 18:50
Pretty bad double bind situation, but fixing Ferdium not working at all is more important than the screen sharing bug.

Ideally, we will be able to upgrade to Electron v26 again once all the issues of a new major version are ironed out and have both bugs fixed.

**Comment by srwi** [comment] 2023-09-03 20:21
It looks like #1317 is caused by this electron bug: https://github.com/electron/electron/issues/39515

As soon as that is fixed we should be able to upgrade to electron 26 again and in turn get the screen sharing bug fixed.

**Comment by 392781** [comment] 2023-09-29 23:19
@srwi @mcmxcdev not only is screensharing broken, Discord doesn't connect to voice at all anymore with latest version of Ferdium.  Their webapp works fine but Ferdium hangs on "RTC Connecting..."

**Comment by mcmxcdev** [comment] 2023-09-29 23:25
@392781  You can find the solution for the Discord call issue you are having here: https://github.com/ferdium/ferdium-app/issues/611#issuecomment-1263271328

**Comment by 392781** [comment] 2023-09-29 23:41
Thank you @mcmxcdev!

**Comment by AnghelRA** [comment] 2023-10-04 06:52
On ferdium 6.5.1 screen sharing is working for me

**Comment by mcmxcdev** [comment] 2023-10-21 22:35
For anyone still encountering issues, there is now a nightly release available using Electron v27: https://github.com/ferdium/ferdium-app/releases/tag/v6.5.3-nightly.3

**Comment by mcmxcdev** [comment] 2023-10-27 14:53
This should now also be fixed in the latest stable: https://github.com/ferdium/ferdium-app/releases/tag/v6.6.0

Let me know if this is not the case ;)

**Closed as completed by mcmxcdev** 2023-10-27 14:53 UTC
Labels: bug :beetle:, linux
