### ISSUE TITLE
Bug: The service icons under a Workspace can't be re-ordered with any precision.

### ISSUE THREAD

**Issue by LLI-inc** [ferdium/ferdium-app#576] opened 2022-08-26 02:45 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0

### What Operating System are you using?

Windows

### Operating System Version

Windows 11 22000.856

### What arch are you using?

x64

### Last Known Working Ferdium version

6.0.0

### Expected Behavior

I would expect to be able to rearrange these icons into whatever order I'd like. I would expect that when I move one up one space that it would land in that space.

![image](https://user-images.githubusercontent.com/46686069/186805081-70b94977-b24a-4b9a-9c6f-cd79b663505b.png)

### Actual Behavior

Instead of landing where I place them, they usually bounce back to where they started. Although sometimes one or another will move - but not to where I would expect it to land.

### Steps to reproduce

Try to move the service icons with your mouse into the desired spot. See if it stays where you put it.

**Comment by SpecialAro** [comment] 2022-08-26 17:08
Closing issue as duplicate of https://github.com/ferdium/ferdium-app/issues/293

**Closed as not planned** 2022-08-26 17:09 UTC
Labels: duplicate :mirror:
