### ISSUE TITLE
Upgrade `ace` dependencies

### ISSUE THREAD

**Issue by vraravam** [ferdium/ferdium-app#44] opened 2022-04-25 00:34 UTC
### Your issue

We are using v5.x of `ace` whereas the public version available is at v11 - need to upgrade

**Comment by mcmxcdev** [comment] 2023-07-29 03:51
Closing as duplicate of https://github.com/ferdium/ferdium-app/issues/242, which has more information.

**Closed as completed by mcmxcdev** 2023-07-29 03:51 UTC
Labels: tech debt :heavy_dollar_sign:
