### ISSUE TITLE
Bug: WhatsApp unread count is incorrect

### ISSUE THREAD

**Issue by huang-jy** [ferdium/ferdium-app#764] opened 2022-11-13 20:09 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.0

### What Operating System are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Ferdium version

Unknown

### Expected Behavior

Unread count to be consistent to app

### Actual Behavior

Unread counter for WhatsApp shows completely incorrect quantity (sometimes shows 44, sometimes 125) and randomly switches between values when interacting with chats

![image](https://user-images.githubusercontent.com/2756283/201542072-a6e60c53-7446-46e0-9589-22f51cbf5d6e.png)

### Steps to reproduce

1. Use WhatsApp

### Debug link

https://debug.ferdium.org/fa134c2d-cc7b-4fc1-823c-0b55e21e7b3e

### Additional information

This behaviour seems to be new. Not sure if it's something with Ferdium (since the the same behaviour exists when running the Linux version under Fedora), or whether the WhatsApp web app has changed recently making the unread counter behave differently

**Comment by cino** [comment] 2022-11-13 20:19
Duplicate of https://github.com/ferdium/ferdium-recipes/issues/230 with PR in process https://github.com/ferdium/ferdium-recipes/pull/235

**Closed as not planned by cino** 2022-11-13 20:19 UTC
Labels: duplicate :mirror:
