### ISSUE TITLE
Could not load services and user information after start

### ISSUE THREAD

**Issue by Wlkus** [ferdium/ferdium-app#1926] opened 2024-10-14 17:48 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.7

### What Operating System are you using?

Windows

### Operating System Version

Windows 11 Pro 22H2

### What arch are you using?

x64

### Last Known Working Ferdium version

6.7.7

### Expected Behavior

Load profile and run as usually

### Actual Behavior

Message Could not load service after start for 1-5 minutes, then load profile. Total random, sometimes runs immediately, sometimes waits for few minutes.

### Steps to reproduce

Start app
Wait for profile to load

### Debug link

https://debug.ferdium.org/f3f2e13f-d5e0-4bd7-9e22-5b65415c56c7

### Additional information

Tried to clear cache, just lost logins in all services. After reauthorising everything and restart, again waiting for Could not load services message...

Started few days ago, total random behavior, sometimes it loads after few seconds, most of the time its 1m+
Have stable ethernet 120 Mbps connection, no internet issues.

**Comment by noahbliss** [comment] 2024-10-14 18:31
I think the servers might be down.

**Comment by survfate** [comment] 2024-10-14 18:36
> I think the servers might be down.

look like that the case for me as well

edit: seem to be back to normal

**Comment by Milincho** [comment] 2024-10-14 21:26
Still happening here. With both 6.7.7 and 6.7.8 Nightly

**Comment by tristengrant** [comment] 2024-10-14 21:26
Still not working for me. Hopefully its just the servers since its worked again for others.

**Comment by noahbliss** [comment] 2024-10-14 21:48
Does seem that this reveals a troubling design weakness of not caching the last known list of services and letting us access them anyways.

**Comment by vraravam** [comment] 2024-10-15 03:02
There's an "accountless" option to move from a hosted server model to an local one. you can move to that so as to safeguarded against server-outages.

**Comment by yvhr** [comment] 2024-10-17 02:54
Is there a healthcheck page to verify if the server's really down? I'm also encountering the same issue, but only encountered it just now. It was working yesterday without issue.

**Comment by vraravam** [comment] 2024-10-17 04:49
> Is there a healthcheck page to verify if the server's really down? I'm also encountering the same issue, but only encountered it just now. It was working yesterday without issue.

We get automated notifications on our Discord server. Whether there's a web page to broadcast this - im not really sure

**Comment by RJVB** [comment] 2024-10-20 18:53
Just started to have the same problem (in France). I'm still on 6.7.3 but it's been working just fine until now, even added another service yesterday.

I'm guessing you can't toggle to the "local"/accountless option when the application is in this state?
![image](https://github.com/user-attachments/assets/927dcc37-e45e-4b0f-b322-233ccca07685)

**Comment by Zethson** [comment] 2024-10-20 19:02
Same in Germany now. I guess the servers are down again?

edit: just loaded now I'm confused.

**Comment by RJVB** [comment] 2024-10-20 19:06
Same here, a few minutes ago I heard the fans go wild and when I turned I was logged in again.

The server must be glitching, or maybe rather some intermediary node...

**Comment by therealgorgan** [comment] 2024-10-20 21:29
Happens intermittently for me as well

**Comment by Alphrag** [comment] 2024-10-20 21:40
> Is there a healthcheck page to verify if the server's really down? I'm also encountering the same issue, but only encountered it just now. It was working yesterday without issue.

Well you can have a look at the [website status](https://ferdium.github.io/ferdium-status/) powered by Upptime, which gives you an idea, but is not real time, the project only pings the sites every now and then to check if the api is running.

**Comment by RJVB** [comment] 2024-10-20 22:40
>Well you can have a look at the [website status](https://ferdium.github.io/ferdium-status/) powered by Upptime, which gives you an idea, but is not real time, the project only 

That seems to show the downtime we experienced here.

Would be nice to put that in a service ... but no, that wouldn't be of much use if you couldn't load it when it's indeed the server that's causing problems ^^

**Comment by ak2k** [comment] 2024-10-23 12:09
> There's an "accountless" option to move from a hosted server model to an local one. you can move to that so as to safeguarded against server-outages.

More info on how to backup up/transfer your configuration if you go with the "accountless" option: https://github.com/ferdium/ferdium-app/blob/develop/docs/INTERNAL_SERVER.md#exporting-backups

**Comment by RJVB** [comment] 2024-10-23 12:11
>Well you can have a look at the [website status](https://ferdium.github.io/ferdium-status/) powered by Upptime, which gives you an idea, but is not real time, the project only 

Yep:

```
Active Incidents
API (Server) is down
Opened at 10/23/2024, 1:47:36 PM with 1 posts
Incident #176 report →
Translator is down
Opened at 10/23/2024, 1:39:13 PM with 0 posts
Incident #175 report →
Debugger is down
Opened at 10/23/2024, 1:39:12 PM with 0 posts
Incident #174 report →
```

**Comment by jmiaje** [comment] 2024-10-23 12:27
This has become so much fraustrating nowadays. Almost regulary api server is being down for some reason and causing the same. 

I'm facing the same issue right now. 
Is there anyway i can host the api server myself to avoid this?

**Comment by mastercko** [comment] 2024-10-23 12:30
> This has become so much fraustrating nowadays. Almost regulary api server is being down for some reason and causing the same.
> 
> I'm facing the same issue right now. Is there anyway i can host the api server myself to avoid this?

Yeah, I think. If you check here, I think they have instructions for spinning up the server for self-hosting:
https://github.com/ferdium/ferdium-server

**Comment by KertLynx** [comment] 2024-12-06 04:06
Having the same issue with version 7.0.0 on Windows 10.

Version: 7.0.0
Server: Ferdium Server
Electron: 33.2.0
Chrome: 130.0.6723.118
Node.js: 20.18.0
Platform: Windows 10
Arch: x64
Build date: Sun Nov 10 2024 07:53:00 GMT+0530 (India Standard Time)
Git SHA: e6249427
Git branch: release

![image](https://github.com/user-attachments/assets/d3ed64cb-5e54-4da4-8950-89f8a988bae6)

**Comment by RJVB** [comment] 2024-12-06 19:46
On Thursday December 05 2024 20:06:36 vscodesyncsettings wrote:
>Having the same issue with version 7.0.0 on Windows 10.

It seems the server is having issues again today. 3rd time today for me too that I get that dreaded raspberry banner

**Comment by sashistillfrvr** [comment] 2024-12-14 20:50
![imagen](https://github.com/user-attachments/assets/9d9f062c-ff42-45cf-ba31-e2387518c308)
Down, again.

**Comment by sashistillfrvr** [comment] 2024-12-14 20:50
#1999 Looks the same as this issue

**Comment by SpecialAro** [comment] 2024-12-14 23:12
Closing as duplicate of #1926.

Please stop opening new issues without searching the issue box. Spamming this issue won't help solving it but rather make it difficult for maintainers to keep the issue board clean. It is starting to get a bit frustrating - I realize that this issue is important and impactful, I've also taken the time to explore it and I've even setup a logger that pings Ferdium API so I know exactly when this issue happens to try and figure out what might be causing it.

If you want to help, please look at the code base on ferdium/ferdium-server repo and look at the way we handle database transactions. We are probably doing something wrong there as logs say somethings on the lines: knex transactions error - probably a timeout or race conditions bloating the CPU/RAM on the server side and causing it to crash.

Thank you.

**Comment by RJVB** [comment] 2024-12-14 23:13
>Down, again.


Yep, today is not a good day, the services have been going up and down like a yoyo.

**Closed as not planned** 2024-12-14 23:12 UTC
Labels: duplicate :mirror:
