### ISSUE TITLE
Somethings is happening and Ferdium not stable to use.

### ISSUE THREAD

**Issue by leoheck** [ferdium/ferdium-app#1213] opened 2023-05-31 18:53 UTC
### Your issue

![image](https://github.com/ferdium/ferdium-app/assets/1277920/2c86be3c-5943-4dac-b9bc-e9197237a807)

If I reload it goes back to normal, and then after some seconds, it changed to the screen above.

```
Version: 6.3.0-nightly.14
Server: No Server
Electron: 25.0.0
Chrome: 114.0.5735.45
Node.js: 18.15.0
Platform: Linux 6.2
Arch: x64
Build date: Mon May 29 2023 21:00:13 GMT-0300 (Brasilia Standard Time)
Git SHA: 67a71a08
Git branch: nightly
```

Debug info, if it helps
```
{"host":{"platform":"linux","release":"6.2.0-20-generic","screens":[{"id":4693186499577156,"label":"DELL U2515H","bounds":{"x":0,"y":0,"width":2560,"height":1440},"workArea":{"x":0,"y":27,"width":2560,"height":1413},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{r:[0.6610, 0.3321], g:[0.3008, 0.6140], b:[0.1493, 0.3321], w:[0.3127, 0.3290]}, transfer:SRGB, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":2560,"height":1440},"displayFrequency":59,"workAreaSize":{"width":2560,"height":1413},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdium":{"version":"6.3.0-nightly.14","electron":"25.0.0","installedRecipes":[{"id":"googlecalendar","version":"2.3.2"},{"id":"hangoutschat","version":"1.6.0"},{"id":"reddit","version":"1.2.0"},{"id":"whatsapp","version":"3.4.10"},{}],"devRecipes":[],"services":[{"id":"7e65fa08-f3a1-4107-a710-519f0cf4b0d7","recipe":"whatsapp","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true,"isProgressbarEnabled":false},{"id":"09d83949-3020-47c0-a27a-bc0c26c2014e","recipe":"googlecalendar","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true,"isProgressbarEnabled":false},{"id":"d80ff737-e88f-4a64-b7ef-7307219928ce","recipe":"hangoutschat","isAttached":false,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"b6236564-73a8-488f-9a28-7eaed68d144c","recipe":"hangoutschat","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false},{"id":"8bb967f4-8b97-4e33-aa0b-c98cb24a90cb","recipe":"googlecalendar","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true,"isProgressbarEnabled":false},{"id":"457f4c1f-a0d8-4496-be4d-8b933301c62c","recipe":"hangoutschat","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false,"isProgressbarEnabled":false}],"messages":[{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"You are using Ferdium without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"You are using Ferdium without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"You are using Ferdium without a server"},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `children` supplied to `CSSTransition`, expected one of type [function].","\n    at CSSTransition (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-transition-group/cjs/CSSTransition.js:120:35)\n    at Appear (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/components/ui/effects/Appear.js:1:816)\n    at InfoBar (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/components/ui/InfoBar.js:1:1366)\n    at injectIntl(InfoBar)\n    at AppUpdateInfoBar (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/components/AppUpdateInfoBar.js:1:1417)\n    at div\n    at div\n    at div\n    at ErrorBoundary (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/components/util/ErrorBoundary/index.js:1:1243)\n    at injectIntl(ErrorBoundary)\n    at /tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:420:25\n    at AppLayout (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/components/layout/AppLayout.js:1:2936)\n    at /tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:420:25\n    at injectIntl(WithStyles(AppLayout))\n    at ThemeProvider (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)\n    at AppLayoutContainer (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/containers/layout/AppLayoutContainer.js:1:1494)\n    at /tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at RenderedRoute (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-router/dist/umd/react-router.development.js:540:7)\n    at Routes (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-router/dist/umd/react-router.development.js:1131:7)\n    at Router (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-router/dist/umd/react-router.development.js:1063:17)\n    at HistoryRouter (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-router-dom/dist/umd/react-router-dom.development.js:375:7)\n    at FerdiumRoutes (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/routes.js:1:2549)\n    at /tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at IntlProvider (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-intl/src/components/provider.js:88:47)\n    at I18N (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/I18n.js:1:1030)\n    at /tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at Provider (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:493:24)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `children` supplied to `CSSTransition`, expected one of type [function].","\n    at CSSTransition (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-transition-group/cjs/CSSTransition.js:120:35)\n    at TransitionGroup (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-transition-group/cjs/TransitionGroup.js:57:30)\n    at Appear (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/components/ui/effects/Appear.js:1:816)\n    at InfoBar (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/components/ui/InfoBar.js:1:1366)\n    at injectIntl(InfoBar)\n    at AppUpdateInfoBar (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/components/AppUpdateInfoBar.js:1:1417)\n    at div\n    at div\n    at div\n    at ErrorBoundary (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/components/util/ErrorBoundary/index.js:1:1243)\n    at injectIntl(ErrorBoundary)\n    at /tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:420:25\n    at AppLayout (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/components/layout/AppLayout.js:1:2936)\n    at /tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:420:25\n    at injectIntl(WithStyles(AppLayout))\n    at ThemeProvider (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)\n    at AppLayoutContainer (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/containers/layout/AppLayoutContainer.js:1:1494)\n    at /tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at RenderedRoute (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-router/dist/umd/react-router.development.js:540:7)\n    at Routes (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-router/dist/umd/react-router.development.js:1131:7)\n    at Router (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-router/dist/umd/react-router.development.js:1063:17)\n    at HistoryRouter (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-router-dom/dist/umd/react-router-dom.development.js:375:7)\n    at FerdiumRoutes (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/routes.js:1:2549)\n    at /tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at IntlProvider (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-intl/src/components/provider.js:88:47)\n    at I18N (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/I18n.js:1:1030)\n    at /tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at Provider (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:493:24)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `children` supplied to `Transition`, expected one of type [function].","\n    at Transition (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-transition-group/cjs/Transition.js:135:30)\n    at CSSTransition (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-transition-group/cjs/CSSTransition.js:120:35)\n    at div\n    at TransitionGroup (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-transition-group/cjs/TransitionGroup.js:57:30)\n    at Appear (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/components/ui/effects/Appear.js:1:816)\n    at InfoBar (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/components/ui/InfoBar.js:1:1366)\n    at injectIntl(InfoBar)\n    at AppUpdateInfoBar (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/components/AppUpdateInfoBar.js:1:1417)\n    at div\n    at div\n    at div\n    at ErrorBoundary (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/components/util/ErrorBoundary/index.js:1:1243)\n    at injectIntl(ErrorBoundary)\n    at /tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:420:25\n    at AppLayout (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/components/layout/AppLayout.js:1:2936)\n    at /tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:420:25\n    at injectIntl(WithStyles(AppLayout))\n    at ThemeProvider (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)\n    at AppLayoutContainer (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/containers/layout/AppLayoutContainer.js:1:1494)\n    at /tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at RenderedRoute (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-router/dist/umd/react-router.development.js:540:7)\n    at Routes (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-router/dist/umd/react-router.development.js:1131:7)\n    at Router (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-router/dist/umd/react-router.development.js:1063:17)\n    at HistoryRouter (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-router-dom/dist/umd/react-router-dom.development.js:375:7)\n    at FerdiumRoutes (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/routes.js:1:2549)\n    at /tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at IntlProvider (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-intl/src/components/provider.js:88:47)\n    at I18N (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/I18n.js:1:1030)\n    at /tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at Provider (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:493:24)"]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","info":["error",{"isTrusted":true}]},{"type":"error","info":["error","The above error occurred in the <Transition> component:\n\n    at Transition (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-transition-group/cjs/Transition.js:135:30)\n    at CSSTransition (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-transition-group/cjs/CSSTransition.js:120:35)\n    at div\n    at TransitionGroup (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-transition-group/cjs/TransitionGroup.js:57:30)\n    at Appear (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/components/ui/effects/Appear.js:1:816)\n    at InfoBar (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/components/ui/InfoBar.js:1:1366)\n    at injectIntl(InfoBar)\n    at AppUpdateInfoBar (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/components/AppUpdateInfoBar.js:1:1417)\n    at div\n    at div\n    at div\n    at ErrorBoundary (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/components/util/ErrorBoundary/index.js:1:1243)\n    at injectIntl(ErrorBoundary)\n    at /tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:420:25\n    at AppLayout (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/components/layout/AppLayout.js:1:2936)\n    at /tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:420:25\n    at injectIntl(WithStyles(AppLayout))\n    at ThemeProvider (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)\n    at AppLayoutContainer (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/containers/layout/AppLayoutContainer.js:1:1494)\n    at /tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at RenderedRoute (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-router/dist/umd/react-router.development.js:540:7)\n    at Routes (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-router/dist/umd/react-router.development.js:1131:7)\n    at Router (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-router/dist/umd/react-router.development.js:1063:17)\n    at HistoryRouter (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-router-dom/dist/umd/react-router-dom.development.js:375:7)\n    at FerdiumRoutes (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/routes.js:1:2549)\n    at /tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at IntlProvider (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/react-intl/src/components/provider.js:88:47)\n    at I18N (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/I18n.js:1:1030)\n    at /tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:524:34\n    at Provider (/tmp/.mount_FerdiuD0h7Si/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:493:24)\n\nReact will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary."]}],"workspaces":[],"windowSettings":{"width":1920,"height":1136,"x":425,"y":171,"displayBounds":{"x":0,"y":0,"width":2560,"height":1440},"isMaximized":false,"isFullScreen":false},"settings":{"autoLaunchOnStart":false,"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"reloadAfterResumeTime":10,"enableSystemTray":true,"startMinimized":false,"confirmOnQuit":false,"minimizeToSystemTray":false,"closeToSystemTray":false,"privateNotifications":false,"clipboardNotifications":true,"notifyTaskBarOnMessage":false,"showDisabledServices":true,"showServiceName":false,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"enableTranslator":false,"spellcheckerLanguage":"en-us","darkMode":true,"navigationBarManualActive":false,"splitMode":false,"splitColumns":3,"fallbackLocale":"en-US","beta":true,"isAppMuted":false,"enableGPUAcceleration":true,"enableGlobalHideShortcut":false,"server":"You are using Ferdium without a server","predefinedTodoServer":"https://todoist.com/app","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernateOnStartup":true,"hibernationStrategy":300,"wakeUpStrategy":300,"wakeUpHibernationStrategy":0,"wakeUpHibernationSplay":true,"inactivityLock":0,"automaticUpdates":true,"universalDarkMode":true,"userAgentPref":"","adaptableDarkMode":true,"accentColor":"#7266F0","progressbarAccentColor":"#7367F0","serviceRibbonWidth":68,"sidebarServicesLocation":0,"iconSize":20,"sentry":false,"navigationBarBehaviour":"custom","webRTCIPHandlingPolicy":"disable_non_proxied_udp","searchEngine":"duckDuckGo","translatorLanguage":"en","translatorEngine":"LibreTranslate","useHorizontalStyle":false,"hideCollapseButton":false,"isMenuCollapsed":true,"hideRecipesButton":false,"hideSplitModeButton":true,"useGrayscaleServices":false,"grayscaleServicesDim":50,"hideWorkspacesButton":false,"hideNotificationsButton":false,"hideSettingsButton":false,"alwaysShowWorkspaces":false,"liftSingleInstanceLock":false,"enableLongPressServiceHint":false,"isTodosFeatureEnabled":true,"customTodoServer":"","locale":"en-US","keepAllWorkspacesLoaded":false,"proxyFeatureEnabled":false,"onlyShowFavoritesInUnreadCount":false,"useVerticalStyle":false},"features":{},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}
```

**Comment by pcklink** [comment] 2023-05-31 19:15
Same here. Hasn't worked all day.

**Comment by sad270** [comment] 2023-05-31 22:36
I have the same issue with `6.3.0-nightly.14` I update to `6.3.0-nightly.15` and now it's working 😄 can you try to upgrade to the last nightly ?

**Comment by vraravam** [comment] 2023-06-01 00:31
nightly 13 and 14 had some changes that are already identified as the root cause. Since 15 was already released, we were not expecting any bugs logged against 13 or 14 per se. (Discussion happened in the discord server rooms). Closing

**Closed as completed by vraravam** 2023-06-01 00:31 UTC
