### ISSUE TITLE
Google classroom does not work within Ferdium because reffer to external browser !

### ISSUE THREAD

**Issue by Nokia808** [ferdium/ferdium-app#374] opened 2022-06-26 16:54 UTC
### Your issue

Hello.

I tried to open my account on Google classroom. But, the problem is that when I tried to log in to my account the log in link did not open within Ferdium but when I clicked it it led to open it in my Firefox !!

I tried to repeat login after I activated the option "Open URL within Ferdium" but same problem remain !!

**Comment by vraravam** [comment] 2022-06-26 22:06
Please specify which version of Ferdium you are using, which version of the Google Classroom service, what OS, etc.

The problem you describe is most likely due to Google changing their logic and not allowing the `user-agent` that your service is sending. Please search other issues (both open and closed ones) and see how to change the user agent for that service alone.

**Comment by Nokia808** [comment] 2022-06-27 13:31
I'm using Fedora Linux version 36 X64 bit OS.

I'm using Ferdium version 6.0.0 Beta 2.

I'm installing flatpak version of Ferdium from FlatHub.

**Comment by SpecialAro** [comment] 2022-06-27 14:25
This is related to https://github.com/ferdium/ferdium-app/issues/1002 probably

**Comment by marie-bnl** [comment] 2023-04-28 11:25
I’m pretty sure this is not a user-agent problem or anything, but just Google’s log-in link that has a `target="_blank"` attribute. Marking this as duplicate of #1064.

**Closed as not planned by marie-bnl** 2023-04-28 11:25 UTC
Labels: bug :beetle:, duplicate :mirror:, question :question:
