### ISSUE TITLE
Bug: Slack notifications in MacOS don't link to the correct Slack channel and message

### ISSUE THREAD

**Issue by florentin** [ferdium/ferdium-app#601] opened 2022-09-07 15:31 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.1.0

### What Operating System are you using?

macOS

### Operating System Version

12.5.1 (21G83)

### What arch are you using?

x64

### Expected Behavior

When the Slack service is added to Ferdium and a Slack notification is received, a notification banner shows up in the right upper corner. A click on the notification should take me to the channel/conversion/thread which caused the notification.

### Actual Behavior

A click on a Ferdium notification coming from the Slack service takes me to the last viewed channel/message in Slack.

### Steps to reproduce

Alternative
1. Add Slack service
2. Connect to a Slack server
3.  Send a direct message to yourself, something like "/remind me to test Ferdium in 10 seconds"
4. Switch to a different channel
5. After 10 seconds, click on the MacOS notification and check if it takes you to the Slackbot conversation (and not to the latest viewed conversation in Slack)

### Additional information

As far as I can tell, this issue was introduced in Ferdi v5.6.1
https://github.com/getferdi/ferdi/releases/tag/v5.6.1

Slack notifications in Ferdi 5.6.0 behaved correctly.

**Comment by SpecialAro** [comment] 2022-09-07 15:57
Closing as duplicate of https://github.com/ferdium/ferdium-app/issues/263

**Closed as not planned by SpecialAro** 2022-09-07 15:57 UTC
Labels: duplicate :mirror:
