### ISSUE TITLE
Bug: Warning when trying to mute chats on Whatsapp

### ISSUE THREAD

**Issue by ppvnf** [ferdium/ferdium-app#631] opened 2022-09-22 17:34 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.1

### What Operating System are you using?

Windows

### Operating System Version

10.0.19044.0

### What arch are you using?

x64

### Expected Behavior

Being able to disable notification (for groups and individual chats)
![Captura de tela 2022-09-22 142423](https://user-images.githubusercontent.com/73800734/191812264-6a234128-3d67-4ada-8fa7-618d9ef5971d.png)

### Actual Behavior

Being unable to disable notifications (it's possible, but kinda hard since this warning appears after a few seconds)
![Captura de tela 2022-09-22 142521](https://user-images.githubusercontent.com/73800734/191812792-50710223-dfec-47d9-a407-d16dfe4f823c.png)

### Steps to reproduce

1. Open Whatsapp inside Ferdium
2. Right click any conversation (on the left sidebar)
3. Click mute/silence notifications
4. A warning about dark mode will appear, making difficult to mute/silence notifications.

**Comment by SpecialAro** [comment] 2022-09-22 17:40
@ppvnf please, next time, search similar issues before raising one.

Closing as duplicate of https://github.com/ferdium/ferdium-app/issues/595

**Comment by SpecialAro** [comment] 2022-09-22 17:40
Also, this is fixed in the new stable version. Please update to v6.2.0.

**Closed as not planned by SpecialAro** 2022-09-22 17:40 UTC
Labels: duplicate :mirror:

**Comment by ppvnf** [comment] 2022-09-22 17:44
> Also, this is fixed in the new stable version. Please update to v6.2.0.

Thanks, I had searched only open issues!
