### ISSUE TITLE
Bug: Hyperlink clicks are not working

### ISSUE THREAD

**Issue by thamaraiselvam** [ferdium/ferdium-app#179] opened 2022-05-19 03:57 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.34

### What Operating System are you using?

macOS

### Operating System Version

macOS Monterey 12.1 (21C52)

### What arch are you using?

x64

### Expected Behavior

Whenever I click URL it should open a new tab on browser and redirect me to that specific url, for example.

I have got facebook.com link in the gmail and when I click that url it directs me to 

https://www.google.com/url?q=https://facebook.com and eventually google.com will redirect me to https://facebook.com

### Actual Behavior

There is a problem in parsing links and one forward slash is missing from the final url.

**Expected** 
https://www.google.com/url?q=https://facebook.com

**Actual**
https://www.google.com/url?q=https:/facebook.com

and it leads 
<img width="592" alt="Screenshot 2022-05-19 at 9 24 24 AM" src="https://user-images.githubusercontent.com/6559664/169200930-6037f88d-286e-41c6-9259-db9025aceb37.png">

### Steps to reproduce

1. Send an email with any link
2. Open same email and click that link

### Screenshots

<img width="615" alt="Screenshot 2022-05-19 at 9 24 07 AM" src="https://user-images.githubusercontent.com/6559664/169201205-fbd81cf0-1930-4fa8-88cb-dcbb15e6f849.png">
<img width="339" alt="Screenshot 2022-05-19 at 9 26 39 AM" src="https://user-images.githubusercontent.com/6559664/169201218-74d68ba8-793e-4819-8ccc-7752f2e9d18b.png">

**Comment by vraravam** [comment] 2022-05-20 02:52
Duplicate of #141 
This has already been fixed in a later nightly.

**Closed as completed by vraravam** 2022-05-20 02:52 UTC
Labels: bug :beetle:
