### ISSUE TITLE
Bug: Toolbar doesn't seem to be reading cache after login after first session cached

### ISSUE THREAD

**Issue by SlanDF** [ferdium/ferdium-app#426] opened 2022-07-05 11:19 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.89 `Ferdium-win-AutoSetup-6.0.0-nightly.89.exe`

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 Pro 19043

### What arch are you using?

x64

### Expected Behavior

Toolbar options are updated as I make changes on Ferdium. **FIRST SESSION ONLY**
This is really an issue that only happened ~~Once a fresh account was created~~ and there was no local user data at all!
**EDIT**: No local user data causes the issue

### Actual Behavior

File>Settings => **Disabled**
Services => No services
WorkSpaces > Add New Workspace => **Disabled**
WorkSpaces > Open workspace drawer => **Disabled**
Todos > Enable Todos => **Disabled**

This is fixed when you close the Ferdium process and open it again.

### Steps to reproduce

1. Delete you `%APPDATA%/Roaming/Ferdium`
2. Login/Create Account
3. Check Toolbar

### Debug link

https://pastebin.com/M1xmnh0p

### Screenshots

Starting Account Session with no local user data 🔽 

https://user-images.githubusercontent.com/13062045/177323825-cb1f63bb-5233-4a8c-bf57-e1b52d9ec485.mp4

**Comment by SlanDF** [comment] 2022-07-05 11:35
I've edited the **Additional Information** will keep you updated

**Comment by SpecialAro** [comment] 2022-07-05 11:37
Hello @Kanubiz , thank you for logging this issue.

Can you please try to Reload Ferdium `CTRL + SHIFT + R` ?

Also, can you please try to uninstall the current Ferdium instance and remove the folder `%APPDATA%/Roaming/Ferdium` and try again with the `.exe` installer version instead of the `.msi` one?

**Comment by cino** [comment] 2022-07-05 11:46
This could actually be fixed once we fix #364 and this is most likely the same issue as #358

**Comment by SpecialAro** [comment] 2022-07-05 11:56
> This could actually be fixed once we fix #364 and this is most likely the same issue as #358

Been talking on discord about this. Turns out it can be an issue related with the DNS Server of our ISP (me and @Kanubiz are based on the same location and also have the same ISP)... @dqos , which is our contact from Hybula, is informed about this 😄

**Comment by SlanDF** [comment] 2022-07-05 11:57
So I really think this is all related to the not having any local data yet and once you create that first data youre not telling the toolbar to update (if thats a function you can call). Just uninstalled, deleted roaming and installed `Ferdium-win-AutoSetup-6.0.0-nightly.89.exe` The video from the Additional information is fixed with this version

**Comment by SlanDF** [comment] 2022-07-05 11:58
> Been talking on discord about this. Turns out it can be an issue related with the DNS Server of our ISP (me and @Kanubiz are based on the same location and also have the same ISP)... @dqos , which is our contact from Hybula, is informed about this 😄

Thats related for us not being able to access ferdium.org on the browser not related to the issue! 🤣

**Comment by SlanDF** [comment] 2022-07-05 11:59
Im gonna update the issue again, including build etc

**Comment by SpecialAro** [comment] 2022-07-05 12:02
> > Been talking on discord about this. Turns out it can be an issue related with the DNS Server of our ISP (me and @Kanubiz are based on the same location and also have the same ISP)... @dqos , which is our contact from Hybula, is informed about this 😄
> 
> Thats related for us not being able to access ferdium.org on the browser not related to the issue! 🤣

Oh! that's right, sorry!

**Comment by SlanDF** [comment] 2022-07-05 13:46
I've reupdated the issue, removed unrelated information and made it more readable

**Comment by vraravam** [comment] 2022-07-05 13:52
As a temporary workaround, can we programmatically force a `Cmd+Shift+R` once the data from the server is downloaded (for first-time users)?

**Comment by SpecialAro** [comment] 2022-07-08 16:58
Is this a duplicate of https://github.com/ferdium/ferdium-app/issues/358 ?

**Comment by SlanDF** [comment] 2022-07-08 19:55
> Is this a duplicate of #358 ?

I've looked at #358 and yeah seems so

**Comment by vraravam** [comment] 2022-07-09 04:24
Closing as duplicate of #358

**Closed as completed by vraravam** 2022-07-09 04:24 UTC
Labels: bug :beetle:, duplicate :mirror:, question :question:
