### ISSUE TITLE
Bug: Three dots instead of tray icon

### ISSUE THREAD

**Issue by givanov95** [ferdium/ferdium-app#739] opened 2022-11-04 19:18 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.0

### What Operating System are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04.1 LTS, GNOME version 42.5

### What arch are you using?

x64

### Expected Behavior

Show icon with number of missed notification 

### Actual Behavior

Three dots icon in tray

### Steps to reproduce

Open Ferdium

### Screenshots

![Screenshot from 2022-11-04 18-53-37](https://user-images.githubusercontent.com/63155374/200057527-6c21d09b-ecee-46cf-b031-a21b447cb3df.png)

### Additional information

Version: 6.2.0
Server: Ferdium Server
Electron: 20.2.0
Chrome: 104.0.5112.124
Node.js: 16.15.0
Platform: Linux 5.15
Arch: x64
Build date: Thu Sep 22 2022 19:47:12 GMT+0300 (Eastern European Summer Time)
Git SHA: 84613b5b
Git branch: release

**Comment by vraravam** [comment] 2022-11-05 01:15
Duplicate of #719

**Closed as completed by vraravam** 2022-11-05 01:15 UTC
Labels: bug :beetle:
