### ISSUE TITLE
Office 365 user password not saving

### ISSUE THREAD

**Issue by iibrahimc** [ferdium/ferdium-app#906] opened 2023-01-27 09:37 UTC
### Your issue

Hello,
I enter my Office 365 account information and it opens... When I close and open Feridun again, my account information is lost... Can you help me..

**Comment by vraravam** [comment] 2023-01-27 09:46
Duplicate of #564 - please follow that thread to look at what workarounds are possible.

**Closed as completed by vraravam** 2023-01-27 09:46 UTC
