### ISSUE TITLE
Missing Viber IM service

### ISSUE THREAD

**Issue by ko5tas** [ferdium/ferdium-app#2010] opened 2024-12-31 12:08 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

Viber is missing from the IM services

### Proposed Solution

add Viber as one of the services

### Alternatives Considered

NA

**Comment by SpecialAro** [comment] 2024-12-31 12:47
Please search the issue board before opening new issues (as stated in the template when opening a new issue).

Closing as duplicate of #1319

**Closed as not planned** 2024-12-31 12:48 UTC
Labels: duplicate :mirror:
