### ISSUE TITLE
Portable version's update installs Ferdium regularly instead

### ISSUE THREAD

**Issue by mh166** [ferdium/ferdium-app#1088] opened 2023-03-30 08:35 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.4-portable

### What Operating System are you using?

Windows

### Operating System Version

21H2 (Build 19044.2604)

### What arch are you using?

x64

### Expected Behavior

- Ferdium provides me with a banner to inform me about an available update.
- After clicking _Restart & Install_, it should replace the portable binary with it's updated version.
- If for whatever reason it's not possible to update it inplace on it's own, it should provide me with the download link and instructions to replace the executable manually.

### Actual Behavior

- I click on _Restart & Install_
- Suddenly the **normal installer** begins to run and I end up with a regularly installed version of Ferdium. Despite my effort to have it portable.
  - Additional side effect: to the uninitiated, it may appear like all settings are lost and one has to start over. This is, of course, because the profile is loaded from the regular path, not the portable location.

### Steps to reproduce

1. Download `Ferdium-win-Portable-6.2.4-x64.exe` and set it up
2. Wait for the update banner to display
3. Click _Restart & Install_
4. Marvel at your newly installed, non-portable version 😅

### Additional information

While #1087 could sound similar when looking at the subject, that issue is about the version number being displayed incorrectly in the About box of the new executable. Not about the update process itself. So it might not be related.

**Comment by Alphrag** [comment] 2023-03-30 14:05
Hey @mh166 that is indeed not an intended behaviour. The auto-updater that we use does not seem to recognise the difference between the portable version and the fully installed one. It should indeed only put a banner saying that an update is available without downloading it, and redirecting to the appropriate url to download the new version. I will have a look at that this weekend!

**Comment by vraravam** [comment] 2023-05-28 05:12
@mh166 - though the code changes have been done and merged in, they will only be "active" ie the changed behavior will only show up after the 2nd nightly beyond today's commit

**Closed as completed** 2023-05-28 05:11 UTC
Labels: bug :beetle:, windows
