### ISSUE TITLE
Desktop Notifications Issue

### ISSUE THREAD

**Issue by alexmfv3** [ferdium/ferdium-app#1268] opened 2023-07-13 13:46 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.4.0

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 IoT Enterprise LTSC (21H2)

### What arch are you using?

x64

### Expected Behavior

When any person writtes me on services (like WhatsApp, Gmail or RoundCube), get a desktop notification and appear a badged in red with number of notifications.

### Actual Behavior

Since some months ago, this desktop notifications stop appear (and just can listen a notification sound).

### Steps to reproduce

1. Go to Gmail service
2. Send to gmail account logged on ferdium an email
3. Check if received notification and badged appear

### Debug link

https://debug.ferdium.org/39ed2a91-a195-42d9-8cdf-72c3ae8863db

**Comment by marie-bnl** [comment] 2023-07-18 14:32
Duplicate of https://github.com/ferdium/ferdium-app/issues/1105

**Closed as not planned by marie-bnl** 2023-07-18 14:32 UTC
Labels: bug :beetle:
