### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Se7Touch** [ferdium/ferdium-app#429] opened 2022-07-05 19:00 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.89

### What Operating System are you using?

Windows

### Operating System Version

Windows 21H2

### What arch are you using?

x64

### Expected Behavior

notification sound needs to be heard

### Actual Behavior

notifications sound silent

### Steps to reproduce

1. Give message on telegram
2. Notifications have not any sound

**Comment by vraravam** [comment] 2022-07-05 23:06
Please add an appropriate title when opening tickets.
Closing this since its a duplicate of #93

**Closed by vraravam** 2022-07-05 23:06 UTC
Labels: bug :beetle:
