### ISSUE TITLE
Service keyboard shortcut combo display "undefined" for the 11th service and more

### ISSUE THREAD

**Issue by sad270** [ferdium/ferdium-app#1214] opened 2023-05-31 23:01 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.3.0-nightly.15

### What Operating System are you using?

macOS

### Operating System Version

macOS Ventura Version 13.4 (22F66)

### What arch are you using?

x64

### Expected Behavior

Only display the service name for the tooltip for the services after 10

### Actual Behavior

It display service name + "undefined"
<img width="183" alt="Screenshot 2023-06-01 at 00 59 34" src="https://github.com/ferdium/ferdium-app/assets/5607440/eeee1a44-caed-482b-86f6-8a0adbb33ba3">

### Steps to reproduce

1. Create more than 10 services
2. On your sidebar, go on the 11th service to show the tooltip

### Screenshots

<img width="197" alt="Screenshot 2023-06-01 at 01 01 30" src="https://github.com/ferdium/ferdium-app/assets/5607440/02cd71ed-06f5-4adb-b8da-bd3f1b4eb0f5">

**Comment by vraravam** [comment] 2023-05-31 23:43
Duplicate of #1210 which was already fixed in #1211

**Comment by vraravam** [comment] 2023-05-31 23:43
Duplicate of #1210 which was already fixed in #1211

**Closed as completed** 2023-05-31 23:43 UTC
Labels: bug :beetle:
