### ISSUE TITLE
Latest build - 6.75 - Breaks 'discord service' sidebar behaviour

### ISSUE THREAD

**Issue by davidmoore-io** [ferdium/ferdium-app#1837] opened 2024-06-30 17:04 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.5

### What Operating System are you using?

macOS

### Operating System Version

Sonoma 14.4.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Ferdium version

6.7.4

### Expected Behavior

It would present like the web app, with side menu's etc collapsed on the right hand side.

### Actual Behavior

![Screenshot 2024-06-30 at 18 00 46](https://github.com/ferdium/ferdium-app/assets/1043347/d9bda50a-4d13-4c38-b6a1-2a45ef511555)
![Screenshot 2024-06-30 at 18 00 27](https://github.com/ferdium/ferdium-app/assets/1043347/71257c12-d545-41f8-9584-06d654090eb4)
![Screenshot 2024-06-30 at 17 55 53](https://github.com/ferdium/ferdium-app/assets/1043347/5d4d9237-95b2-4f29-a5bb-f50bf98a5b68)

It now fully extends the menu views to fill the screen. 

An side effect is that you now have to click the 'send arrow' to send - pressing enter no longer works when in a chat. Pressing enter does what 'shift + enter' used to do.

### Steps to reproduce

Load the discord service and navigate anywhere...

### Screenshots

![Screenshot 2024-06-30 at 18 00 46](https://github.com/ferdium/ferdium-app/assets/1043347/854c1c39-9e97-4f5d-bda4-adb73f1afaf9)
![Screenshot 2024-06-30 at 18 00 27](https://github.com/ferdium/ferdium-app/assets/1043347/24f3f0b4-4c7c-41f1-b092-ebb2510c0e9a)
![Screenshot 2024-06-30 at 17 55 53](https://github.com/ferdium/ferdium-app/assets/1043347/62734868-22bf-46b4-a98e-7483b6e306eb)

**Comment by mariellamarco** [comment] 2024-07-01 08:14
I downgraded to 6.7.4 while waiting for the fix.

**Comment by th3jesta** [comment] 2024-07-03 14:16
Same issue. Downgrade to 6.7.4 resolved it for now.

**Comment by damywise** [comment] 2024-07-14 11:34
Seems like this is a duplicate of this https://github.com/ferdium/ferdium-app/issues/1835, there's also a mention of a workaround there. I personally overlooked it because the title and screenshots of this issue provide more clarity.

**Comment by davidmoore-io** [comment] 2024-07-15 21:49
Ref the workaround here - [https://github.com/ferdium/ferdium-app/issues/1835#issuecomment-2198346786](https://github.com/ferdium/ferdium-app/issues/1835#issuecomment-2198346786)

.. or just use 6.7.4.

**Comment by SpecialAro** [comment] 2024-08-17 12:09
Duplicate of https://github.com/ferdium/ferdium-app/issues/1835

**Closed as not planned by SpecialAro** 2024-08-17 12:09 UTC
Labels: duplicate :mirror:
