### ISSUE TITLE
"Loading" OSD stays forever

### ISSUE THREAD

**Issue by J-Kappes** [ferdium/ferdium-app#1081] opened 2023-03-28 07:45 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.4 Flathub

### What Operating System are you using?

Other Linux

### Operating System Version

Fedora Linux 37 (Workstation Edition)

### What arch are you using?

x64

### Expected Behavior

After opening a service, it finishes loading after a while and the "Loading" OSD disappears, allowing me to interact with the service.

### Actual Behavior

Occasionally, the OSD will stay on forever and I can't use the service.
The only ways to restore functionality that I've found are restarting Ferdium and hibernating the service for a while.

### Steps to reproduce

Just keep trying to open services that aren't active yet.

**Comment by meiphoo7-Mae** [comment] 2023-04-06 04:30
Did you try reloading the service (Ctrl + R)? I use a custom service which suffers from this problem occasionally and reloading the service always solves the problem.

**Comment by jwmh** [comment] 2023-05-14 16:51
+1 this happens for me with Discord.
But if I go into edit service and disable the "PROGRESS BAR"
then it fixes it.

I suspect the problem is that some dynamic web apps can appear to the browser as "always still-loading" because they're active/dynamic.
... :-/

**Comment by vraravam** [comment] 2023-06-01 00:36
Duplicate of #590

**Closed as completed by vraravam** 2023-06-01 00:36 UTC
Labels: bug :beetle:

**Comment by RJVB** [comment] 2023-06-06 11:51
Disabling the progressbar didn't fix it for me, I just had it again (IG service). At most now I can fix the problem via the hibernation feature; before I had to disable and reenable the service.

What's the point of that OSD anyway? A working progressbar seems a lot more useful to me. Or "do something" with the service icon (traditional "throbber" style) whenever the page is being loaded, not just a reload of the service but also when you follow links.

**Comment by rmeissn** [comment] 2024-02-06 07:19
I'm still effected by this bug with ferdium 6.7.0 flatpak on Fedora 39. So it does not seem to be resolved.
It regularly happens to me with WhatsApp, but also with RocketChat occasionally.

**Comment by meiphoo7-Mae** [comment] 2024-02-07 02:12
It happens with any random service. Even with Github.
That's because it isn't resolved. Issue #590 of which this one is supposed to be a duplicate was closed by the OP for some unknown reason. Also what #1208 says about the progressbar doesn't work in every case.

**Comment by RJVB** [comment] 2024-02-07 12:11
Same here, still (see also my comment from June 6th).

I suspect that there are a few state variables that aren't (always) (re)set. I'm having a similar problem with the URL bar which sometimes remains empty (and when that happens, keyboard navigation shortcuts don't work and the userscript isn't executed).

**Comment by RiddheshB** [comment] 2024-05-06 10:44
> +1 this happens for me with Discord. But if I go into edit service and disable the "PROGRESS BAR" then it fixes it.
> 
> I suspect the problem is that some dynamic web apps can appear to the browser as "always still-loading" because they're active/dynamic. ... :-/

This is still an issue. Can someone please guide me on how to remove the progress bar like someone above mentioned (on mac)?

I can't see a disable progress bar option

**Comment by meiphoo7-Mae** [comment] 2024-06-01 05:40
A little late, but anyway...

Right-click on your service then the contextmenu opens.
Choose  "edit" then a new window opens and in the section "Appearance" there's the option you're searching for.
Currently I don't use the English language in Ferdium so the names mentioned above might be different.

**Comment by sochartgit** [comment] 2024-07-01 18:27
Bump. still the same problem. Progress bar switch does nothing, still getting the Loading message forever.

**Comment by BeyondMagic** [comment] 2024-10-12 06:46
Still having the same problem with any service, including customs. Should not have been closed...
