### ISSUE TITLE
Bug: Hamburger Menu Position doesn´t get saved after restart

### ISSUE THREAD

**Issue by Latschenharry** [ferdium/ferdium-app#365] opened 2022-06-25 12:29 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.77

### What Operating System are you using?

Windows

### Operating System Version

Windows 11 21H2

### What arch are you using?

x64

### Last Known Working Ferdium version

Never Worked

### Expected Behavior

If the hamburger menu in the sidebar is collapsed on closing Ferdium it should also be closed after being startet again.

### Actual Behavior

Hamburger menu is opened after every start.

### Steps to reproduce

1. Collapse the hamburger menu
2. restart Ferdium
3. hamburger menu is open again

### Screenshots

![image](https://user-images.githubusercontent.com/12736979/175773493-d025db13-5c56-4dd6-a5f3-0571a5cdc39e.png)

**Comment by SpecialAro** [comment] 2022-06-25 13:29
Thank you for raising this issue.

This is a "it's not a bug, it's a feature" kind of thing ahaha 🤣

I can try to take a look at this when I get the chance 👍 if someone has the time go ahead and raise a PR!

**Comment by SpecialAro** [comment] 2022-06-27 14:00
Closing this issue as it is working on the latest nightly.

**Closed as completed by SpecialAro** 2022-06-27 14:00 UTC
Labels: bug :beetle:
