### ISSUE TITLE
Feature: Slack: other person screen sharing can't open in bigger window

### ISSUE THREAD

**Issue by Shadester** [ferdium/ferdium-app#265] opened 2022-06-15 15:21 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.60

### What Operating System are you using?

macOS

### Operating System Version

12.4

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

When someone share their screen in Slack, I can see the window within ferdium, but I can't open that one bigger in a separate window, like how it is on the official Slack client.

Would be great if that could be done.

### Actual Behavior

Nothing happens if I click the expand button

### Steps to reproduce

1. Have someone share their screen to you in Slack
2. See the little window
3. Click to expand
4. Nothing happens

**Comment by SpecialAro** [comment] 2022-06-15 15:46
Hello @Shadester , thank you for raising this issue.

In fact, I think this issue is related with opening a new window rather than the mainWindow of Ferdium, which is something real hard to achieve in the shor-term given how the code is structured, right @vraravam ?

Therefore, I think this should be marked as a feature request and not a bug.

**Comment by Shadester** [comment] 2022-06-15 16:44
Sure, if it should be labeled feature request, feel free to add that label instead. Don't think I can do it.

This is the only thing that stops me from uninstalling Slack from my work computer.

**Comment by vraravam** [comment] 2022-06-15 22:14
> In fact, I think this issue is related with opening a new window rather than the mainWindow of Ferdium, which is something real hard to achieve in the shor-term given how the code is structured, right @vraravam ?

Yes - both of these are true

**Comment by AbubakrSamsodien** [comment] 2022-08-30 08:09
+1

**Comment by MathysBriers** [comment] 2022-08-30 08:11
+1

**Comment by fnagel** [comment] 2022-08-30 08:21
+1

**Comment by boguima** [comment] 2023-03-31 00:32
I run into the same problem. @vraravam  is there any solution even if alternative?

**Comment by mcmxcdev** [comment] 2023-10-01 14:13
Closing as duplicate of https://github.com/ferdium/ferdium-app/issues/788

**Closed as completed by mcmxcdev** 2023-10-01 14:13 UTC
Labels: enhancement :sparkles:
