### ISSUE TITLE
Bug: Default Outlook keeps logging out on company account

### ISSUE THREAD

**Issue by TeaDrinkingProgrammer** [ferdium/ferdium-app#564] opened 2022-08-20 13:50 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0

### What Operating System are you using?

Other Linux

### Operating System Version

Fedora 36, kernel version 5.18

### What arch are you using?

x64

### Expected Behavior

You need to only login once whereafter it stays logged in.

### Actual Behavior

Asks for your email adress every time whereafter it logs in automatically. Using the custom link "outlook.office.com/mail" it works like expected.

### Steps to reproduce

1. Make new outlook instance
2. log in with company/school account
3. select "remember password"
4. reload page
The page ends up on the home page of outlook.
5. Click on "sign in"
6. Enter email adress
Logs into outlook

### Additional information

This issue has to do with the difference between personal accounts and company accounts: personal accounts have to login via outlook.live.com, company accounts via outlook.office.com. If you try to login with a company account at outlook.live.com or vice versa, it asks you for your email account and redirects you to the correct page.
I didn´t know this and was confused when Ferdium didn´t work because the service is called Outlook Office 365 which suggests it is for company accounts. Now, both live and outlook are aliases for this service which is thus not correct.
I would suggest creating separate services to avoid confusion but I am new to the project so there may be better solutions.

**Comment by SpecialAro** [comment] 2022-08-20 13:54
Hello @TeaDrinkingProgrammer. I'm closing this issue as a duplicate of https://github.com/ferdium/ferdium-app/issues/995.

**Closed as not planned** 2022-08-20 13:54 UTC
Labels: bug :beetle:
