### ISSUE TITLE
Bug: Whatsapp notification badge does not reflect unread messages

### ISSUE THREAD

**Issue by icheered** [ferdium/ferdium-app#773] opened 2022-11-16 13:32 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.0

### What Operating System are you using?

Other Linux

### Operating System Version

Fedora 36

### What arch are you using?

x64

### Expected Behavior

Whatsapp service notification badge disappears if there are no unread messages.

### Actual Behavior

The Whatsapp notification badge shows a random number of unread messages. 

### Steps to reproduce

1. Add Whatsapp as a service
2. Log into whatsapp
3. The service badge shows a random number of notifications (maybe this happened after a reboot)

### Debug link

https://debug.ferdium.org/eb92219d-5bcf-4eef-909f-d2ee5e3ccd91

### Screenshots

![2022-11-16_14-30](https://user-images.githubusercontent.com/37150873/202193829-2b35e851-a404-4c64-8f00-aa3be3d435b4.png)

**Comment by icheered** [comment] 2022-11-16 13:33
Bug was initially encountered and mentioned in #671

**Comment by SpecialAro** [comment] 2022-11-16 13:35
Yet another duplicate for the same issue. This is starting to be frustrating...

Please search for "Whatsapp" or other search terms before writing and raising tickets, as it says in the box you just ticked when raising this issue. 

Closing as a duplicate of https://github.com/ferdium/ferdium-recipes/issues/230

**Closed as not planned** 2022-11-16 13:36 UTC
Labels: duplicate :mirror:

**Comment by icheered** [comment] 2022-11-16 13:40
@SpecialAro I'm very confused, if I search for "is:issue is:open WhatsApp " issue #230 does NOT show up: https://github.com/ferdium/ferdium-app/issues?q=is%3Aissue+is%3Aopen+WhatsApp+

**Comment by vraravam** [comment] 2022-11-16 14:06
@icheered - you also need to look at the closed tickets - not just the open ones. That's pretty standard for any project. maybe something was fixed, but not yet released.

Also, I have pinned one of the closed tickets for the term Whatsapp - so, please also look at the top part of the page, and not just the filtered results.
<img width="1297" alt="Screenshot 2022-11-16 at 7 37 51 PM" src="https://user-images.githubusercontent.com/69629/202202261-bfd04eab-fbdf-4c10-b693-41eac087d9d2.png">

**Comment by SpecialAro** [comment] 2022-11-16 14:07
@icheered in fact you can't find it because it is opened in the ferdium-recipes repository (where it should be).

Regardless of that, a similar issue is currently pinned on top of the issue tracker.
![image](https://user-images.githubusercontent.com/37463445/202201824-ea3a5de0-6cda-493a-b5aa-e68ac935b6af.png)
