### ISSUE TITLE
Since today in the morning I get “Could not load services and user information”

### ISSUE THREAD

**Issue by katastrophe92** [ferdium/ferdium-app#1999] opened 2024-12-14 20:14 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

7.0.0

### What Operating System are you using?

Windows

### Operating System Version

Windows 11 Pro 26100.2605

### What arch are you using?

x64

### Last Known Working Ferdium version

7.0.0

### Expected Behavior

All recipes start

### Actual Behavior

No recipes are showed and below is a red bar showing the error message: Could not load services and user information

### Steps to reproduce

1. Open Ferdium
2. Wait until recipes are loading
3. Use Ferdium and be happy it exists.

### Debug link

https://debug.ferdium.org/362b65d2-3e6a-461d-ac7e-1da691fea406

### Screenshots

![image](https://github.com/user-attachments/assets/63630d3b-9320-4c47-b410-a304a65c5f7c)

### Additional information

Cleared cache, multiple Ferdium&Windows restarts did not helped.

**Comment by DemonAlone** [comment] 2024-12-14 21:40
The same problem  on Windows and Linux. Look like the server is down.

**Comment by jnvillar** [comment] 2024-12-14 22:14
same

**Comment by victorlunam** [comment] 2024-12-14 22:38
the same problem on macos

**Comment by Erudition** [comment] 2024-12-14 22:54
Same issue here. Logs:

```
~> flatpak run org.ferdium.Ferdium                                  12/14/2024 04:42:38 PM
F: Can't get document portal: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
LaunchProcess: failed to execvp:
xdg-settings
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
[40:1214/164304.926141:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[40:1214/164307.003683:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[MobX] Since strict-mode is enabled, changing (observed) observable values without using an action is not allowed. Tried to modify: Settings@13.store
[2:1214/164307.650208:ERROR:nss_util.cc(227)] Error initializing NSS with a persistent database (sql:/home/adroit/.pki/nssdb): NSS error code: -8126
[40:1214/164309.154368:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
Checking for update
Update for version 7.0.0 is not available (latest version: 7.0.0, downgrade is disallowed).
```

> Look like the server is down.

Ferdium depends on a live server to launch?

**Comment by mmlo** [comment] 2024-12-14 23:10
![image](https://github.com/user-attachments/assets/28822a68-45f8-4ad9-8927-e9addbd9b3b3)
Same issue here

**Comment by SpecialAro** [comment] 2024-12-14 23:13
Closing as duplicate of #1926.

Please stop opening new issues without searching the issue box. Spamming this issue won't help solving it but rather make it difficult for maintainers to keep the issue board clean. It is starting to get a bit frustrating - I realize that this issue is important and impactful, I've also taken the time to explore it and I've even setup a logger that pings Ferdium API so I know exactly when this issue happens to try and figure out what might be causing it.

If you want to help, please look at the code base on ferdium/ferdium-server repo and look at the way we handle database transactions. We are probably doing something wrong there as logs say somethings on the lines: knex transactions error - probably a timeout or race conditions bloating the CPU/RAM on the server side and causing it to crash.

Thank you.

**Closed as not planned by SpecialAro** 2024-12-14 23:13 UTC
Labels: duplicate :mirror:

**Comment by Erudition** [comment] 2024-12-14 23:28
Perhaps the more pressing issue, and the reason duplicate issues are created, is that the software doesn't at least  say "The server is down", or even just "failed to connect to Ferdium server".

The way it acts instead is the same as if my profile was corrupted, which is scary.
