### ISSUE TITLE
Bug: Whatsapp Notification count issue after Introduction of Community feature 

### ISSUE THREAD

**Issue by build3r** [ferdium/ferdium-app#769] opened 2022-11-15 08:36 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.0

### What Operating System are you using?

macOS

### Operating System Version

macOS Monterey

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Ferdium version

n/a

### Expected Behavior

Proper notification count as seen on whatsapp chat wondow

### Actual Behavior

The notification count is not proper

### Steps to reproduce

1. Have a whatsapp app which has community feature enabled
2. Be a part of any community with unread messages
3. Link to whatsapp web
4. Check notification count

### Screenshots

![image](https://user-images.githubusercontent.com/6481548/201870129-2922adfa-938b-4b18-88a7-e0506fd20393.png)

**Comment by Latschenharry** [comment] 2022-11-15 08:58
Duplicate of https://github.com/ferdium/ferdium-recipes/issues/230

**Closed as completed** 2022-11-15 09:02 UTC
Labels: bug :beetle:
