### ISSUE TITLE
Bug: wrong/enormous notification count for Whatsapp

### ISSUE THREAD

**Issue by hmalaud** [ferdium/ferdium-app#767] opened 2022-11-14 15:31 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.1-nightly.44

### What Operating System are you using?

macOS

### Operating System Version

Monterrey 12.6.1

### What arch are you using?

x64

### Expected Behavior

Whatsapp service should show correct amount of unread notifications.

### Actual Behavior

For the last 2 days, Whatsapp service has started to show an enormous number for notifications (more than 100).

### Steps to reproduce

Started by itself without any modification on user end

- Tried disabling/enabling service ❌
- Tried deleting/re-adding service ❌
- Tried deleting cache ❌
- Tried reinstalling stable 6.2 RC ❌
- Tried upgrading from stable 6.2 RC to nightly 6.2.1 ❌

### Screenshots

<img width="59" alt="image" src="https://user-images.githubusercontent.com/1000119/201699966-48de39bf-6ad3-4942-b5ed-e9708994e11c.png">

**Comment by eitchtee** [comment] 2022-11-14 15:38
Same behavior on 6.2.0
Started happening today.

**Comment by cino** [comment] 2022-11-14 15:44
Duplicate of https://github.com/ferdium/ferdium-recipes/issues/230 with PR in process https://github.com/ferdium/ferdium-recipes/pull/235

**Closed as not planned by cino** 2022-11-14 15:44 UTC
Labels: duplicate :mirror:

**Comment by hmalaud** [comment] 2022-11-14 15:46
Sorry for the duplicate, I searched for "notification" not "message" ;)
