### ISSUE TITLE
Service Request : Mastodon instance Statuzer

### ISSUE THREAD

**Issue by DarkXero-dev** [ferdium/ferdium-app#1881] opened 2024-08-25 14:45 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

I can't find **statuzer** under services.

### Proposed Solution

Adding **statuzer** to supported services

### Alternatives Considered

Custom Website.

**Comment by SpecialAro** [comment] 2024-08-26 23:06
Hello @DarkXero-dev 👋 

Can you please follow the template for service/recipe requests that we have instead of a bug report? When creating a new issue you should be able to change the template.

Nevertheless, is just to make sure, is statuzer a web app?

Is this the app url: https://statuzer.com ?

**Comment by DarkXero-dev** [comment] 2024-08-27 07:26
@SpecialAro Yes that's the URL if you can add it. I will see about correct template.

**Comment by Alphrag** [comment] 2024-10-12 19:42
Duplicate of #1883.

**Closed as not planned by Alphrag** 2024-10-12 19:42 UTC
Labels: enhancement :sparkles:
