### ISSUE TITLE
Whatsapp is not showing notfiication on Windows or Mac

### ISSUE THREAD

**Issue by RahKapoor** [ferdium/ferdium-app#1234] opened 2023-06-07 16:03 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.4.0-nightly.2

### What Operating System are you using?

Windows

### Operating System Version

Windows 11 Pro - Windows Feature Experience Pack 1000.22641.1000.0

### What arch are you using?

x64

### Last Known Working Ferdium version

6.0.0

### Expected Behavior

When you get a message on Whatsapp it should show the Whatsapp popup, but it doesn't, not on Mac or Windows

It only shows the Whatsapp notification banner on Whatsapp reactions, not on actual messages.

### Actual Behavior

Someone sends you a message. You get a sound notification but no banner notification on Windows or Mac

I have tried on 6.3.0 and on my Macbook which is on an older version, it also stopped working. 6.1.0

### Steps to reproduce

1. Message yourself to the Whatsapp on your Ferdium logged in
2. Hear the sound but no banner will show
3. Thats it
![26c0b7202b95e3a61e56be0bb23fedc5](https://github.com/ferdium/ferdium-app/assets/42355716/495cea62-872e-4323-8b07-68336537a2e1)

### Debug link

https://debug.ferdium.org/74323123-60e7-4d3f-a90c-14d1100dcfc2

**Comment by vraravam** [comment] 2023-06-08 00:06
Please do not create duplicates!!!!!!
Closing as a duplicate of #1182

**Closed as completed by vraravam** 2023-06-08 00:06 UTC
Labels: bug :beetle:

**Comment by RahKapoor** [comment] 2023-06-15 20:52
Ok jeez, no need to shout im just a lion
