### ISSUE TITLE
Bug: Translation fails (Ferdium Translator) or indefinitely hangs (Google engine)

### ISSUE THREAD

**Issue by LeonidRosin** [ferdium/ferdium-app#839] opened 2022-12-15 07:01 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.3-nightly.7

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 Pro, ver. 20H2, OS Build 19042.2130

### What arch are you using?

x64

### Last Known Working Ferdium version

n/a, my first attempt at using Ferdium Translator.

### Expected Behavior

select text -> Right-click -> "translate to English <or any lang>" -> translation is returned.

### Actual Behavior

1. If the translation service is LibreTranslate:
- returned red box with "FERDIUM ERROR: An error occured. Please select less text to translate or try again latter"
2. If the translation service is Google:
- returned message "Loading..." and nothing else happens.

3. The behavior is independent of the language pair.

### Steps to reproduce

1. Set Translator Engine to Google
2. Reload
3. Select text
4. Right click on selected text and 
5. Click on "translate to ..."
6. Got "Loading..." and nothing else happens.

7. Set Translator Engine to Ferdium Translator (Powered by LibreTranslator)
8. Reload
9. Select text
10. Right click on selected text and 
11. Click on "translate to ..."
12. Got red box w. "FERDIUM ERROR: An error occured. Please select less text to translate or try again latter".

### Screenshots

![Screenshot_4](https://user-images.githubusercontent.com/17572756/207793636-d8d37ead-5b9c-46ca-bcf1-e21246250707.png)

**Comment by SpecialAro** [comment] 2022-12-19 12:15
Hello @LeonidRosin,

I'm not able to reproduce this issue locally in DEV Mode. Nevertheless, in production, there is this issue with only Google Translator (LibreTranslator works fine) - which is throwing the following TypeError in the service console:
```
Uncaught (in promise) Error: Error invoking remote method 'translate': TypeError: requestFunction is not a function
    at o.invoke (VM126 renderer_init:57:526)
    at async generateTranslationItems (VM190 C:\Users\SpecialAro\AppData\Local\Programs\ferdium\resources\app.asar\webview\contextMenuBuilder.js:35:4773)
 ```
 
 --
 
 @LeonidRosin would you be able to provide the text you're trying to translate (as I've only tried with Portuguese/English/Spanish/French) - all Latin languages so far ? Thank you!

**Comment by LeonidRosin** [comment] 2022-12-19 12:31
Hello @SpecialAro, 
Behavior is independent of language, target language and text. For example see attachments.
(I have also added settings.)
Also, the interface language is not influenced. I switched to English - the result is the same.
![Screenshot_10](https://user-images.githubusercontent.com/17572756/208425966-d11de6f0-179e-4d30-8910-55bc77506198.png)
---
![Screenshot_11](https://user-images.githubusercontent.com/17572756/208425957-837bd72e-f72a-405d-bf54-ba493c635a1b.png)
---
![Screenshot_12](https://user-images.githubusercontent.com/17572756/208425970-f7434a87-9ece-49f3-b35f-d58d352b474d.png)

**Comment by SpecialAro** [comment] 2023-01-23 11:43
![image](https://user-images.githubusercontent.com/37463445/214031067-a6f23395-e404-4c6f-821f-99353d881fe6.png)
![image](https://user-images.githubusercontent.com/37463445/214031118-f6c9ab4a-7ba3-4fd1-8cef-55b38d2de416.png)
![image](https://user-images.githubusercontent.com/37463445/214031175-b79ce6d7-7909-4bc3-bb59-cc06efec46fe.png)

Well, for me it's working fine.

Can you provide me with the developer console log (View > Toggle Developer Console) and developer service log (View > Toggle Service Console) right after you get the error?

**Comment by LeonidRosin** [comment] 2023-01-23 12:32
It's ok?
![Screenshot_15](https://user-images.githubusercontent.com/17572756/214040395-9da66ef9-fef6-4e67-b3f6-0ad4a5276673.png)
![Screenshot_14](https://user-images.githubusercontent.com/17572756/214040413-9e526aad-fabe-4765-9a0f-0ec6a74b4594.png)

**Comment by SpecialAro** [comment] 2023-01-24 14:28
> It's ok? ![Screenshot_15](https://user-images.githubusercontent.com/17572756/214040395-9da66ef9-fef6-4e67-b3f6-0ad4a5276673.png) ![Screenshot_14](https://user-images.githubusercontent.com/17572756/214040413-9e526aad-fabe-4765-9a0f-0ec6a74b4594.png)

Would you be able to disable the warnings and just show the errors? 
![image](https://user-images.githubusercontent.com/37463445/214320986-e2d743a5-2070-479c-8816-0bd92ce98289.png)

**Comment by LeonidRosin** [comment] 2023-01-24 15:18
@SpecialAro  I wanted to do this, but the translation suddenly worked! 6.2.4-nnightly.11
![Screenshot_17](https://user-images.githubusercontent.com/17572756/214333029-b77fafe7-f5f6-46eb-a1d8-7d1fc5e7edab.png)

**Comment by SpecialAro** [comment] 2023-01-24 17:22
Ok, awesome!!

I'm closing this ticket then. In the meantime, if you get the same problem again, comment here and I'll be happy to reopen it ok?

Thank you!

**Closed as completed** 2023-01-24 17:22 UTC
Labels: bug :beetle:

**Comment by LeonidRosin** [comment] 2023-02-02 06:31
@SpecialAro 
**FYI.**
Hi, 
Ferdium Translator works but does not translate from Hebrew. This is of course a different issue and I found a similar bug and commented there. https://github.com/ferdium/ferdium-app/issues/583

**Comment by gogosese** [comment] 2023-09-19 03:48
I use an app to chat with friends and can't use Google to translate the conversation. Still looking for the reason.
