### ISSUE TITLE
Double unread message notification number on gmail icon

### ISSUE THREAD

**Issue by satnapar** [ferdium/ferdium-app#1532] opened 2024-01-16 08:08 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.0

### What Operating System are you using?

macOS

### Operating System Version

MacOs 10.15.7

### What arch are you using?

x64

### Expected Behavior

The gmail icon must show the correct unread emails

### Actual Behavior

The Gmail icon counting the unread messages, shows double unread emails. For example with one unread email, it show the number 2

### Steps to reproduce

Open ferdium
Add Gmail service
have some unread emails
it shows double the unread email number on gmail icon

### Screenshots

![Screenshot 2024-01-16 at 10 06 09 AM](https://github.com/ferdium/ferdium-app/assets/31922251/9f2b2ec5-0f7c-4f7b-a546-5f975bef59fb)

**Comment by SpecialAro** [comment] 2024-01-16 08:23
Please search the issue tracker before submitting new issues. This issue was fixed yesterday and the codebase is going to be available for pre-release users.

Closing as duplicate of https://github.com/ferdium/ferdium-app/issues/1496

**Closed as not planned** 2024-01-16 08:23 UTC
Labels: bug :beetle:
