### ISSUE TITLE
Ability to Add Chrome Extensions

### ISSUE THREAD

**Issue by bert003** [ferdium/ferdium-app#1485] opened 2023-12-13 13:02 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

There are chrome extensions which are really useful when browsing online but at the moment there seems to be no way to add them to Ferdium.

### Proposed Solution

Being able to add these extensions in Ferdium would be a great asset. Is this feature in the pipeline by any chance please?

### Alternatives Considered

Nothing in particular.

**Comment by mcmxcdev** [comment] 2023-12-17 04:35
Duplicate of https://github.com/ferdium/ferdium-app/issues/135

**Closed as completed by mcmxcdev** 2023-12-17 04:35 UTC
Labels: enhancement :sparkles:
