### ISSUE TITLE
Bug: Whatsapp notification count shows large number

### ISSUE THREAD

**Issue by felixmosh** [ferdium/ferdium-app#762] opened 2022-11-13 15:12 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

Version: 6.2.0

### What Operating System are you using?

macOS

### Operating System Version

MacOs Catalina

### What arch are you using?

x64

### Expected Behavior

In the past week looks like Whatsapp shows wrong notification count,

### Actual Behavior

It should show the real count

### Steps to reproduce

1. Add whatsapp service,
2. See that the notification count shows large number

### Screenshots

![image](https://user-images.githubusercontent.com/9304194/201528915-2aa8b197-e2f9-4c79-830a-8b4b39170ed4.png)

### Additional information

I've tried to remove & add the Whatsapp service, without any luck

**Comment by cino** [comment] 2022-11-13 15:13
Duplicate of https://github.com/ferdium/ferdium-recipes/issues/230 with PR in process https://github.com/ferdium/ferdium-recipes/pull/235

**Closed as not planned by cino** 2022-11-13 15:13 UTC
Labels: duplicate :mirror:
