### ISSUE TITLE
Bug: Whatsapp Update and Preferences

### ISSUE THREAD

**Issue by akougblenou** [ferdium/ferdium-app#535] opened 2022-08-03 08:31 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

 6.0.0

### What Operating System are you using?

macOS

### Operating System Version

macOS Monterey12.14

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Whatsapp opens and has the same preferences as I have on my mobile, specifically the them which should mimic the theme that the machine has.
Also in case of update of whatsapp the update is carried out and I have no notification for an update again.

### Actual Behavior

The theme preference is not applied and whatsapp has a white theme.

After update I am asked again for updating whatsapp.

### Steps to reproduce

1. setup your mobile with dark mode
2. Have the preference on your whatsapp mobile as "system preference"
3. go to computer
4. setup your computer with dark mode
5. open ferdium
6. access whatsapp
7. witness the whatsapp in light mode

**Comment by SpecialAro** [comment] 2022-08-03 08:59
Hello @akougblenou , thank you for logging this issue.

This is a duplicate of https://github.com/ferdium/ferdium-app/issues/490 on the part of the theming. Please look at that first.

**Comment by SpecialAro** [comment] 2022-08-03 17:00
Since this issue was manly about the theming, I'm closing it as duplicate of #490.

**Closed as not planned by SpecialAro** 2022-08-03 17:00 UTC
Labels: bug :beetle:, duplicate :mirror:
