### ISSUE TITLE
HUD thingy remains up and blocks service

### ISSUE THREAD

**Issue by RJVB** [ferdium/ferdium-app#1208] opened 2023-05-31 11:36 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.7

### What Operating System are you using?

Other Linux

### Operating System Version

4.14.23-ck1-mainline-core2-rjvb

### What arch are you using?

x64

### Expected Behavior

While loading a service (e.g. after hibernation), Ferdium shows a HUD thingy:

![image](https://github.com/ferdium/ferdium-app/assets/1756884/7ca40618-d023-4758-9e6c-9aa3011b4116)

This is supposed to go away once the site has been fully loaded.

### Actual Behavior

Periodically it doesn't (as in the screenshot above). And when that happens, the only fix is to disable and re-enable the service. A simple reload or even hibernation won't work.

### Steps to reproduce

No particular steps; this just happens from time to time, and not just with custom services as in the screenshot. I do think I see it more often in more complex sites; I cannot recall having had the problem with the couple of discussion forum sites I also use via Ferdium.

### Debug link

https://debug.ferdium.org/03e46e7a-701f-4f22-89da-d660d813428e

### Screenshots

![image](https://github.com/ferdium/ferdium-app/assets/1756884/7ca40618-d023-4758-9e6c-9aa3011b4116)

### Additional information

Maybe the easiest workaround is an option to disable the thingy, or simply disable it when the progressbar is enabled. They're redundant anyway.

**Comment by vraravam** [comment] 2023-06-01 00:33
The progressbar has been known to cause problems. We recommend that you turn it off for general use.

**Comment by vraravam** [comment] 2023-06-01 00:34
Duplicate of #1081

**Closed as completed by vraravam** 2023-06-01 00:34 UTC
Labels: bug :beetle:
