### ISSUE TITLE
Got logged out & services removed when account server was not reachable

### ISSUE THREAD

**Issue by M-arcus** [ferdium/ferdium-app#2005] opened 2024-12-18 16:50 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

7.0.0

### What Operating System are you using?

Ubuntu

### Operating System Version

Linux Mint 22

### What arch are you using?

x64

### Last Known Working Ferdium version

7.0.0

### Expected Behavior

When account server is not reachable, I get a warning and am able to continue working with my installed services.

### Actual Behavior

All services are deleted, all settings set to default

![image](https://github.com/user-attachments/assets/13b391e2-0fda-4a1f-a137-653585365182)

### Steps to reproduce

1. Loose connection to fermium authentication server

**Comment by thenotec** [comment] 2024-12-18 16:55
It seems https://api.ferdium.org/user/login not response.
It may have been hacked!

**Comment by joshuabalbert** [comment] 2024-12-18 17:02
It really should be able to use a locally cached version of everything and not crash when the server goes down.

**Comment by sdbingham** [comment] 2024-12-18 17:24
Same issue for me as well.

I can successfully ping api.ferdium.org but the actual site times out or gives a 500 internal server error. 

Looks like a server/database issue.

**Comment by mitchellhanks** [comment] 2024-12-18 17:50
+1

**Comment by Soetens** [comment] 2024-12-18 17:54
This happens a little to often.
Why is it required to make a server connection to use the app, this is not something you want to get it stable and independent.

**Comment by sdbingham** [comment] 2024-12-18 17:57
> This happens a little to often. Why is it required to make a server connection to use the app, this is not something you want to get it stable and independent.

Agreed. Time to host my own server or find something else.

**Comment by M-arcus** [comment] 2024-12-18 18:03
The best case for handling an offline Ferdium API should just be a warning that the server is not available. Removing local services is too much, just a warning text is perfectly fine IMO

**Comment by M-arcus** [comment] 2024-12-18 18:07
Server seems to be available again.

**Comment by Soetens** [comment] 2024-12-18 18:29
> The best case for handling an offline Ferdium API should just be a warning that the server is not available. Removing local services is too much, just a warning text is perfectly fine IMO


I'm wondering why is an API even needed when running Ferdium.
It's not like there is a DRM that needs validation if you are allowed to run ferdium.

**Comment by SpecialAro** [comment] 2024-12-18 18:59
Closing as duplicate of https://github.com/ferdium/ferdium-app/issues/1926.

@M-arcus your services are not removed. You simply can't see them when the server is down.

And, as I stated on another issue:
"Please stop opening new issues without searching the issue box. Spamming this issue won't help solving it but rather make it difficult for maintainers to keep the issue board clean. It is starting to get a bit frustrating - I realize that this issue is important and impactful, I've also taken the time to explore it and I've even setup a logger that pings Ferdium API so I know exactly when this issue happens to try and figure out what might be causing it.

If you want to help, please look at the code base on ferdium/ferdium-server repo and look at the way we handle database transactions. We are probably doing something wrong there as logs say somethings on the lines: knex transactions error - probably a timeout or race conditions bloating the CPU/RAM on the server side and causing it to crash.

Thank you."

**Closed as not planned by SpecialAro** 2024-12-18 18:59 UTC
Labels: bug :beetle:

**Comment by M-arcus** [comment] 2024-12-18 19:03
> Closing as duplicate of #1926.
> 
> @M-arcus your services are not removed. You simply can't see them when the server is down.
> 
> And, as I stated on another issue: "Please stop opening new issues without searching the issue box. Spamming this issue won't help solving it but rather make it difficult for maintainers to keep the issue board clean. It is starting to get a bit frustrating - I realize that this issue is important and impactful, I've also taken the time to explore it and I've even setup a logger that pings Ferdium API so I know exactly when this issue happens to try and figure out what might be causing it.

@SpecialAro 

This issue was about the removal of the services when the ferdium-server is down. Not about the downtime itself. 

Should I reopen an issue with a feature request for keeping local cached data when the ferdium-server is down?

**Comment by SpecialAro** [comment] 2024-12-18 20:34
@M-arcus as I stated previously, whenever the server is down your services aren't removed. When the server comes back up, you can restar Ferdium and you can see your services there.

If, for some reason, your services disappeared in the process (and you didn't attempt to logout) then it is, in fact a bug.

**Comment by Soetens** [comment] 2024-12-18 23:05
> @M-arcus as I stated previously, whenever the server is down your services aren't removed. When the server comes back up, you can restar Ferdium and you can see your services there.
> 
> If, for some reason, your services disappeared in the process (and you didn't attempt to logout) then it is, in fact a bug.

I also noticed when the API is down the running ferdium stops working.
