### ISSUE TITLE
Bug: Ferdium Icon Not Showing in Menu Tray

### ISSUE THREAD

**Issue by jshand2015** [ferdium/ferdium-app#874] opened 2023-01-11 21:57 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.3

### What Operating System are you using?

Other Linux

### Operating System Version

Opensuse Tumbleweed

### What arch are you using?

x64

### Last Known Working Ferdium version

unknown

### Expected Behavior

when ferdium start successfully, the icon of ferdium should be visible.  as it is now, the icon is not visible

in the picture X marks where ferdium icon should be visible

### Actual Behavior

starts up without problems, except the icon on the tray.  so hard to find it

### Steps to reproduce

Start ferdium

### Screenshots

![ferdium-running-no-icon-visible](https://user-images.githubusercontent.com/10791292/211926445-f83da215-8f16-4883-94f2-4290d411fb28.png)

**Comment by jshand2015** [comment] 2023-01-11 21:58
i forgot to mention.  i installed ferdium with snap

**Comment by vraravam** [comment] 2023-01-11 23:41
Duplicate of #719

**Closed as completed by vraravam** 2023-01-11 23:41 UTC
Labels: bug :beetle:
