### ISSUE TITLE
Bug: WhatsApp not connecting to internet

### ISSUE THREAD

**Issue by gaylie** [ferdium/ferdium-app#831] opened 2022-12-11 18:35 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.3-nightly.3

### What Operating System are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

WhatsApp being able to connect to internet.

### Actual Behavior

WhatsApp isn't connecting to the internet. Gives me an error message saying I should check my internet connection. Anything else requiring internet, both on Ferdium and in general, is working just fine.

### Steps to reproduce

1. Start Ferdium
2. Set up a WhatsApp service
3. Try to start WhatsApp

### Debug link

https://debug.ferdium.org/841c61ce-77c6-4caf-878f-45f2ab4bb3f1

### Screenshots

![image](https://user-images.githubusercontent.com/42840021/206922147-8b1e61d5-43cd-4cb0-aa3a-91cb6398b613.png)

**Comment by vraravam** [comment] 2022-12-26 02:30
I have seen this sometimes when my internet connection is slow. Its either your ISP/router where the issue is (or) that your computer has too many processes that are trying to use the same bandwidth to connect to the internet. Either way, I dont think this is a Ferdium issue. Closing.

**Closed as completed by vraravam** 2022-12-26 02:30 UTC
Labels: bug :beetle:

**Comment by gaylie** [comment] 2022-12-26 02:35
@vraravam  Is there any way I can check if this is the case? Because I have the same issue when I have nothing open but ferdium, and opening whatsapp web in my browser connects just fine. This issue only occurs in Ferdium and it has been happening every day, every time without fail for several weeks now.

**Comment by vraravam** [comment] 2022-12-26 04:28
Do you have a network usage dashboard app on your machine? If so, I would recommend to see what that says while Ferdium is the only app running and trying to connect to Whatsapp. For macos, I use stats.app for this purpose.
