### ISSUE TITLE
Ferdium-win-Portable-6.2.6-x64 does not run on Windows 7

### ISSUE THREAD

**Issue by dkhokhlov** [ferdium/ferdium-app#1101] opened 2023-04-08 06:43 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

Ferdium-win-Portable-6.2.6-x64

### What Operating System are you using?

Windows

### Operating System Version

Windows 7

### What arch are you using?

x64

### Last Known Working Ferdium version

Ferdium-win-Portable-6.2.6-x64

### Expected Behavior

installs and runs 

### Actual Behavior

crashes during install and portable run

### Steps to reproduce

1. run installer

**Comment by Alphrag** [comment] 2023-04-08 11:59
Duplicate of #1075

**Closed as not planned by Alphrag** 2023-04-08 11:59 UTC
Labels: bug :beetle:, duplicate :mirror:
