### ISSUE TITLE
Messenger Dark Mode not properly inverting colors

### ISSUE THREAD

**Issue by harryheres** [ferdium/ferdium-app#1418] opened 2023-10-25 10:38 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

v6.5.2

### What Operating System are you using?

Other Linux

### Operating System Version

Arch Linux 6.5.8-arch-1-1

### What arch are you using?

x64

### Expected Behavior

Messenger dark mode will invert also the message bubble background.

### Actual Behavior

Message bubbles on Dark mode stay with white background and gray text, which makes it fairly unreadable.

### Steps to reproduce

1. Go to Messenger service
2. Toggle dark mode

### Screenshots

![image](https://github.com/ferdium/ferdium-app/assets/74781187/02bbe048-8c71-478a-aaeb-b4ffc523382e)

### Additional information

Proposed solution:

Add to darkmode.css for messenger following line in the **root** node: 

`--chat-incoming-message-bubble-background-color: rgba(0, 0, 0, 0.5)`

**Comment by SpecialAro** [comment] 2023-10-25 10:39
Duplicate of https://github.com/ferdium/ferdium-app/issues/1416

Please search the issue board before filing new issues.

**Comment by harryheres** [comment] 2023-10-25 10:39
Oh, sorry, I was searching but did not quite find. My bad!

**Closed as not planned by SpecialAro** 2023-10-25 10:39 UTC
Labels: duplicate :mirror:
