### ISSUE TITLE
Bug:  Loading keeps on flashing when doing anything in any service

### ISSUE THREAD

**Issue by HamzaTGP** [ferdium/ferdium-app#287] opened 2022-06-17 10:05 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0.nightly.65-1

### What Operating System are you using?

Other Linux

### Operating System Version

Arch Linux (linux-zen 5.18.3)

### What arch are you using?

x64

### Last Known Working Ferdium version

6.0.0-nightly.60-1

### Expected Behavior

The "loading" text should only appear when a service is being opened

### Actual Behavior

The "loading" text flickers in places like:
The WhatsApp home page
Switching between WhatsApp chats
Switching between Discord groups/chats
Loading emails in gmail

and more

### Steps to reproduce

1. Open any WhatsApp instance
2. Going to be there infront of you, flickering on the homepage

Or for something like Gmail
1. Open any Gmail instance
2. Open any email

### Debug link

https://debug.ferdium.org/7c5d9b3c-bc5a-43be-9907-d10358220caf

### Screenshots

![image](https://user-images.githubusercontent.com/42169828/174276852-13ad8610-e22b-4337-9aa4-ca0ac1cdc55e.png)

### Additional information

Issue also started happening on Windows

**Comment by enkaa** [comment] 2022-06-17 10:33
I go the same issue, on macOS 6.0.0-nightly.63.
Problem does not exist on Telegram with me.

Debug log: 
https://debug.ferdium.org/7ab65455-916e-46f0-a619-a0404b399887

Screen recording:
https://user-images.githubusercontent.com/4510371/174280925-466de34c-9137-4d45-a08e-3c45b7ac200e.mov

.

**Comment by mydarkstar** [comment] 2022-06-17 12:24
Duplicate of #157

**Comment by HamzaTGP** [comment] 2022-06-17 12:28
Doesn't seem to be a duplicate, mine occurs no matter how many services I have. Also, the loading only flickers in some areas.

**Comment by pepper3k** [comment] 2022-06-17 12:31
I can confirm the same behavior on my end, only whatsapp exhibits this behavior mostly. I think there needs to be a way to separately identify loading of the root html document rather than individual resources.

**Comment by vraravam** [comment] 2022-06-17 12:57
I have a PR open (#285) - waiting for someone to approve

**Closed as completed** 2022-06-17 16:07 UTC
Labels: bug :beetle:

**Comment by vraravam** [comment] 2022-06-18 03:06
This has been released in nightly-66 - please try it out.

**Comment by HamzaTGP** [comment] 2022-06-18 08:18
> This has been released in nightly-66 - please try it out.

Yup, the new loader bar is way way way less distracting and annoying. Thank you so much!

**Comment by MagicLegend** [comment] 2022-06-19 11:11
I actually find the loader bar very distracting in Slack, since it gets shown every time I do anything :) Is there an option to disable it somewhere? (Per-service perhaps?)

**Comment by MagicLegend** [comment] 2022-06-19 11:27
For me in Whatsapp the loading bar does some crazy flickering as well:

![ferdium-whatsapp-loading](https://user-images.githubusercontent.com/3169104/174478554-f797b1bc-4279-4f06-88f9-258d7fadb9ec.gif)

**Comment by TJonCooper** [comment] 2022-06-19 13:18
@vraravam  I'm experiencing the same issue as @MagicLegend - only in WhatsApp. Running:

Version: 6.0.0-nightly.66
Electron: 19.0.4
Platform: Linux 5.15 (Ubuntu 22.04, X11)
Arch: x64

It has been going for the past few nightlies.

**Comment by vraravam** [comment] 2022-06-19 13:38
I implemented this earlier today: https://github.com/ferdium/ferdium-app/pull/301 - should be in the next nightly.

**Comment by HamzaTGP** [comment] 2022-06-19 19:41
> I implemented this earlier today: #301 - should be in the next nightly.

Gigachad.
