### ISSUE TITLE
Bug: Causes resize cursor to not show up for apps in front

### ISSUE THREAD

**Issue by probablykasper** [ferdium/ferdium-app#662] opened 2022-10-09 19:37 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.0

### What Operating System are you using?

macOS

### Operating System Version

macOS Catalina 10.15.7

### What arch are you using?

x64

### Expected Behavior

When dragging the cursor to a window edge, the resize cursor should show up

### Actual Behavior

https://user-images.githubusercontent.com/11315492/194778978-7dafcbf8-ecc4-49ac-ada2-163893b0886d.mp4

### Steps to reproduce

1. Put an app in front of Ferdium
2. Drag your cursor from Ferdium to the other app's window

### Additional information

I would've thought it's an Electron bug, but it's not happening with my Electron app

**Comment by SpecialAro** [comment] 2022-10-09 20:27
Hello!

I'm not entirely sure this is a Ferdium issue at all... Also, I'm trying to see what's wrong in the video, but everything seems to be working as intended. Could you please explain it better or send a video of the issue as how it should work?

Nevertheless, please edit your issue description if this is a Ferdium issue and not a Ferdi issue, given that you're reporting bugs on Ferdium and not Ferdi, thank you 😁

**Comment by probablykasper** [comment] 2022-10-09 20:54
Updated it with a more zoomed in recording. You can see that when dragging from Ferdium, the cursor doesn't update

Updated the description, my bad

**Comment by SpecialAro** [comment] 2022-10-13 08:50
> Updated it with a more zoomed in recording. You can see that when dragging from Ferdium, the cursor doesn't update

Thank you @probablykasper 😄 

Tested on my Windows 11 and on my macOS Monterey (12.6) and couldn't reproduce this issue. Maybe that issue is specific to macOS Catalina?

https://user-images.githubusercontent.com/37463445/195550367-9f533e75-6555-427e-bbc4-729c22a365f4.mov

**Comment by probablykasper** [comment] 2022-10-13 16:10
Might be specific to Catalina yeah, I can't reproduce it either in a Monterey VM

**Comment by cino** [comment] 2022-11-11 15:02
Going to close this issue as this is not something that happens on a recent version of MacOS and Catalina isn't even supported by Apple anymore. (https://endoflife.date/macos)

**Closed as not planned by cino** 2022-11-11 15:02 UTC
Labels: bug :beetle:
