### ISSUE TITLE
Bug: Icon on top showing twice after sleep mode

### ISSUE THREAD

**Issue by Zoldiru** [ferdium/ferdium-app#869] opened 2023-01-08 16:58 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.3

### What Operating System are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04.1

### What arch are you using?

x64

### Expected Behavior

After sleep mode and logging back to your account, the icon on top is showing once and is working

### Actual Behavior

After going to sleep mode, the icon in the top taskbar is showing twice, and the second one is not doing anything when I click on it.

### Steps to reproduce

1. Launch Ferdium
2. Go to sleep mode
3. Turn back on your computer
4. After logging back, the icon is now showing twice

### Screenshots

![image](https://user-images.githubusercontent.com/6117394/211209047-dad42f90-c13a-4fb9-b224-82f909d5e2e5.png)

**Comment by xalt7x** [comment] 2023-02-05 09:42
Duplicate of #57 
It's actually [gnome-shell-extension-appindicator bug](https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/348). You can install [updated extension](https://extensions.gnome.org/extension/615/appindicator-support/) until Ubuntu team backport changes to Ubuntu 22.04. Please close this issue.

**Comment by vraravam** [comment] 2023-02-05 13:12
thanks for finding the duplicate @xalt7x 
Closing

**Closed as completed by vraravam** 2023-02-05 13:12 UTC
Labels: bug :beetle:
