### ISSUE TITLE
Bug: Ferdium Tools Pane Not Resizable

### ISSUE THREAD

**Issue by dmytri** [ferdium/ferdium-app#830] opened 2022-12-11 14:24 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.2

### What Operating System are you using?

Other Linux

### Operating System Version

using Ferdium Flatpak on Fedora (IoT) with i3 wm.

### What arch are you using?

x64

### Expected Behavior

When I hover on the line between the application pane and the ferdium tools pane, the resize cursor appears, expected behaviour is for dragging to resize the panes

### Actual Behavior

dragging does not resize the panes

### Steps to reproduce

- open Ferdium tools
- hover on the line between application pane and tools pane until resize cursor appears
- drag to resize

**Comment by vraravam** [comment] 2022-12-26 02:38
Unable to reproduce with the latest 6.2.3 version. Closing
![ferdium-830](https://user-images.githubusercontent.com/69629/209492459-8a1caf3e-567e-447b-89e0-616d69dd3570.gif)

**Closed as completed by vraravam** 2022-12-26 02:38 UTC
Labels: bug :beetle:
