### ISSUE TITLE
Gmail Badge Count showing double the amount of new emails I have 

### ISSUE THREAD

**Issue by scottjohnson20** [ferdium/ferdium-app#1550] opened 2024-01-31 15:02 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.0

### What Operating System are you using?

Windows

### Operating System Version

Windows 11 

### What arch are you using?

x64

### Last Known Working Ferdium version

I'm not sure, sorry.

### Expected Behavior

When I have 3 new unread emails, a badge showing the number 3 should appear on top right corner of the service's icon in Ferdium.

### Actual Behavior

When I have 3 new unread emails, a badge showing the number 6 appears on top right corner of the service's icon in Ferdium.

### Steps to reproduce

1. Add your Gmail account to the Ferdium
2. Wait for multiple emails to come in
3. See what the badge number says.

### Screenshots

![Untitled-1](https://github.com/ferdium/ferdium-app/assets/49926530/6b40539b-07e8-430f-88f4-61eecb7a0ec6)

**Comment by SpecialAro** [comment] 2024-01-31 15:10
Please search the issue tracker before submitting new issues. This issue was already fixed and the codebase is already available for pre-release users.

Closing as duplicate of #1496

**Closed as not planned** 2024-01-31 15:10 UTC
Labels: bug :beetle:
