### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by harikrishnan993** [ferdium/ferdium-app#270] opened 2022-06-15 17:50 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.60

### What Operating System are you using?

Ubuntu

### Operating System Version

21.04

### What arch are you using?

x64

### Expected Behavior

When I add a service it should show the service and should be clickable

### Actual Behavior

the service will show a "Loading **Service Name** " wheel and nothing inside is clickable. The service itself will load its login page, and for something with a QR code scanned login (whatsapp) if I scan then login will work but the loading mask will not disappear and I am unable to select the chats

### Steps to reproduce

Add multiple service
click through each and see if all of them have no loading mask

### Screenshots

![image](https://user-images.githubusercontent.com/60136369/173892314-4030c858-cc63-42bb-b881-4ad9ebd527f4.png)
![image](https://user-images.githubusercontent.com/60136369/173892417-d7616ee3-9345-47eb-8d83-2eb7fdebf45f.png)

**Comment by vraravam** [comment] 2022-06-15 22:16
Duplicate of #157

**Closed as completed by vraravam** 2022-06-15 22:16 UTC
Labels: bug :beetle:
