### ISSUE TITLE
quick Switch window (Ctrl + s) doen't get focus on opening after the first switch

### ISSUE THREAD

**Issue by namzicos** [ferdium/ferdium-app#1787] opened 2024-05-24 07:57 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.4

### What Operating System are you using?

Windows

### Operating System Version

Windows 11 Professionnel - 22H2

### What arch are you using?

x64

### Expected Behavior

after the first switch when on re-opening quick switch window get focus  and can navigate directly with keyboard

### Actual Behavior

after the switch when re-opening quick switch window doesn't have the focus et i can't navigate with keyboard directly

### Steps to reproduce

1 opening (ctrl + s) quick switch window
2 select a recipe
3 re-open quick switch window (ctrl-s)

**Comment by SpecialAro** [comment] 2024-05-24 08:26
Duplicate of https://github.com/ferdium/ferdium-app/issues/341

Please search the issue box before opening issues.

**Closed as not planned by SpecialAro** 2024-05-24 08:26 UTC
Labels: bug :beetle:

**Comment by namzicos** [comment] 2024-05-27 11:32
my bad i didn't find it ... and this issue have 1 years old....

**Comment by SpecialAro** [comment] 2024-05-30 08:43
> my bad i didn't find it ... 

No problem


> and this issue have 1 years old....

As always, and bearing in mind this is a FOSS, we welcome new contributions to help fix bugs and add new features 😁
