### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by arielsantarosa** [ferdium/ferdium-app#1402] opened 2023-10-18 09:33 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.5.2

### What Operating System are you using?

Windows

### Operating System Version

Windows 11 23h2

### What arch are you using?

x64

### Expected Behavior

CPU usage mirroring software operation

### Actual Behavior

High CPU usage without software operation
Closing Ferdium APP doesn't work, since it keeps running in background using 25-50% CPU

### Steps to reproduce

Using Ferdium for some hours

### Debug link

https://debug.ferdium.org/88306459-6fb3-41e1-bab2-f459c949c545

**Comment by SpecialAro** [comment] 2023-10-18 09:40
Closing as possible duplicate of https://github.com/ferdium/ferdium-app/issues/219

**Closed as completed by SpecialAro** 2023-10-18 09:40 UTC
Labels: duplicate :mirror:
