### ISSUE TITLE
Feature: Support adblock for services

### ISSUE THREAD

**Issue by andremmfaria** [ferdium/ferdium-app#539] opened 2022-08-04 18:19 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Some services show ads that can be blocked to avoid clutter and/or excess bandwidth usage.

### Proposed Solution

Support an ad-blocker for the app. There are some options out there.
A solution I found, thanks to the guys at the [Unofficial YouTube Music Desktop app](https://th-ch.github.io/youtube-music/), is incorporating @ghostery's [adblocker library for electron](https://github.com/ghostery/adblocker).
Another one comes from this [medium article](https://medium.com/@Jense5_/how-to-setup-electron-ad-blocker-c5d6ec8fb1d3) that uses @Jense5's [electron-ad-blocker](https://github.com/Jense5/electron-ad-blocker)

### Alternatives Considered

Living with ads provides no alternatives :(

**Comment by vraravam** [comment] 2022-08-04 18:25
Duplicate of #135

**Closed as completed by vraravam** 2022-08-04 18:25 UTC
Labels: enhancement :sparkles:

**Comment by onjour** [comment] 2025-08-12 09:07
@andremmfaria @vraravam 
we are in 2025 and I just discovered Ferdium, the only thing missing in my setup is ad blocking and it looks like nothing has been implemented yet. Is there a way to block ads with the resources you provided? I'm no dev and I must say that I'm a bit confused by all this information, thanks for your understanding!
