### ISSUE TITLE
Messenger refreshes when sending messages

### ISSUE THREAD

**Issue by XantorXD** [ferdium/ferdium-app#1362] opened 2023-09-15 09:04 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.4.1

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 22H2 19045.2673

### What arch are you using?

x64

### Last Known Working Ferdium version

6.4.1

### Expected Behavior

No blinking window when sending messages

### Actual Behavior

The window blinks, as if it refreshes every time a message is received and sent.

### Steps to reproduce

1. write message
2. send message
3. see error
4. deliver message
5. see error

**Comment by gsfranc** [comment] 2023-09-15 17:06
i have it too it started today

**Comment by Ve7off** [comment] 2023-09-15 18:17
I have the same issue. Tested with new browser, netz settings, flushed dns. Basically evrything what i tought about

**Comment by sethmayer** [comment] 2023-09-15 20:24
same issue here. 
Messenger recipe version 1.8.0

Version: 6.4.1
Server: No Server
Electron: 25.5.0
Chrome: 114.0.5735.289
Node.js: 18.15.0
Platform: Windows 11
Arch: x64
Build date: Tue Aug 15 2023 06:42:59 GMT-0700 (Pacific Daylight Time)
Git SHA: 09ee519f
Git branch: release

**Comment by gsfranc** [comment] 2023-09-16 12:18
it fixed today no more refreshing yay

**Comment by SpecialAro** [comment] 2023-09-16 22:20
@XantorXD are you still experiencing this issue? It looks like it was something on the Messenger side as we haven't change nothing so far on the code.

**Comment by Ve7off** [comment] 2023-09-18 08:21
It's gone for me too. It was Meta problem for sure. I had Problem in Insta also, the messages ware disappearing than coming back in messed up order🤣

**Comment by XantorXD** [comment] 2023-09-18 14:59
> @XantorXD are you still experiencing this issue? It looks like it was something on the Messenger side as we haven't change nothing so far on the code.

For now its ok ;)

**Comment by SpecialAro** [comment] 2023-09-27 12:12
Closing this issue as this was not caused by Ferdium but by Meta.

**Closed as not planned by SpecialAro** 2023-09-27 12:12 UTC
Labels: bug :beetle:
