### ISSUE TITLE
Bug: Loading modal stuck after wake up a service [Linux]

### ISSUE THREAD

**Issue by Jvlsc** [ferdium/ferdium-app#181] opened 2022-05-19 14:10 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.41

### What Operating System are you using?

Ubuntu

### Operating System Version

22.04

### What arch are you using?

x64

### Last Known Working Ferdium version

None

### Expected Behavior

Loading Service Modal close after a service is loaded.

### Actual Behavior

Modal stuck with the service loaded in background. The only way to fix is force reload the app (Ctrl+Shift+R).

### Steps to reproduce

1. Have a service hibernated.
2. Click on it to wake up.

### Debug link

```
instrument.ts:129

Warning: Failed prop type: Invalid prop `actions.service` of type `Object` supplied to `AppLayoutContainer`, expected instance of `_class`.
    at AppLayoutContainer (/snap/ferdium/25/resources/app.asar/containers/layout/AppLayoutContainer.js:1:1742)
    at /snap/ferdium/25/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34
    at <anonymous> (/snap/ferdium/25/resources/app.asar/node_modules/create-react-class/factory.js:899:37)
    at <anonymous> (/snap/ferdium/25/resources/app.asar/node_modules/create-react-class/factory.js:899:37)
    at Routes (/snap/ferdium/25/resources/app.asar/routes.js:1:2444)
    at /snap/ferdium/25/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34
    at IntlProvider (/snap/ferdium/25/resources/app.asar/node_modules/react-intl/src/components/provider.js:83:47)
    at I18N (/snap/ferdium/25/resources/app.asar/I18n.js:1:470)
    at /snap/ferdium/25/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34
    at Provider (/snap/ferdium/25/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:482:24)
```

```
instrument.ts:129 

Warning: Failed prop type: Invalid prop `actions.settings` of type `Object` supplied to `Sidebar`, expected instance of `_class`.
    at Sidebar (/snap/ferdium/25/resources/app.asar/components/layout/Sidebar.js:1:1942)
    at /snap/ferdium/25/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34
    at injectIntl(inject-with-stores-actions(Sidebar))
    at div
    at div
    at ErrorBoundary (/snap/ferdium/25/resources/app.asar/components/util/ErrorBoundary/index.js:1:971)
    at /snap/ferdium/25/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25
    at injectIntl(WithStyles(ErrorBoundary))
    at AppLayout (/snap/ferdium/25/resources/app.asar/components/layout/AppLayout.js:1:2631)
    at /snap/ferdium/25/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25
    at injectIntl(WithStyles(AppLayout))
    at ThemeProvider (/snap/ferdium/25/resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)
    at AppLayoutContainer (/snap/ferdium/25/resources/app.asar/containers/layout/AppLayoutContainer.js:1:1742)
    at /snap/ferdium/25/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34
    at <anonymous> (/snap/ferdium/25/resources/app.asar/node_modules/create-react-class/factory.js:899:37)
    at <anonymous> (/snap/ferdium/25/resources/app.asar/node_modules/create-react-class/factory.js:899:37)
    at Routes (/snap/ferdium/25/resources/app.asar/routes.js:1:2444)
    at /snap/ferdium/25/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34
    at IntlProvider (/snap/ferdium/25/resources/app.asar/node_modules/react-intl/src/components/provider.js:83:47)
    at I18N (/snap/ferdium/25/resources/app.asar/I18n.js:1:470)
    at /snap/ferdium/25/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34
    at Provider (/snap/ferdium/25/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:482:24)
```

```
instrument.ts:129 

Warning: Failed prop type: Invalid prop `actions.service` of type `Object` supplied to `QuickSwitchModal`, expected instance of `_class`.
    at QuickSwitchModal (/snap/ferdium/25/resources/app.asar/features/quickSwitch/Component.js:1:1976)
    at /snap/ferdium/25/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34
    at /snap/ferdium/25/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25
    at injectIntl(WithStyles(inject-with-stores-actions(QuickSwitchModal)))
    at div
    at div
    at div
    at ErrorBoundary (/snap/ferdium/25/resources/app.asar/components/util/ErrorBoundary/index.js:1:971)
    at /snap/ferdium/25/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25
    at injectIntl(WithStyles(ErrorBoundary))
    at AppLayout (/snap/ferdium/25/resources/app.asar/components/layout/AppLayout.js:1:2631)
    at /snap/ferdium/25/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25
    at injectIntl(WithStyles(AppLayout))
    at ThemeProvider (/snap/ferdium/25/resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)
    at AppLayoutContainer (/snap/ferdium/25/resources/app.asar/containers/layout/AppLayoutContainer.js:1:1742)
    at /snap/ferdium/25/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34
    at <anonymous> (/snap/ferdium/25/resources/app.asar/node_modules/create-react-class/factory.js:899:37)
    at <anonymous> (/snap/ferdium/25/resources/app.asar/node_modules/create-react-class/factory.js:899:37)
    at Routes (/snap/ferdium/25/resources/app.asar/routes.js:1:2444)
    at /snap/ferdium/25/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34
    at IntlProvider (/snap/ferdium/25/resources/app.asar/node_modules/react-intl/src/components/provider.js:83:47)
    at I18N (/snap/ferdium/25/resources/app.asar/I18n.js:1:470)
    at /snap/ferdium/25/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34
    at Provider (/snap/ferdium/25/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:482:24)
```

```
instrument.ts:129 

Warning: Failed prop type: Invalid prop `actions.service` of type `Object` supplied to `PublishDebugLogModal`, expected instance of `_class`.
    at PublishDebugLogModal (/snap/ferdium/25/resources/app.asar/features/publishDebugInfo/Component.js:1:2558)
    at /snap/ferdium/25/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34
    at /snap/ferdium/25/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25
    at injectIntl(WithStyles(inject-with-stores-actions(PublishDebugLogModal)))
    at div
    at div
    at div
    at ErrorBoundary (/snap/ferdium/25/resources/app.asar/components/util/ErrorBoundary/index.js:1:971)
    at /snap/ferdium/25/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25
    at injectIntl(WithStyles(ErrorBoundary))
    at AppLayout (/snap/ferdium/25/resources/app.asar/components/layout/AppLayout.js:1:2631)
    at /snap/ferdium/25/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25
    at injectIntl(WithStyles(AppLayout))
    at ThemeProvider (/snap/ferdium/25/resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)
    at AppLayoutContainer (/snap/ferdium/25/resources/app.asar/containers/layout/AppLayoutContainer.js:1:1742)
    at /snap/ferdium/25/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34
    at <anonymous> (/snap/ferdium/25/resources/app.asar/node_modules/create-react-class/factory.js:899:37)
    at <anonymous> (/snap/ferdium/25/resources/app.asar/node_modules/create-react-class/factory.js:899:37)
    at Routes (/snap/ferdium/25/resources/app.asar/routes.js:1:2444)
    at /snap/ferdium/25/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34
    at IntlProvider (/snap/ferdium/25/resources/app.asar/node_modules/react-intl/src/components/provider.js:83:47)
    at I18N (/snap/ferdium/25/resources/app.asar/I18n.js:1:470)
    at /snap/ferdium/25/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34
    at Provider (/snap/ferdium/25/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:482:24)
```

```
instrument.ts:129 

Warning: You cannot PUSH the same path using hash history
```

```

helpers.ts:111 

Uncaught Error: The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at WebViewElement.getWebContentsId (node:electron/js2c/renderer_init:105:695)
    at _class.initializeWebViewEvents (/snap/ferdium/25/res…s/Service.js:1:8906)
    at _class._setWebviewReference (/snap/ferdium/25/res…cesStore.js:1:14243)
    at executeAction (/snap/ferdium/25/res…/lib/mobx.js:927:19)
    at _class._setWebviewReference (/snap/ferdium/25/res…/lib/mobx.js:914:16)
    at /snap/ferdium/25/res…ib/actions.js:1:556
    at Array.forEach (<anonymous>)
    at Function.i.notify (/snap/ferdium/25/res…ib/actions.js:1:544)
    at i (/snap/ferdium/25/res…ib/actions.js:1:398)
    at Object.onDidAttach (/snap/ferdium/25/res…ceWebview.js:1:3082)
    at WebViewElement.<anonymous> (/snap/ferdium/25/res…WebView.js:21413:46)
    at WebViewElement.sentryWrapped (helpers.ts:87:17)
    at WebViewImpl.dispatchEvent (node:electron/js2c/r…derer_init:109:1997)
    at EventEmitter.<anonymous> (node:electron/js2c/renderer_init:97:862)
    at EventEmitter.emit (node:events:390:28)
    at Object.onMessage (node:electron/js2c/renderer_init:69:746)
```

### Screenshots

![Screenshot from 2022-05-20 11-49-06](https://user-images.githubusercontent.com/36289254/169502755-9a6bb79c-b220-42e3-b147-853284269f1c.png)

### Additional information

This behavior occurs many times randomly, but not always. In Windows is working fine, just Linux (Snap/Flatpak).

**Comment by cheez3d** [comment] 2022-05-20 13:20
Same issue is happening randomly to me on the Linux AUR `ferdium-bin` version.

**Comment by vraravam** [comment] 2022-05-20 23:28
I have faced the same issue on macos - my suspicion was that this is due to network being slow.

The workaround for this is to hard-refresh the service and/or the whole of Ferdium. That should restart the sequence and the loading modal will go away

**Comment by maxecharel** [comment] 2022-05-22 23:13
same issue here (Kubuntu 22.04, snap install); reloading (C-R) do not systematically work though. I also had to disable then re-enable the service, which is not really convenient

**Comment by maxecharel** [comment] 2022-06-04 18:22
@vraravam any idea how to solve that, other than hard-refreshing? since it can still happen after the whole Ferdium has been reloaded (e.g. after switching from one service to another), it is really inconvenient

**Comment by TiZ-HugLife** [comment] 2022-06-06 18:26
This is occurring on the Flathub build as well.

**Comment by Jvlsc** [comment] 2022-06-06 21:32
I didn't know a Flatpak package was already available. I switched it and it's the same behavior. I'm using a dual-boot machine with the same internet connection: in Windows never occurs, but in Linux almost always. So, I don't think it's about the connection itself ( I have a very good one). If there is not a bug in the code, It could be an Electron issue with Linux.

**Comment by mydarkstar** [comment] 2022-06-17 12:26
I assume this is a duplicate of #157

**Comment by vraravam** [comment] 2022-06-17 12:55
Closing this in favor of #157

**Closed as completed by vraravam** 2022-06-17 12:55 UTC
Labels: bug :beetle:
