### ISSUE TITLE
Mobile (Android & iOS) apps

### ISSUE THREAD

**Issue by trymeouteh** [ferdium/ferdium-app#1706] opened 2024-04-17 17:14 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

Unable to use web apps on mobile devices

### Proposed Solution

Making an Android app and iOS app to allow us to use services on the go all in one app.

### Alternatives Considered

None

### Additional Information

Would likely need a codebase for the Android client and another codebase for the iOS client.

**Comment by SpecialAro** [comment] 2024-04-17 17:49
Please search the issue tracker before raising new issues. This is a duplicate of https://github.com/ferdium/ferdium-app/issues/650

**Closed as not planned by SpecialAro** 2024-04-17 17:49 UTC
Labels: duplicate :mirror:
