### ISSUE TITLE
Feature: auto upgrade ferdium .exe standalone app

### ISSUE THREAD

**Issue by spupuz** [ferdium/ferdium-app#191] opened 2022-05-26 08:40 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Feature: auto upgrade ferdium .exe standalone app

### Proposed Solution

Feature: auto upgrade ferdium .exe standalone app

### Alternatives Considered

Feature: auto upgrade ferdium .exe standalone app

**Comment by SpecialAro** [comment] 2022-05-26 09:05
Hey @spupuz ! Thank you for raising this ticket.

Just to clarify, what do you mean by auto upgrade? Do you know that this feature actually exists in Ferdium (altough, given that the nightlies are unsigned for the time being, it is broke)?

Please check Settings > Updates in app.

This is possibly a duplicate of https://github.com/ferdium/ferdium-app/issues/51. Marking this as "Duplicate" and will close shortly.

**Comment by spupuz** [comment] 2022-05-26 09:08
![image](https://user-images.githubusercontent.com/1721792/170456695-28551a5b-93f4-4a93-8ec6-9b1490235594.png)

maybe i'm wrong but this is not the latest version correct?

**Comment by SpecialAro** [comment] 2022-05-26 11:01
That's not, in fact, the latest nightly (currently we're on [v6.0.0-nightly.47](https://github.com/ferdium/ferdium-app/releases/tag/v6.0.0-nightly.47)).

You should open a bug request (instead of a feature request) and report that problem there. That way we can help you get over this issue.

Although, keep in mind what I said before about the fact that the auto-update doesn't work for the time being, given that the code isn't signed yet.
Nevertheless, you should be getting this image when clicking "Check for updates":
![image](https://user-images.githubusercontent.com/37463445/170474055-8cf89730-6ad6-4b2f-8da7-ff0c4154518c.png)

And then it should fail like this:
![image](https://user-images.githubusercontent.com/37463445/170474194-9705caae-7403-4ba3-aed5-57f5f8f75a3c.png)


Given the fact that this issue is a bug and not a feature request, I'm closing it. Please, if you think you still need help join us on discord (https://discord.gg/jVv4Qns8pP) or log a bug report [in here](https://github.com/ferdium/ferdium-app/issues/new/choose ), by selecting Bug Report.

Thank you very much!

**Closed as completed by SpecialAro** 2022-05-26 11:01 UTC
Labels: duplicate :mirror:
