### ISSUE TITLE
Bug: Can't mute a chat in WhatsApp (Dark Mode warning shows up)

### ISSUE THREAD

**Issue by KiritoStorm** [ferdium/ferdium-app#623] opened 2022-09-18 17:05 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.1.0

### What Operating System are you using?

Other Linux

### Operating System Version

Zorin OS 16.1

### What arch are you using?

x64

### Expected Behavior

You should be still able to interact with all modals.

### Actual Behavior

- It overrides the also the menu from the chat muting modal.
- It also appears in the Shortcuts menu for example

### Steps to reproduce

1.) Right click on a chat
2.) Select select mute Notifications

**Result:**
Now you can normally set the time for the mute, it's also shown up the first second, but then it get's overrwritten by the warning.

### Screenshots

![WhatsApp_DarkMode](https://user-images.githubusercontent.com/46503102/190919296-91f74833-ab9b-4d6c-8343-adad0def7b3f.png)
![image](https://user-images.githubusercontent.com/46503102/190919258-127a5eee-4c0e-4cfc-882f-af6aa3a37bbc.png)

**Comment by SpecialAro** [comment] 2022-09-18 17:09
Closing as duplicate of #573

**Closed as not planned** 2022-09-18 17:09 UTC
