### ISSUE TITLE
Whatsapp notification count picks up any group or status that starts with a number as that number of outstanding messages!

### ISSUE THREAD

**Issue by bassmanitram** [ferdium/ferdium-app#829] opened 2022-12-10 15:36 UTC
### Your issue

If I set up a group whose name starts with a number - e.g. "2022 Carol Service" - Ferdium shows THAT number as the number of outstanding messages (plus any real outstanding conversations or messages)

Same goes for messages from a contact name that is actually a phone number.

![image](https://user-images.githubusercontent.com/12625370/206862813-c128d74e-6074-4ebc-bddb-5f93f8c8d75f.png)

![image](https://user-images.githubusercontent.com/12625370/206862855-efb8d0f0-8440-4eac-a897-543eee9b5fe4.png)

(aaaand, from that last one, sometimes it DOUBLES the number it finds

Linux version, v6.2.0

**Comment by localjo** [comment] 2022-12-12 08:47
I've also been seeing really weird notification counts for WhatsApp. It's almost making Ferdium unusable for me. OSX, v6.2.2

**Comment by dev-allinappli** [comment] 2022-12-14 10:32
so do I

**Comment by SpecialAro** [comment] 2022-12-14 10:38
Closing as duplicate of https://github.com/ferdium/ferdium-app/issues/829

Also, please update your app. You are too far behind on versioning.

**Closed as not planned by SpecialAro** 2022-12-14 10:38 UTC
Labels: duplicate :mirror:

**Comment by localjo** [comment] 2022-12-14 10:42
This is #829, I don't think you meant that it's a duplicate of itself. Could you link the duplicate issue?

I've eagerly been updating the app every time an update has been available, and my WhatsApp notifications are still wrong.

Do I need to build this myself to get the bug fix? I don't think this issue has been solved, but if it has, I'd be happy to be corrected and pointed to the solution.

**Comment by localjo** [comment] 2022-12-14 11:16
The latest release on GitHub is v6.2.2, which is what I'm using.

![Screenshot 2022-12-14 at 1 10 33 PM](https://user-images.githubusercontent.com/516388/207580238-5701fbf3-18d2-4dc9-bcd6-403775ee5fc9.png)

```
Version: 6.2.2
Server: No Server
Electron: 21.3.3
Chrome: 106.0.5249.199
Node.js: 16.16.0
Platform: macOS
Arch: arm64
Build date: Mon Dec 05 2022 05:12:32 GMT+0200 (South Africa Standard Time)
Git SHA: 8700f5ca
Git branch: release
```

I've also searched the issues and can't find anything else about WhatsApp notification counts being wrong. Is it really "not planned" to even take a look at this bug?

I've got no unread messages, but Ferdium is showing a count of 2 that will not go away.
![Screenshot 2022-12-14 at 1 17 37 PM](https://user-images.githubusercontent.com/516388/207581606-632a2b0e-07a5-43fd-876a-d2c8d5043b39.png)

This means I have a constant red badge on my dock and I don't really know if I have new messages or not. It completely destroys Ferdium's usability for me.

![Screenshot 2022-12-14 at 1 15 49 PM](https://user-images.githubusercontent.com/516388/207581258-badb80cf-5fcd-473c-a2e5-3f8590e21b7b.png)

@SpecialAro  I really think this issue shouldn't have been closed.

**Comment by bassmanitram** [comment] 2022-12-14 11:35
Upgrading to 6.2.2 does seem to have solved my "groups that start with numbers issue", though closing the issue as a duplicate of itself, with a "not planned" reason doesn't seem to be the _best_ way to endear your users! Perhaps you should have simply closed it as "fixed in 6.2.2"? Possibly pointing to an actual defect report? :)

**Comment by SpecialAro** [comment] 2022-12-14 16:31
Hello again. I'm sorry for linking the wrong issue when closing this as duplicate. This is the correct issue:
https://github.com/ferdium/ferdium-recipes/issues/230

In the past month we received more that 10 duplicate issues of this issue even though we - the maintainers - requested people to look for similar issues before opening a new one. As you may understand, this is very frustrating for maintainers, who not only have to fix/code things but also need to spend their time organizing and closing issues that are duplicated 😢.

This issue, as #230 indicates, had a fix for this in https://github.com/ferdium/ferdium-recipes/pull/240 and, therefore, it was available `v6.2.1-nightly.47` which later on was merged to the stable branch on version `v6.2.1`. Summing up, since `v6.2.1` that this fix is available for users.

The issue described here (as you can see on the first post) is regarding an issue with incorrect message count of the Whatsapp service on version `v.6.2.0` - therefore, it is a duplicate of the the issue I tagged in the beginning of this entry.

Nevertheless, if any of you are still experiencing a wrong Whatsapp count or issue on the latest version of Ferdium, you are more than welcome to open an issue for that - please follow ALL the guidelines on the template before doing so.

PS: 

> I've got no unread messages, but Ferdium is showing a count of 2 that will not go away.

For this I advise you to toggle the button on the right and to see if you have any old notification that's causing the issue (that also happened to me before 😄)
![image](https://user-images.githubusercontent.com/37463445/207650989-7ef0458b-4ced-47c6-8024-b158a84d3cf9.png)

> Upgrading to 6.2.2 does seem to have solved my "groups that start with numbers issue"

If so, did you upgrade you services right after you updated? I can consider reopening this issue if that's the case!
I tried to reproduce this issue in the latest nightly and I wasn't able to to so... There might be an issue on your local config (specially if you upgraded from 6.2.0 to 6.2.2 - some users reported some issues after upgrading).

Also, I'm available (and so are other maintainers) on discord if you need for a quick chat so we try to figure out what is wrong.

**Comment by SpecialAro** [comment] 2022-12-14 16:33
> I've also searched the issues and can't find anything else about WhatsApp notification counts being wrong

About this I think you can find plenty of them if you search:
https://github.com/ferdium/ferdium-app/issues?q=is%3Aissue+whatsapp
https://github.com/ferdium/ferdium-recipes/issues?q=is%3Aissue+whatsapp

Remember to always look for closed issues (as it is indicated on the template before opening a new one).

**Comment by bassmanitram** [comment] 2022-12-14 18:06
Hey @SpecialAro - I said that 6.2.2 _has_ fixed it. So no worries.
