### ISSUE TITLE
Bug: Status down?

### ISSUE THREAD

**Issue by Namoku** [ferdium/ferdium-app#506] opened 2022-07-21 18:47 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0

### What Operating System are you using?

Windows

### Operating System Version

11 21H2

### What arch are you using?

x64

### Last Known Working Ferdium version

6.0.0

### Expected Behavior

Working ferdium servers.

### Actual Behavior

Can't connect to Ferdium online services.

### Steps to reproduce

1. Open ferdium
2. Click try again in can't connect
3. Not working.

### Screenshots

![image](https://user-images.githubusercontent.com/31052826/180291781-11a0876d-06c8-42da-912d-858220ac48d0.png)

### Additional information

I turn on my pc and stopped working, I have Mac m1 too, and I logout and login to my mac and stopped working too.

**Comment by upgreydd** [comment] 2022-07-21 18:50
Same here

**Comment by Rizwan-Hasan** [comment] 2022-07-21 18:50
I'm facing the same issue in my Manjaro setup. Annoying.

**Comment by atoerien** [comment] 2022-07-21 18:54
I've got the same issue - going to https://api.ferdium.org gives an expired Let's Encrypt certificate error so that's probably what's causing it.

**Comment by spsf64** [comment] 2022-07-21 18:54
Same here, also unable to sign in to my account

**Comment by SpecialAro** [comment] 2022-07-21 18:57
> I've got the same issue - going to https://api.ferdium.org gives an expired Let's Encrypt certificate error so that's probably what's causing it.

This is the problem actually.

**Comment by cmtcosta** [comment] 2022-07-21 19:06
On MacOS 12.4 with v6.0.0 nightly, also unable to use the service.

**Comment by jasmines** [comment] 2022-07-21 19:15
Devs: enable autorenew for let's encrypt... it's the ABC...

**Comment by Shrekmachine** [comment] 2022-07-21 19:19
works again

**Comment by dqos** [comment] 2022-07-21 19:22
This was indeed caused by a certificate issue, we are investigating why this happened suddenly.

It has been fixed so I am closing this ticket.

**Closed as completed by dqos** 2022-07-21 19:22 UTC
Labels: bug :beetle:
