### ISSUE TITLE
Forgotten custom icons

### ISSUE THREAD

**Issue by stevelacey** [ferdium/ferdium-app#1349] opened 2023-09-05 04:46 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.4.1

### What Operating System are you using?

macOS

### Operating System Version

macOS Monterey 12.4

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Custom icons are never forgotten.

### Actual Behavior

Custom icons periodically vanish and have to be deleted and added again.

### Steps to reproduce

Not sure, maybe certain updates, or bad force quits cause this?

### Screenshots

They show as blank, these are all Slack's with custom icons:

<img width="71" alt="Screen Shot 2023-09-05 at 12 41 45" src="https://github.com/ferdium/ferdium-app/assets/289531/be3fa7c5-5f91-45de-a98c-dedcbb88fdc4">

They still have their delete button:

<img width="188" alt="Screen Shot 2023-09-05 at 12 44 26" src="https://github.com/ferdium/ferdium-app/assets/289531/88a1a7eb-acb1-4536-ac68-47c7d75f1d2d">

**Comment by SpecialAro** [comment] 2023-09-06 08:52
Closing this issue as a duplicate of #1252

**Closed as not planned** 2023-09-06 08:52 UTC
Labels: bug :beetle:, duplicate :mirror:
