### ISSUE TITLE
Bug: Outlook does not save credentials after close/restart/lock

### ISSUE THREAD

**Issue by spsf64** [ferdium/ferdium-app#126] opened 2022-05-09 13:35 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

v6.0.0-nightly.30 Appimage

### What Operating System are you using?

Other Linux

### Operating System Version

Archlinux 

### What arch are you using?

x64

### Expected Behavior

After restart just select the service and see emails

### Actual Behavior

After restart I have to input my email (ie: xxxx@msn.com), however the password is not asked and it works fine, very strange....

### Steps to reproduce

Close or wait it to lock and restart ferduim

### Additional information

I use also yahoo and gmail, both work without any problem.

**Comment by SpecialAro** [comment] 2022-05-09 14:32
This is a known bug (there was a PR that was closed - not merged - that tried to solve this on the Ferdium-Server repo).

Can you please try to change the url of your recipe to https://outlook.live.com/mail/ instead or https://outlook.office365.com/mail/ and see if this solves your isse?

To change the URL edit your recipe and change it to self-hosted.

Thank you @spsf64!

**Comment by spsf64** [comment] 2022-05-09 14:42
> This is a known bug (there was a PR that was closed - not merged - that tried to solve this on the Ferdium-Server repo).
> 
> Can you please try to change the url of your recipe to https://outlook.live.com/mail/ instead of https://outlook.office365.com/mail/ and see if this solves your issue (as a workaround, for now)?
> 
> To change the URL edit your recipe and change it to self-hosted.
> 
> Thank you @spsf64!

Sorry, I just checked the open issues before reporting...
I will try your suggestions and report back, thanks for the quick reply!

**Comment by mydarkstar** [comment] 2022-05-09 14:55
Duplicate of https://github.com/ferdium/ferdium-recipes/issues/8

Referenced, closed PR: https://github.com/ferdium/ferdium-recipes/pull/9 (did not solve the issue)

**Comment by spsf64** [comment] 2022-05-09 14:57
Wow! It works!
Thanks @SpecialAro , hope you can implement this in future releases.
BTW, the dark mode is so cool!

**Closed** 2022-05-10 09:35 UTC
Labels: bug :beetle:, question :question:
