### ISSUE TITLE
Bug: Custom icon on custom website does not load (probably linked to Ferdium server)

### ISSUE THREAD

**Issue by tr1plus** [ferdium/ferdium-app#621] opened 2022-09-16 18:40 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0 and 6.1

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 home 21H1

### What arch are you using?

x64

### Expected Behavior

Icon is shown

### Actual Behavior

No icon is shown

### Steps to reproduce

1. Add new service
2. Custom Website
3. Choose a custom icon (enter name/custom server, ...)
4. Save service

Note - I am using Ferdium Server (docker version)

### Screenshots

![image](https://user-images.githubusercontent.com/7044850/190708757-35fddb45-6f4e-473c-a91c-aa8e6522b58d.png)

### Additional information

Briefly discussed in discord already, but no solution found https://discord.com/channels/963836780778512454/963841911376982046/1017133812704088187

(scroll down as some more messages/ info is being sent there)

**Comment by gabriel-andreescu** [comment] 2022-09-22 19:06
This also happens for Gmail (also using self hosted server):
![image](https://user-images.githubusercontent.com/3175443/191830865-5e5ac9cc-a729-4b4e-8786-eed758dece18.png)

**Comment by ghalpha** [comment] 2022-10-02 18:29
I am also seeing this on the self hosted server with pretty much any custom application. My guess is there is a permission error somewhere not allowing the file to be uploaded to the local server directory.

**Comment by klonos** [comment] 2022-10-13 19:59
I confirm this happening with 6.2.0 on a local, "accountless" setup, with any service that has a custom icon configured. It is happening with Slack, Zulip, Rocket Chat, so I don't think that this is service-specific.

**Comment by jgeusebroek** [comment] 2022-10-14 09:18
I can also confirm.

**Comment by tr1plus** [comment] 2022-11-19 11:40
Hi - I think I found a solution after deepdiving trough the code of the Ferdium server and following step by step how the icons get saved a processed.

**NOTE**: the issue is not with the Ferdium app, but with the Ferdium server.

The app_url should contain "https://" if you are serving your server over https(otherwise I believe it tries HTTP and doesn't redirect). After making this change, custom icons started working for me. As I was working with docker, this was changeable by the environment variable "APP_URL"

I also had to make the /app/tmp path re-usable by mounting it in volumes
```
    volumes:
      - "/mnt/storage/docker-container/ferdium-server/tmp:/app/tmp"
```

**Comment by gabriel-andreescu** [comment] 2022-11-19 11:49
@tr1plus that worked for me too, thank you!

**Comment by rubycerebra** [comment] 2022-11-22 11:42
Any ideas how to get this to work on a mac?

**Comment by ylluminate** [comment] 2022-11-24 05:39
Using Ferdium server-less here and after several months I've added a new service, but now I cannot customize the icon any longer. Only the default loads for new services now. Is this related to this issue?

**Comment by rndthoughts** [comment] 2022-12-02 10:30
I have the same problem but I think a different cause. I am not using HTTPS currently as my server is internal only, but i setup the /tmp docker setting anyway from @tr1plus suggestion.  However, looking at the development tools window, I can see upon selecting an icon image and hitting Save:

1. It loads the image I select from the local disk correctly using GET with file:// and gets a 200.
2. It then does a PUT but it only pushes the JSON relating to the server - there is no file upload going on as far as I can see.
3. It then makes 3 GET requests to the /v1/icon/guid.png endpoint and gets a 404.  Not sure if this is three because I have tried to set icons from other services too?

Willing to assist with any logs anyone needs, but at the moment it makes Ferdi very hard to use if i cant see at a glance which custom website icon i need to click!

**Comment by vraravam** [comment] 2022-12-02 12:55
Is this a duplicate of #809 ? If so, its been fixed in the 6.2.2-nightly.1 release. ofc, please upgrade to the newer nightly to get other bug fixes as well.

**Comment by rndthoughts** [comment] 2022-12-02 12:58
Can confirm, the nightly build referenced above fixes it.

**Comment by vraravam** [comment] 2022-12-02 14:12
Thanks. Closing as a duplicate of #809

**Closed as completed by vraravam** 2022-12-02 14:12 UTC
Labels: bug :beetle:, question :question:
