### ISSUE TITLE
Discord do not show badges for all new message, even with setting activated.

### ISSUE THREAD

**Issue by gauchya** [ferdium/ferdium-app#1370] opened 2023-09-21 08:53 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.4.1-beta.2

### Recipe Name

Discrod

### Recipe Version

1.8.0

### Steps to reproduce

1. Join a Discord server and keep all notification
2. Activate Badges for all message in Discord recipe settings
3. Receive a message in the server, with no @name @here @all ...
4. No notification

### Expected Behavior

A "New message badge" should appear when a message is received in any server with discord notification on when the settings is activated.

### Actual Behavior

No Ferdium notification or new message badge. 

### Screenshots

![image](https://github.com/ferdium/ferdium-app/assets/7487956/ad842b5e-7411-442e-af2b-fc62e4cee9f6)

New message, no badge.

**Comment by Arthur-Huan** [comment] 2023-09-23 03:51
Could you provide OS info? I cannot reproduce this on Fedora Linux and Windows 10.

**Comment by gauchya** [comment] 2023-09-25 08:16
I use Ubuntu 23.04.  
A friend use mac OS and have the same problème.

Just note that if someone talk to me in a 1-1 discussion it works and if in the server the message is a reply to one of my message it works too or if it is a @MyName even in a server chat it works too.

Only "basic" messages in a server don't work.

**Comment by Mickhopes** [comment] 2023-09-26 15:46
Hi,

This problem exists only if you receive a notification on a server that is not currently opened in Discord.

The recipe is looking at the `modeUnread-*` classes to check for indirect messages but this CSS class is attached to channels. As they are not part of the view on non-opened servers you are not notified.

This can be fixed using the `document.title`. Discord will change it's title with `(<number>) Discord | ...` when you have direct message(s) and `• Discord | ...` when you have indirect message(s) (prioritizing showing the first one). If the character `•` is present on the title, you have unread indirect messages.

**Comment by gauchya** [comment] 2023-09-29 09:59
Using @Mickhopes method in a discord recipe fixed my and my friend issue.

**Comment by chaudron** [comment] 2023-10-13 09:54
@gauchya having the same problem. New to Ferdium so how/what/where do I change the recipe?

**Comment by andyeff** [comment] 2023-10-29 15:53
> Using @Mickhopes method in a discord recipe fixed my and my friend issue.

I'm guessing this involves editing the webview.js for the Discord service, this part?

```js
    const indirectCountPerServer = document.querySelectorAll(
      '[class*="modeUnread-"]',
    ).length;
```

Would you be able to show how you used document.title to fix this? I don't know enough javascript to figure this out currently :(

@chaudron I found the file to edit at this path (for windows): `%appdata%\Ferdium\recipes\discord\webview.js`

**Comment by Mickhopes** [comment] 2023-10-30 08:23
To find the folder containing the recipes, you go to _Settings > Advanced_ and then on the bottom **Open Service Recipes folder**.

In this folder you have to edit _discord/webview.js_ and replace:

```javascript
const indirectCountPerServer = document.querySelectorAll(
      '[class*="modeUnread-"]',
    ).length;
```

with

```javascript
const indirectCountPerServer = document.title.search("•") != -1 ? 1 : 0;
```

**Comment by briankendall** [comment] 2023-10-31 16:33
There's another issue where direct messages, either from a server or in DMs, are not causing Ferdium to add a badge to Discord's icon.

The solution is to change the following code in `discord/webview.js`:

        const directCountPerServer = document.querySelectorAll(
          '[class*="lowerBadge-"] [class*="numberBadge-"]',
        );

to:

        const directCountPerServer = document.querySelectorAll(
          '[class*="lowerBadge_"] [class*="numberBadge_"]',
        );

(Note that change from hyphens to underscores in the class names.)

**Comment by Cknight70** [comment] 2023-11-04 04:17
Hi @briankendall and @Mickhopes Hope you don't mind I opened a pull request to get discord notifications fixed using your advice. Thanks

**Comment by Cknight70** [comment] 2023-11-10 05:37
It is done

**Comment by mcmxcdev** [comment] 2023-11-11 22:28
Closing since the fix in https://github.com/ferdium/ferdium-recipes/pull/461 was merged

**Closed as completed by mcmxcdev** 2023-11-11 22:28 UTC
Labels: bug :beetle:, recipe :bookmark_tabs:
