### ISSUE TITLE
Bug: Whatsapp theme popup jumps when deleting a msg

### ISSUE THREAD

**Issue by eyallior** [ferdium/ferdium-app#610] opened 2022-09-10 18:16 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.1.0

### What Operating System are you using?

Other Linux

### Operating System Version

Pop!_OS 22.04

### What arch are you using?

x64

### Expected Behavior

I'm trying to delete a message from a chat in whatsapp - I'm expecting the whatsapp confirmation popup to show

### Actual Behavior

the dark/light theme popup shows, and it looks like it's combined with the delete message confirmation popup from whatsapp - attaching here

### Steps to reproduce

Try to delete a message in whatsapp, the confirmation popup is wrong

### Screenshots

![ksnip_20220910-210746](https://user-images.githubusercontent.com/7419178/189496388-e9278fa5-76d4-451f-b59f-ad7638aec965.png)

### Additional information

s

**Comment by SpecialAro** [comment] 2022-09-10 18:26
Duplicate of https://github.com/ferdium/ferdium-app/issues/595

**Closed as not planned** 2022-09-10 18:27 UTC
Labels: duplicate :mirror:
