### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by iCheater** [ferdium/ferdium-app#1720] opened 2024-04-25 13:19 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.3-nightly.5

### What Operating System are you using?

Windows

### Operating System Version

Windwos 10  22H2

### What arch are you using?

x64

### Last Known Working Ferdium version

the first time i face it was about year ago

### Expected Behavior

- I excect that ferdium will not run like miner.
- Ferdium should not spawn processes, that will consume 10% of cpu power for NO REASON

### Actual Behavior

Ferdium spawns processes, that will consume 10% of cpu power for NO REASON

### Steps to reproduce

- Run ferdium, add telegram and whatsapp accounts
- Do not reboot pc (only hibernate ) 

### Debug link

https://debug.ferdium.org/6fd00d3f-4f2e-49fc-bc79-052980c4babb

### Screenshots

![ferdium](https://github.com/ferdium/ferdium-app/assets/13772028/281c4682-54e0-4eec-857b-2806e3eeb130)
![ferdium_2](https://github.com/ferdium/ferdium-app/assets/13772028/1944bb97-e1b8-4173-b9ff-3f09f58ed350)

### Additional information

Version: 6.7.3-nightly.5
Server: No Server
Electron: 29.1.6
Chrome: 122.0.6261.139
Node.js: 20.9.0
Platform: Windows 10
Arch: x64
Build date: Sun Mar 31 2024 07:22:48 GMT+0300 
Git SHA: 740a7593
Git branch: nightly

**Comment by vraravam** [comment] 2024-04-25 13:44
We just released v6.7.3 public stable version of ferdium. Please try with that and get back if this is still an issue.

Also - since you are on nightlies, please report bugs against the latest version. It will not be possible to go back to an older version and try to perform a root cause analysis on that older version.

**Comment by iCheater** [comment] 2024-04-25 13:53
> We just released v6.7.3 public stable version of ferdium. Please try with that and get back if this is still an issue.
> 
> Also - since you are on nightlies, please report bugs against the latest version. It will not be possible to go back to an older version and try to perform a root cause analysis on that older version.

- i was on stable latest version over a year
- i started to use nightly "some time ago" (maybe a moth?)
- ill switch to stable

**Comment by iCheater** [comment] 2024-04-25 13:55
Hh, i forgot to notice that i had the same behavior with franz. 
Franz and ferdium work perfectly on mac, but have troubles on windows.

**Comment by SpecialAro** [comment] 2024-04-26 00:45
Hi!

Is this issue a duplicate of https://github.com/ferdium/ferdium-app/issues/219 ?

**Comment by iCheater** [comment] 2024-04-26 10:03
> Hi!
> 
> Is this issue a duplicate of #219 ?
Hi!
Yes, you are right. My issue can be marked as dublicate.

**Closed as not planned** 2024-04-26 11:34 UTC
Labels: duplicate :mirror:

**Comment by dluca22** [comment] 2024-05-17 19:03
Hi, unfortunately I must report having the same issue on 6.7.3
I noticed it yesterday first time since my work laptop was laggging badly and noticed that i had about 15+ open ferdium processes. Nothing weird happened previous to that, i just closed everyone of them and went on fine by restarting.
Today happened the same thing and started googling and came across this thread, but i already am on the suggested version

Version: 6.7.3
Server: Ferdium Server
Electron: 30.0.1
Chrome: 124.0.6367.60
Node.js: 20.11.1
Platform: Windows 10
Arch: x64
Build date: Thu Apr 25 2024 03:14:04 GMT+0200 (Ora legale dell’Europa centrale)
Git SHA: d8f519a8
Git branch: release



Let me know if there's something else i could provide you.
I can't recall anything weird or different in the last couple of days that might have caused this, I have been using Ferdium on this pc about 6 months and this are first issues with it.

**Comment by iCheater** [comment] 2024-05-18 17:20
> Hi, unfortunately I must report having the same issue on 6.7.3 I noticed it yesterday first time since my work laptop was laggging badly and noticed that i had about 15+ open ferdium processes. Nothing weird happened previous to that, i just closed everyone of them and went on fine by restarting. Today happened the same thing and started googling and came across this thread, but i already am on the suggested version
> 
> Version: 6.7.3 Server: Ferdium Server Electron: 30.0.1 Chrome: 124.0.6367.60 Node.js: 20.11.1 Platform: Windows 10 Arch: x64 Build date: Thu Apr 25 2024 03:14:04 GMT+0200 (Ora legale dell’Europa centrale) Git SHA: [d8f519a](https://github.com/ferdium/ferdium-app/commit/d8f519a8eea28b88b727ddc6a2a42b6e3d784e02) Git branch: release
> 
> Let me know if there's something else i could provide you. I can't recall anything weird or different in the last couple of days that might have caused this, I have been using Ferdium on this pc about 6 months and this are first issues with it.

Hi! 
i've reproduced the bug here 
https://github.com/ferdium/ferdium-app/issues/219#issuecomment-2081631653

**Comment by dluca22** [comment] 2024-05-18 20:40
> > Hi, unfortunately I must report having the same issue on 6.7.3 I noticed it yesterday first time since my work laptop was laggging badly and noticed that i had about 15+ open ferdium processes. Nothing weird happened previous to that, i just closed everyone of them and went on fine by restarting. Today happened the same thing and started googling and came across this thread, but i already am on the suggested version
> > Version: 6.7.3 Server: Ferdium Server Electron: 30.0.1 Chrome: 124.0.6367.60 Node.js: 20.11.1 Platform: Windows 10 Arch: x64 Build date: Thu Apr 25 2024 03:14:04 GMT+0200 (Ora legale dell’Europa centrale) Git SHA: [d8f519a](https://github.com/ferdium/ferdium-app/commit/d8f519a8eea28b88b727ddc6a2a42b6e3d784e02) Git branch: release
> > Let me know if there's something else i could provide you. I can't recall anything weird or different in the last couple of days that might have caused this, I have been using Ferdium on this pc about 6 months and this are first issues with it.
> 
> Hi! i've reproduced the bug here [#219 (comment)](https://github.com/ferdium/ferdium-app/issues/219#issuecomment-2081631653)

You're right! i use multiple desktops as well but forgot to mention.
I think it's something related to a recent update because my setup has not changed since installing it first time and last couple of days were my first bugs with ferdium

**Comment by viv-01** [comment] 2024-06-11 04:25
Same issue with me, high cpu usage.  30% of my cpu usage goes towards Ferdium

Version: 6.7.4
Server: No Server
Electron: 30.0.6
Chrome: 124.0.6367.207
Node.js: 20.11.1
Platform: Windows 11
Arch: x64
Build date: Sat May 18 2024 06:51:10 GMT+0200 (South Africa Standard Time)
Git SHA: cb7f4598
Git branch: release


![Screenshot 2024-06-11 062353](https://github.com/ferdium/ferdium-app/assets/63659554/61bee8ef-a98f-4a77-b14b-618e7b142a77)

**Comment by WebShapedBiz** [comment] 2024-07-31 18:54
I have the same issue on my Linux PC where Ferdium is never under 75% CPU usage:
elementary OS 6.1 Jólnir, based on Ubuntu 20.04.6 LTS
Lenovo IdeaCentre-3 (8× AMD Ryzen 7 4800u with Radeon graphics, 16GB RAM)

4 active services (2x Gmail, Google Calendar, Google Contacts)

Version: 6.7.5
Server: No Server
Electron: 31.1.0
Chrome: 126.0.6478.114
Node.js: 20.14.0
Platform: Linux 5.15
Arch: x64
Build date: Sat Jun 29 2024 03:42:50 GMT+0200 (srednjoeuropsko ljetno vrijeme)
Git SHA: 5514cab9
Git branch: release

Cheers.

**Comment by luthor112** [comment] 2025-04-19 16:32
Same for me now, on 34.4.1 on Windows.

**Comment by svobom57** [comment] 2025-05-15 07:59
I second this too:
Running Macbook Air with M4

![Image](https://github.com/user-attachments/assets/76d11d40-985d-4dae-8701-f073d11b1ff3)

When the windows initially load the CPU spikes. 

After they finish loading the CPU drops off:

![Image](https://github.com/user-attachments/assets/ca597cea-7669-48a1-b6b6-3c50bd0b6929)

But then if I leave Ferdium on for a while and come back the windows tend to refresh. 

It also takes really long time for the CPU to drop-off and for the apps to load.
