### ISSUE TITLE
[Bug]: Slack Huddle : Can't open the screen sharing preview

### ISSUE THREAD

**Issue by ragusa87** [ferdium/ferdium-app#974] opened 2022-11-22 10:08 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Ferdium Version

6.2.0

### Recipe Name

slack

### Recipe Version

b14a52d

### Steps to reproduce

1. Add a "slack" service and login
2. Join a channel and start a huddle
3. Share your own screen
4. Click on the screen preview to maximize it or on the "View Shared Screen" button (see screenshot)

### Expected Behavior

The shared screen should be opened in a new window so you can see the screen content

### Actual Behavior

Nothing happen, the new window doesn't open.

### Screenshots

![image](https://user-images.githubusercontent.com/1695207/203286563-d2b27066-24bc-4e6e-bc4c-dd0d7f29574f.png)

### Additional Information

Logs:
```
[42529:1122/105853.551585:ERROR:egl_dmabuf.cc(569)] Failed to record frame: Error creating EGLImage - EGL_NOT_INITIALIZED
[42529:1122/105853.551637:ERROR:shared_screencast_stream.cc(655)] Dropping DMA-BUF modifier: 72057594037927935 and trying to renegotiate stream parameters
(electron) The new-window event is deprecated and will be removed. Please use contents.setWindowOpenHandler() instead.

```

**Comment by ragusa87** [comment] 2022-11-22 10:12
Slack recipe on commit b14a52d is version 1.4.2

**Comment by jampoyman** [comment] 2022-12-01 12:00
This issue also occurs when you try to view shared screens from other people in the huddle.

**Comment by kciredor** [comment] 2022-12-01 12:23
> This issue also occurs when you try to view shared screens from other people in the huddle.

Exactly, which is the reason I wanted to create an issue here, but it has already been filed ;-)

**Comment by jurienhamaker** [comment] 2022-12-07 09:46
This is turning into quite the hassle for me with my work slack. Would love to see a fix. I'll try check if I can do anything myself.

Also kind of annoying how slack pushes huddles this hard, since not everyone loves it that much, but that's a discussion for somewhere else.

**Comment by jsanta** [comment] 2022-12-07 19:32
Same problem here. Trying to opt out from Rambox and Slack huddles are the only thing  stopping me from doing so.

**Comment by jdegger** [comment] 2023-01-30 12:40
Confirming this bug also exists on macOS

**Comment by jurienhamaker** [comment] 2023-03-21 10:00
9 days left, any news?

**Comment by bachi76** [comment] 2023-04-12 09:20
Same here. I remember in Franz the issue existed as well, but in a different way: It would open a new window, but with no content, and that window seemingly belonged to Franz (menus etc.). Maybe this helps in a way.

**Comment by rogorman-provenir** [comment] 2023-04-17 14:56
I cant share my screen at all on Mac OS, slack huddles barely function in Ferdium, such a shame. Service disabled for now and will have to use slack like normal :(

**Comment by RohitSurwase** [comment] 2023-05-11 10:33
This is a must have feature for Slack Service. I hope it gets added soon.

**Comment by jurienhamaker** [comment] 2023-06-03 22:03
How is this still not fixed. Does anyone know whats up? I am fine with creating a PR if I have a lead

**Comment by jampoyman** [comment] 2023-06-04 00:54
> How is this still not fixed. Does anyone know whats up? I am fine with creating a PR if I have a lead

If you check the service logs, it looks like slack is trying to open a popup window and it gets blocked.

**Comment by jurienhamaker** [comment] 2023-06-05 13:45
> > How is this still not fixed. Does anyone know whats up? I am fine with creating a PR if I have a lead
> 
> If you check the service logs, it looks like slack is trying to open a popup window and it gets blocked.



Yeah I know that much, but I don't know where in Ferdium such a thing is controlled. Is it service level, app level, etc ?

**Comment by ChumlyFernando** [comment] 2023-06-27 19:23
Confirming that this is still happening on v6.4 on Windows 11 PRO 2H22 x64.

**Comment by tilaktilak** [comment] 2023-07-06 16:21
Hi everyone, in case it helps, here's the error message I get while trying to maximize the huddle : 
![slack_huddle_error](https://github.com/ferdium/ferdium-app/assets/6662416/5a03afeb-4f41-4b60-9ae8-17bc911954ca)

**Comment by sean-d** [comment] 2023-07-07 21:10
can confirm this issue exists on 

`Version: 6.4.0
Server: Ferdium Server
Electron: 25.2.0
Chrome: 114.0.5735.134
Node.js: 18.15.0
Platform: Linux 6.1
Arch: x64
Build date: Fri Jun 23 2023 11:45:19 GMT-1000 (Hawaii-Aleutian Standard Time)
Git SHA: 41c29e60
Git branch: release`

**Comment by jnvillar** [comment] 2023-08-04 15:06
still happening, mac os latest nightly

**Comment by raulillo82** [comment] 2023-08-18 11:07
+1 opensuse tumbleweed through flatpack (works well in Slack through flatpack).

**Comment by RPDiep** [comment] 2023-08-22 07:52
![image](https://github.com/ferdium/ferdium-app/assets/4834747/80f7f522-8669-49ef-b359-6faaf20d8030)
Here's a more complete log of the errors.
Unfortunately I don't know enough of javascript to be able to fix this.

**Comment by softexpert** [comment] 2023-09-13 06:38
+1 just had it with slack 1.50 on Ferdium 6.5.0-nightly.6

**Comment by mcmxcdev** [comment] 2023-10-01 14:15
Closing as duplicate of https://github.com/ferdium/ferdium-app/issues/788

**Closed as completed by mcmxcdev** 2023-10-01 14:15 UTC
Labels: bug :beetle:, recipe :bookmark_tabs:
