### ISSUE TITLE
Bug: Cannot delete WhatsApp messages

### ISSUE THREAD

**Issue by FANMixco** [ferdium/ferdium-app#608] opened 2022-09-09 06:49 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.1.0

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 21H2

### What arch are you using?

x64

### Expected Behavior

I should be able to delete my messages, but the popups are being replaced by something else:

![image](https://user-images.githubusercontent.com/1666156/189287877-e744519f-f08b-4b3c-8313-88f8dbd4ad15.png)

### Actual Behavior

This popup is replacing and blocking the normal popup:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/1666156/189288463-0b155e01-a518-426d-ba0e-06a5fa9c00cd.gif)

### Steps to reproduce

1. Open WhatsApp.
2. Choose any chat.
3. Choose Delete chat.

### Screenshots

![ezgif com-gif-maker](https://user-images.githubusercontent.com/1666156/189288463-0b155e01-a518-426d-ba0e-06a5fa9c00cd.gif)

### Additional information

N/A

**Comment by SpecialAro** [comment] 2022-09-09 07:28
Duplicate of https://github.com/ferdium/ferdium-app/issues/595

**Closed as not planned** 2022-09-09 07:28 UTC
Labels: duplicate :mirror:
