### ISSUE TITLE
Ferdium can not connect to API

### ISSUE THREAD

**Issue by 2ge** [ferdium/ferdium-app#1995] opened 2024-12-06 14:54 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

7.0.0

### What Operating System are you using?

macOS

### Operating System Version

Sonoma 14.7.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Ferdium version

N/A

### Expected Behavior

Today my Ferdium services doesnt load. Is your API down ? Getting 500/SSL errors.

### Actual Behavior

```
% curl -I https://api.ferdium.org
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.ferdium.org:443
Exit 35
```

### Steps to reproduce

open ferdium with services hosted in ferdium.

### Additional information

Version: 7.0.0
Server: Ferdium Server
Electron: 33.2.0
Chrome: 130.0.6723.118
Node.js: 20.18.0
Platform: macOS Unknown
Arch: arm64
Build date: Sat Nov 09 2024 21:21:54 GMT-0500 (Colombia Standard Time)
Git SHA: e6249427
Git branch: release

**Comment by sashistillfrvr** [comment] 2024-12-06 14:59
Can't use ferdium too. can't connect to the ferdium servers.

**Comment by 2ge** [comment] 2024-12-06 15:08
seems it is back, probably temporary issue.

**Comment by torstenhoppe** [comment] 2024-12-06 16:59
No, unfortunately not, as you can see here https://github.com/ferdium/ferdium-status But I'm wondering where the files for the services are stored on MacOS. The fact that synchronization doesn't work is one thing, but the services must be stored locally somewhere. Where can I find them? And why doesn't the app use these local files for the connections to the services?

**Comment by torstenhoppe** [comment] 2024-12-06 17:12
It tooks its time, now the server seem to work again, but my question where the files are stored locally stays on. Who can help with information?

**Comment by heyeddi** [comment] 2024-12-06 17:31
@torstenhoppe I found some files on `$HOME/.config/ferdium` (not sure if it's the same on MacOS) still, it seems it needs the connection to the API to work.

I do not know if it was a coincidence, but I re-installed Ferdium, and it started working again.

**Comment by Supermarcel10** [comment] 2024-12-06 17:35
Also having issues on Windows & Linux. Cannot access or use Ferdium at all.

![image](https://github.com/user-attachments/assets/81fa6d40-00a4-4e8a-8d94-38350ca4e9ca)

Really starting to question the point of Ferdium (which has been unreliable for me over the last year), especially since it's making some of my core communications unavailable atm. I might have to move to something different. It's somewhat blatantly poor design imo, if an API is required to use something that is present locally.

**Comment by sashistillfrvr** [comment] 2024-12-06 17:50
Exactly. I can understand that maybe some of the features on ferdium shouldn't work if the API is down, but the services wont work if the API is down?, doesn't should work like that.

**Comment by sashistillfrvr** [comment] 2024-12-07 02:35
Ferdium can not connect to API again.
![imagen](https://github.com/user-attachments/assets/76866a70-8bbf-4be3-aefd-37ceddfa351f)

**Comment by mauro-miatello** [comment] 2024-12-07 08:02
me too, Linux Mint. and this is not as it should work. 
why does my gmail need ferdium to work? nonsense... or is ferdium tracking my data?

**Comment by eps90** [comment] 2024-12-07 09:55
> Exactly. I can understand that maybe some of the features on ferdium shouldn't work if the API is down, but the services wont work if the API is down?, doesn't should work like that.

Fully agree. The app should allow to use the integration using locally stored configuration, even when the API is down. As far as I understand, the API is used to get the account information, but it should not be a must-have. In a worst case scenario, when the API is down, it should sync all the settings whenever it's up again.

**Comment by procobain** [comment] 2024-12-07 10:35
My dear Devs... Ferdium is the best program of its kind, it's one of the most useful and important for me, I believe it is for many people too... But they need to find a way to fix this, it shouldn't only work if an API is online, even similar (and worse) programs didn't have that...

Cheers.

**Comment by 2ge** [comment] 2024-12-07 12:47
it seems it is time to find alternative - no reply from devs? I was using Ferdium daily, I believe others too. When I can not use it, because API is down, it is unusable program for me.

**Comment by SpecialAro** [comment] 2024-12-07 14:10
Hello!

In the last months I've been away from development given the fact that I'm working on my PhD and on my day job, which unfortunately didn't allowed me to take the time to look further into this.

Nevertheless, I've been looking at the logs on the server side to try and understand what may be causing this and so far I've come with almost no theory. My best guess is that this is caused by a memory leak on the docker container containing the server.

We are aware that this issue is important and impacts the users negatively, but because me and other devs haven't been able to take the time to look into it, the issue hasn't been fixed yet.

As this is an open source software, anyone that is willing and has the time/energy/knowledge to contribute is more than welcomed to give this and other issues a chance of fixing.

What we kindly ask is that end users understand that we work on this project on our own personal time and that sometimes we are not able to give as much as we and other end users would want us to give to the project. Also, please, whenever you are logging new issues on GitHub (such as this one) please make sure to follow the rules, as there already are several open issues regarding this problem. This bloats the issue board and, consequently, takes us more time on solving issues - because we are worried on making the issue board clean with the information centralized on one single thread rather than in different threads.

All in all, I will personally take a look at this issue in order to address it whenever I get the time. But again, please understand, as this issue is a rather difficult one to reproduce locally (as it has to do probably with memory leaks that are impacted by the large usage of the app amongst users) it might take some time to solve.

Best,
André

**Comment by sashistillfrvr** [comment] 2024-12-07 21:02
I clearly understand that you don't really have time to look further to this issue. It's not about the issue actually, the problem is that the services should work if the API is down. if an API is required to use something that is present locally i don't feel safe to use the app. I didn't know it works like that. I always thought it was like opening a web browser but stored only on pages I need like social media or Mail.

**Comment by SpecialAro** [comment] 2024-12-09 16:15
Closing as duplicate of https://github.com/ferdium/ferdium-app/issues/1926

**Closed as not planned by SpecialAro** 2024-12-09 16:15 UTC
Labels: duplicate :mirror:
