### ISSUE TITLE
Can't  connect to ferdium service notification at login windows

### ISSUE THREAD

**Issue by cubiboy90** [ferdium/ferdium-app#1964] opened 2024-11-10 17:47 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.7

### What Operating System are you using?

macOS

### Operating System Version

15.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

When move to the page sign up or login page when start ferdium, the notification "Can't  connect to ferdium service" appear and I can't create account or login either

### Actual Behavior

When move to the page sign up or login page when start ferdium, the notification "Can't  connect to ferdium service" appear and I can't create account or login either

### Steps to reproduce

1. start ferdium
2. Click "Create a free account"
3. error can't not connect to ferdium appear
4. continue with "login to your account"
5. that error still appear

**Comment by shaneoreilly** [comment] 2024-11-11 03:31
Same
macOS 15.1

Version: 7.0.0
Server: Ferdium Server
Electron: 33.2.0
Chrome: 130.0.6723.118
Node.js: 20.18.0
Platform: macOS Unknown
Arch: arm64
Build date: Sat Nov 09 2024 21:21:54 GMT-0500 (Eastern Standard Time)
Git SHA: e6249427
Git branch: release

**Comment by fherbin** [comment] 2024-11-13 08:34
same

Ubuntu:  24.04 LTS
Ferdium:  7.0.0

**Comment by Leny1337** [comment] 2024-11-13 08:51
The same, looks like it's missing local data, because even when API is down, it should load my services from local storage. Right now it's totally unusable.

**Comment by sefrijn** [comment] 2024-11-13 18:37
Same issue here
![Screenshot 2024-11-13 at 19 36 39](https://github.com/user-attachments/assets/d61b03f9-186d-4a9a-99d9-f6d32a572a60)

MacOS Sonoma 14.6.1
Ferdium 7.0.0

**Comment by LostViking09** [comment] 2024-11-13 18:56
Same issue. Win10 LTSC 21H2 19044.5011

**Comment by lcreed** [comment] 2024-11-13 19:17
Same issue.  Fedora 41.  

![image](https://github.com/user-attachments/assets/d0bcc01b-ae04-42ab-bc8b-5f7bf8ad80a2)

![image](https://github.com/user-attachments/assets/2a857eba-55e7-4343-99b7-b9bddba01516)

**Comment by Alastor-Ripley** [comment] 2024-12-06 18:44
Same here, on Garuda which is based on arch (jokingly) btw

**Comment by SpecialAro** [comment] 2024-12-09 16:14
Closing as duplicate of https://github.com/ferdium/ferdium-app/issues/1926

**Closed as not planned by SpecialAro** 2024-12-09 16:14 UTC
Labels: duplicate :mirror:
