### ISSUE TITLE
Interface is broken - Missing font or invalid encoding

### ISSUE THREAD

**Issue by GuillaumeSorel** [ferdium/ferdium-app#1095] opened 2023-04-04 08:06 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.6-nightly.9

### What Operating System are you using?

Ubuntu

### Operating System Version

22.10

### What arch are you using?

x64

### Expected Behavior

Saving (downloading) an attached document or deleting a service should open a human readable screen

### Actual Behavior

Interface is broken, either fonts are missing or encoding is wrong but it's not readable. All characters are replaced by squares.

### Steps to reproduce

Suppress a service or download a file

### Screenshots

![image](https://user-images.githubusercontent.com/49272839/229727458-64e9a9ce-431c-49d6-8cea-67fd9929ac93.png)
![image](https://user-images.githubusercontent.com/49272839/229728073-dbd21405-5e7e-4911-8489-5035185647cc.png)

**Comment by vraravam** [comment] 2023-04-05 03:36
Duplicate of #435

**Closed as completed by vraravam** 2023-04-05 03:36 UTC
Labels: bug :beetle:
