### ISSUE TITLE
Whatsapp unread indicator seems confused

### ISSUE THREAD

**Issue by mnilsson76** [ferdium/ferdium-app#766] opened 2022-11-14 09:18 UTC
### Your issue

Since a few days ago Ferdium is indicating that there are 137 unread messages on Whatsapp. I don't have any messages unread either in the Android client or if I logon to web.whatsapp.com

If I click on my most recent chat the unread indicator changes to 34 and if I then click on my second chat it changes back to 137. Clicking on the 3rd chat shows 64 messages unread, then it's back to 137 if I click on the 4th chat.

I get the exact same behaviour on 2 machines: My Windows 11 Pro 22H2 machine at home and my Windows 10 Enterprise 21H2 laptop at work. Running Ferdium 6.2.0 on both.

**Comment by ysoudy** [comment] 2022-11-14 09:31
I have the same issue

To fix it temporarily (until the next release), modify the file : AppData\Roaming\Ferdium\recipes\whatsapp\webview.js

and edit the line 18 :
`const unreadSpans = parentChatElem.querySelectorAll('span[aria-label]:not(span[aria-label=""])');`

**Comment by krptg0** [comment] 2022-11-14 09:32
I have the same issue too.

**Comment by SpecialAro** [comment] 2022-11-14 09:44
Duplicate of https://github.com/ferdium/ferdium-recipes/issues/230 with PR in process https://github.com/ferdium/ferdium-recipes/pull/235

**Comment by Donaldini** [comment] 2022-11-14 09:44
Can confirm too.

Badge shows new messages though the WhatsApp unread message filter shows none.

<img width="537" alt="image" src="https://user-images.githubusercontent.com/2185680/201626951-4027c7ef-dfcb-47d5-8427-cfce606a35df.png">

Weirdly, when toggling between this filter, the unread messages changes from 64 to 24 here.

![image](https://user-images.githubusercontent.com/2185680/201627698-013756ce-60c3-4e57-a17c-7ad63319c3d6.png)

**Closed as not planned** 2022-11-14 09:44 UTC
Labels: duplicate :mirror:

**Comment by Teistt** [comment] 2022-11-14 20:13
Same issue here. Since a few day, it's going from like 33 to 37 to 54, then back to 33 when it wants...
Now I am at 2022 unread messages.. oops no 2055 now

![image](https://user-images.githubusercontent.com/80969848/201756374-bbbc2988-4ceb-46fa-a4bd-c466f6c72fe3.png)
