### ISSUE TITLE
Whatsapp - Wrong message about theme.

### ISSUE THREAD

**Issue by leoheck** [ferdium/ferdium-app#575] opened 2022-08-25 19:55 UTC
Trying to access Live Location of Whatsapp on Ferdium
![image](https://user-images.githubusercontent.com/1277920/186756153-c278829a-6044-453a-930d-0d4a69659c57.png)

Getting this weird, wrong, message about the theme.
![image](https://user-images.githubusercontent.com/1277920/186755980-333bf6ac-c989-4626-80e7-1f596edc8001.png)

```
Version: 6.0.1-nightly.18
Server: No Server
Electron: 20.0.3
Chrome: 104.0.5112.81
Node.js: 16.15.0
Platform: Linux 5.15
Arch: x64
Build date: Fri Aug 19 2022 23:41:38 GMT-0300 (Brasilia Standard Time)
Git SHA: 145a8fce
Git branch: nightly
```

**Comment by bwyyoung** [comment] 2022-08-31 11:00
I have the same issue.

**Comment by Riuaux** [comment] 2022-09-01 18:46
Yeah, same issue in every pop-up: delete msgs, live locaction, kboard shortcuts, silence group, delete chat...
```
Version: 6.1.0
Server: Ferdium Server
Electron: 20.1.0
Chrome: 104.0.5112.102
Node.js: 16.15.0
Platform: Windows 11
Arch: x64
Build date: Fri Aug 26 2022 18:40:44 GMT-0500 (hora de verano central)
Git SHA: 117ea8b2
Git branch: release
```

**Comment by SpecialAro** [comment] 2022-09-02 08:55
Duplicate of https://github.com/ferdium/ferdium-app/issues/573

**Closed as not planned by SpecialAro** 2022-09-02 08:55 UTC
Labels: duplicate :mirror:
