### ISSUE TITLE
Feature: Support Spotify In 

### ISSUE THREAD

**Issue by Julian88Tex** [ferdium/ferdium-app#686] opened 2022-10-20 05:11 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently, when creating a custom site for Spotify using URL `https://open.spotify.com`, an error message appears instead of the Spotify web player app reading "Enable secure playback in your browser".

<img width="1312" alt="Screen Shot 2022-10-19 at 9 58 49 PM" src="https://user-images.githubusercontent.com/459099/196860657-ab02fdf0-6f47-490f-b804-3b01e6693606.png">

### Proposed Solution

I suspect this may have been covered already here, but just in case I'm misunderstanding I think the underlying request is supporting DRM which perhaps is not possible with Electron apps. It looks like there are some projects that can allow for this but not sure if they are compatible with Ferdium realistically. At least hoping to get definite closure and understanding why this isn't possible and/or have this feature request in case someone knows of a way that it is possible.

### Alternatives Considered

It appears there may be a way with a [Chrome extension](https://www.quora.com/How-do-I-install-Widevine-on-Chrome) but is likely depending on [Chrome extensions being added to Ferdium](https://github.com/ferdium/ferdium-app/issues/135) first.

**Comment by vraravam** [comment] 2022-10-20 07:31
Closing as a duplicate of #113 - please follow the conversation there

**Closed as completed by vraravam** 2022-10-20 07:31 UTC
Labels: enhancement :sparkles:
