### ISSUE TITLE
Translator API down - cannot use Ferdium

### ISSUE THREAD

**Issue by anenviousguest** [ferdium/ferdium-app#1998] opened 2024-12-13 12:37 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

7.0.1-nightly.4

### What Operating System are you using?

Windows

### Operating System Version

23H2 build 22631.4460

### What arch are you using?

x64

### Last Known Working Ferdium version

7.0.1-nightly.4

### Expected Behavior

I start Ferdium and all services are loaded and usable

### Actual Behavior

I start Feridum and see a black window with a red error banner at the bottom of it, saying "Cannot load services and user information. Try again"

### Steps to reproduce

1. Open Ferdium
2. See the error message mentioned above

### Screenshots

![image](https://github.com/user-attachments/assets/c1856190-0231-4f80-b4de-8d74decee4c7)

### Additional information

When opening Developer Tools window, I see this in console:

```
C:\Users\whoami\AppData\Local\Programs\Ferdium\resources\app.asar\stores\GlobalErrorStore.js:1 Error: [@formatjs/intl Error MISSING_TRANSLATION] Missing message: "sidebar.openWorkspaceDrawer" for locale "de", using default message (Open workspace drawer) as fallback.

    at new MissingTranslationError (C:\Users\whoami\AppData\Local\Programs\Ferdium\resources\app.asar\node_modules\@formatjs\intl\src\error.js:82:28)
    at formatMessage (C:\Users\whoami\AppData\Local\Programs\Ferdium\resources\app.asar\node_modules\@formatjs\intl\src\message.js:68:21)
    at formatMessage (C:\Users\whoami\AppData\Local\Programs\Ferdium\resources\app.asar\node_modules\react-intl\src\components\createIntl.js:32:39)
    at h.render (C:\Users\whoami\AppData\Local\Programs\Ferdium\resources\app.asar\components\layout\Sidebar.js:1:5382)
    at Object.allowStateChanges [as _allowStateChanges] (C:\Users\whoami\AppData\Local\Programs\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:1337:12)
    at C:\Users\whoami\AppData\Local\Programs\Ferdium\resources\app.asar\node_modules\mobx-react\dist\mobxreact.cjs.development.js:361:26
    at trackDerivedFunction (C:\Users\whoami\AppData\Local\Programs\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:1899:18)
    at Reaction.track (C:\Users\whoami\AppData\Local\Programs\Ferdium\resources\app.asar\node_modules\mobx\dist\mobx.cjs.development.js:2487:18)
    at h.reactiveRender [as render] (C:\Users\whoami\AppData\Local\Programs\Ferdium\resources\app.asar\node_modules\mobx-react\dist\mobxreact.cjs.development.js:357:14)
    at finishClassComponent (C:\Users\whoami\AppData\Local\Programs\Ferdium\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:19781:31)
```

**Comment by SpecialAro** [comment] 2024-12-14 11:35
Closing as duplicate of #1926

**Closed as not planned** 2024-12-14 11:35 UTC
Labels: duplicate :mirror:
