### ISSUE TITLE
Whatsapp not able to drag-drop-send video files

### ISSUE THREAD

**Issue by helloabella** [ferdium/ferdium-app#1642] opened 2024-03-25 03:23 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.7.1

### Recipe Name

WhatsApp

### Recipe Version

3.5.3

### Steps to reproduce

Go to Whatsapp, drag a video file like mp4 or mov into a conversation. 

### Expected Behavior

The file will be accepted and prompt the share media window.

### Actual Behavior

An error message will come up: 1 file you tried adding is not supported. 

### Screenshots

![Screenshot 2024-03-25 at 11 20 49 AM](https://github.com/ferdium/ferdium-app/assets/99466075/57eec5dd-0c76-40af-92f8-1376f98730c1)

### Additional Information

You can add the same file if you use the + sign > photos & videos > select the same file. I can do this on Whatsapp desktop so I suspect it's a ferdium recipe bug.

**Comment by SpecialAro** [comment] 2024-04-09 11:53
Hello @helloabella, does this same behavior happen with a regular web browser? If so, it might be a WhatsApp issue and not a Ferdium issue.

If not, I'll investigate further to try and fix it.

Thank you very much!

**Comment by mcmxcdev** [comment] 2024-04-13 22:44
I tried to reproduce this with both an `.mp4` and an `.mov` file, but both files were accepted and prompted the share media window without any issues.

Since there haven't been any other user reports about this problem, I suspect that the video you tried uploading could be corrupted, see: https://www.reddit.com/r/ffmpeg/comments/564kyc/ffmpeg_whatsapp_video_format_not_supported/

Closing since not an issue with Ferdium

**Closed as completed by mcmxcdev** 2024-04-13 22:44 UTC
Labels: bug :beetle:, question :question:, recipe :bookmark_tabs:
