### ISSUE TITLE
Bug: lots of whatsapp notifications

### ISSUE THREAD

**Issue by rst-raphael** [ferdium/ferdium-app#761] opened 2022-11-13 12:37 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.0

### What Operating System are you using?

Windows

### Operating System Version

windows 11

### What arch are you using?

x64

### Expected Behavior

Muitas notificações em whatsapp.

![image](https://user-images.githubusercontent.com/61321277/201521978-cb8b9b61-23b7-4ed9-9cc9-24ab5962d416.png)

### Actual Behavior

Ao acessar são apresentadas muitas notificações no whatsapp

### Steps to reproduce

Ao acessar são apresentadas muitas notificações no whatsapp

**Comment by cino** [comment] 2022-11-13 12:49
Duplicate of https://github.com/ferdium/ferdium-recipes/issues/230 with PR in process https://github.com/ferdium/ferdium-recipes/pull/235

**Closed as not planned by cino** 2022-11-13 12:49 UTC
Labels: duplicate :mirror:

**Comment by rst-raphael** [comment] 2022-11-13 13:07
ok, applied the change in webview.jsu, problem solved, thanks!
