### ISSUE TITLE
Discord ask to reconnect every time

### ISSUE THREAD

**Issue by noahfraiture** [ferdium/ferdium-app#1393] opened 2023-10-07 15:14 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.5.1-1

### Recipe Name

Discord

### Recipe Version

1.8

### Steps to reproduce

1. Open ferdium
2. Open discord
3. You need to reconnect

### Expected Behavior

It should keep you session

### Actual Behavior

It doesn't keep your session and ask you "try to reconnect"

### Screenshots

![231007_17h09m18s_screenshot](https://github.com/ferdium/ferdium-app/assets/94681915/79ab904d-019a-47d7-a9cf-1e200b21efa2)

### Additional Information

I tried to clear cache, remove and readd the recipe. Uninstall and reinstall ferdium.
I'm using the ferdium-bin on AUR

**Comment by SpecialAro** [comment] 2023-10-07 15:36
Duplicate of #522

**Closed as not planned** 2023-10-07 15:36 UTC
Labels: duplicate :mirror:
