### ISSUE TITLE
Bug: Duplicate tray icon in Gnome when locking/unlocking screen

### ISSUE THREAD

**Issue by cedricroijakkers** [ferdium/ferdium-app#57] opened 2022-04-28 15:15 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.14

### What Operating System are you using?

Other Linux

### Operating System Version

Linux 5.17.5-arch1-1 (Arch rolling release), Gnome 42.1

### What arch are you using?

x64

### Last Known Working Ferdium version

n/a

### Expected Behavior

When having the Ferfium icon in the tray, locking the screen and ulocking the screen again there should still be one Ferdium icon in the tray.

### Actual Behavior

Each time when the screen is locked/unlocked, a new Ferdium tray icon appears. If the previous one had a dot to signal a notification, it will remain there, even when the notification is read. The new tray icon seems to update just fine, the old one remains as is. Doing another lock/unlock cycle creates a new tray icon.

Only way to get rid of all tray icons, is to fully close Ferdium and re-open it. At that point, there will be one tray icon.

### Steps to reproduce

1. Open Ferdium
2. Tray icon appears as usual
3. Lock yout Gnome session
4. Unlock the Gnome session
5. A second tray icon appears
6. Lock your Gnome session again
7. Unlock your Gnome session again
8. A third tray icon appears
9. Close Ferdium fully to get rid of all tray icons

### Additional information

Related old Ferdi PR: https://github.com/getferdi/ferdi/pull/2343
Possibly related Electron issue: https://github.com/electron/electron/issues/24976

**Comment by kris7t** [comment] 2022-04-29 11:44
This is a well-known electron (actually chromium) problem. We're working around it somewhat, which is why we get a duplicate tray icon instead of an entirely disappearing tray icon.

Fixing this will require writing our on AppIndicator D-Bus implementation, unfortunately, as chromium's one is slightly broken.

**Comment by danisztls** [comment] 2022-05-05 15:57
There's an easy way to reproduce. Just disable and enable the "Always show Ferdium in system tray" option.

User log output:

```
mai 05 12:54:20 epsilon appindicatorsupport@rgcjonas.gmail.com[47594]: unable to update icon for Ferdium1
mai 05 12:54:26 epsilon appindicatorsupport@rgcjonas.gmail.com[47594]: Ferdium1, Impossible to lookup icon for 'Ferdium1_4-panel' in path /tmp/.org.chromium.Chromium.Alnrfy
mai 05 12:54:26 epsilon appindicatorsupport@rgcjonas.gmail.com[47594]: unable to update icon for Ferdium1
mai 05 12:54:26 epsilon appindicatorsupport@rgcjonas.gmail.com[47594]: While reading menu layout on proxy :1.128: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “com.canonical.dbusmenu” on object at path /org/ayatana/NotificationItem/Ferdium1/Menu
mai 05 12:54:26 epsilon gnome-shell[47594]: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
                                              refreshPropertyOnProxy@/home/dani/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:41:38
                                              _translateNewSignals/<@/home/dani/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:206:18
                                              _translateNewSignals@/home/dani/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:205:50
                                              _onProxySignal/<@/home/dani/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:222:56
                                              _onProxySignal@/home/dani/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:222:38
mai 05 12:54:27 epsilon appindicatorsupport@rgcjonas.gmail.com[47594]: unable to update icon for Ferdium2
mai 05 12:54:28 epsilon appindicatorsupport@rgcjonas.gmail.com[47594]: Ferdium2, Impossible to lookup icon for 'Ferdium2_1-panel' in path /tmp/.org.chromium.Chromium.tRnNMl
mai 05 12:54:28 epsilon appindicatorsupport@rgcjonas.gmail.com[47594]: unable to update icon for Ferdium2
mai 05 12:54:28 epsilon appindicatorsupport@rgcjonas.gmail.com[47594]: While reading menu layout on proxy :1.128: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/ayatana/NotificationItem/Ferdium2/Menu”
mai 05 12:54:28 epsilon gnome-shell[47594]: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
                                              refreshPropertyOnProxy@/home/dani/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:41:38
                                              _translateNewSignals/<@/home/dani/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:206:18
                                              _translateNewSignals@/home/dani/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:205:50
                                              _onProxySignal/<@/home/dani/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:222:56
                                              _onProxySignal@/home/dani/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:222:38
```

**Comment by Telkhine** [comment] 2022-07-07 23:43
I've personally only seen this issue with gnome + appindicator shell-extension. On both i3-wm and qtile, I don't have the duplicate tray icon issue. So I don't know if it's an implementation issue or not.

**Comment by xalt7x** [comment] 2022-09-28 01:02
> I've personally only seen this issue with gnome + appindicator shell-extension. On both i3-wm and qtile, I don't have the duplicate tray icon issue. So I don't know if it's an implementation issue or not.

Seems like it is. I guess GNOME/Ubuntu users could try alternative "tray restoration extensions"  (e.g. [Tray Icons: Reloaded](https://github.com/MartinPL/Tray-Icons-Reloaded)) until Ferdium, [Electron](https://github.com/electron/electron/issues/24976) or [gnome-shell-extension-appindicator](https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/348) fix this issue.

**Comment by cedricroijakkers** [comment] 2022-09-28 13:41
With [gnome-shell-extension-appindicator release 44](https://github.com/ubuntu/gnome-shell-extension-appindicator/releases/tag/v44), this issue is now solved in Ferdium for me.

**Comment by 3v1n0** [comment] 2022-09-28 23:49
@Alt37 those apps are not using AppIndicators, but tray icons, so different technology (not really wayland friendly) and it's another issue.

I hope our (extension) bug is mostly fixed as @cedricroijakkers says when it comes to suspend/resume lock/unlock, but the reproducer @danisztls mentioned is actually tricky to handle.

In fact (as mentioned in https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/348#issuecomment-1261002950) we don't really get any status change call when the indicator is removed, it's just removed from the bus with no information to us, and we can only make assumptions.

And this looks to me more an electron issue, in particular:
 - It should create a status notifier icon only in the bus (and not a new one each time)
 - When hidden, it should first change the indicator Status to Passive, instead of just removing it.

**Comment by xalt7x** [comment] 2022-09-29 06:07
> With [gnome-shell-extension-appindicator release 44](https://github.com/ubuntu/gnome-shell-extension-appindicator/releases/tag/v44), this issue is now solved in Ferdium for me.

> I hope our (extension) bug is mostly fixed as @cedricroijakkers says when it comes to suspend/resume lock/unlock, but the reproducer @danisztls mentioned is actually tricky to handle.

With [gnome-shell-extension-appindicator release 44](https://github.com/ubuntu/gnome-shell-extension-appindicator/releases/tag/v44) (installed with "Extensions" app) I still can reproduce bug in both cases

1) After lock/suspend/resume or enable+disable extension there's 2 duplicated indicator. First (old) with an unread indicator icon and it's right click context menu doesn't work. New with regular icon and working context menu. 

[Kooha-2022-09-29-08-53-56.webm](https://user-images.githubusercontent.com/44649402/192951587-d85a66cc-c919-46a0-901a-c0430d907e2d.webm)

2) Just enter "Settings" and on the "General" tab untick/tick option "Always Show Ferdium in system tray". Tray indicators gets duplicated each time you change that setting. Only the last gets regular Ferdium icon (and working context menu), other got "three dots" icon.

[Kooha-2022-09-29-09-18-41.webm](https://user-images.githubusercontent.com/44649402/192954102-8cc6f5b3-b887-4dd0-9df4-6d01d0ae34e5.webm)

**Comment by kris7t** [comment] 2022-09-29 12:08
@3v1n0 

> And this looks to me more an electron issue, in particular:
> It should create a status notifier icon only in the bus (and not a new one each time)
> When hidden, it should first change the indicator Status to Passive, instead of just removing it.

There is another, more subtle issue at play here. When creating a status indicator icon, chromium will

1. Write the icon image to `/tmp`
2. Submit the status indicator to dbus
3. Delete the icon image from `/tmp`

This is to work around some issues in desktop environments where you couldn't directly send an icon bitmap over dbus (as per the comments in the chromium source code).

When gnome shell engages the screen lock,  the status notifier extension (just like any other extension) is unloaded. When you unlock the screen, the extension is loaded again, and wants to re-create the icons based on the information from dbus. But the icon has been already deleted from `/tmp`, so you get a missing icon!

As a workaround, ferdium destroys the tray icon when the status notifier extensions drops from the dbus, and re-creates it when it appears again. This ensures that the icon is (briefly) added back to `/tmp`, so there is no missing icon. But this gets us the duplicate icon bug due to chromium improperly destroying the previous icon.

**Comment by 3v1n0** [comment] 2022-09-29 20:42
So I've been looking at this again, and indeed we received a `passive` state change before closing, but we were missing it as we were trying to re-load it from dbus instead of getting the signal parameter.

This is now fixed as part of https://github.com/ubuntu/gnome-shell-extension-appindicator/commit/31c491dad8b879f70d3bdb3ebc2b803007c2f839

The best way would be to actually put the icons in a new bus, but that could not be controlled at this level I suppose.

**Comment by xalt7x** [comment] 2022-09-30 10:30
@3v1n0 
> This is now fixed as part of [ubuntu/gnome-shell-extension-appindicator@31c491d](https://github.com/ubuntu/gnome-shell-extension-appindicator/commit/31c491dad8b879f70d3bdb3ebc2b803007c2f839)

I've briefly tested a new version and duplicated indicators doesn't stay on panel anymore (after screen unlock you still might see icon flashing or even notice duplicated icon for a fraction of a second before it's destroyed). 
Could we expected an update for "Ubuntu AppIndicators" so LTS users would have it out of the box? Or should I fill a bug-report on the launchpad?

Thanks all for the quick resolution!

----

Indicator still "loses" unread icon status (on panel you have unread badge but tray indicator has regular icon) but I'm not sure if it's the same issue (happens with "Tray Icons: Reloaded" as well)

**Comment by 3v1n0** [comment] 2022-09-30 16:15
@Alt37 we've https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-appindicator/+bug/1991263 so we'll track it there

**Comment by xalt7x** [comment] 2022-10-03 17:09
@3v1n0 ,
With a new version I've got a new bug (not that annoying though).

With [AppIndicator and KStatusNotifierItem Support](https://extensions.gnome.org//extension/615/appindicator-support/) v46 icon now flicker/changes/reloads each time you switch services (that's reproducibly with [Hamsket](https://github.com/TheGoddessInari/hamsket) as well).

[appindicator__v46.webm](https://user-images.githubusercontent.com/44649402/193636947-34735b68-c679-4cb7-983b-13566134da7f.webm)

 ---

 With [gnome-shell-extension-appindicator v42-2~fakesync1](https://launchpad.net/ubuntu/+source/gnome-shell-extension-appindicator/42-2~fakesync1) icon doesn't change/reload.

[gnome-shell-extension-appindicator__42-2~fakesync1.webm](https://user-images.githubusercontent.com/44649402/193636983-b53b1c57-7153-407d-96c5-bf6faaae78f4.webm)

**Comment by mcmxcdev** [comment] 2023-07-29 03:58
Does anyone still encounter this issue? 

I remember having it too in the past, but seems to work as expected when I toggle "Always show Ferdium in system tray" nowadays. Also, screen locking and unlocking doesn't create a duplicate tray icon. 

Running Ubuntu 23.04, GNOME 44.3, Kernel 6.4.6

**Comment by danisztls** [comment] 2023-07-30 09:35
Solved for me on Arch.

**Comment by xalt7x** [comment] 2023-07-30 09:56
@cedricroijakkers 
I believe this issue is already fixed in [AppIndicator and KStatusNotifierItem Support](https://extensions.gnome.org//extension/615/appindicator-support/) (since[ v45](https://github.com/ubuntu/gnome-shell-extension-appindicator/releases/tag/v45))

https://github.com/ferdium/ferdium-app/issues/57#issuecomment-1262792571:
> This is now fixed as part of [ubuntu/gnome-shell-extension-appindicator@31c491d](https://github.com/ubuntu/gnome-shell-extension-appindicator/commit/31c491dad8b879f70d3bdb3ebc2b803007c2f839)

**Comment by mcmxcdev** [comment] 2023-07-30 12:32
Great I will close this then, let me know if I need to reopen it.

**Closed as completed by mcmxcdev** 2023-07-30 12:32 UTC
Labels: bug :beetle:
