### ISSUE TITLE
Bug: Keyboard Shortcuts not working

### ISSUE THREAD

**Issue by jason-mehmel** [ferdium/ferdium-app#267] opened 2022-06-15 16:24 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.60

### What Operating System are you using?

Ubuntu

### Operating System Version

Ubuntu 21.10

### What arch are you using?

x64

### Expected Behavior

Hitting Ctrl-[number] should take me to the app that matches that number in the order on the app drawer.

### Actual Behavior

Nothing.

### Steps to reproduce

1. Load Ferdium
2. Hit Ctrl-[any number]
3. no switching between apps

### Debug link

{"host":{"platform":"linux","release":"5.13.0-46-generic","screens":[{"id":0,"bounds":{"x":0,"y":349,"width":1920,"height":1080},"workArea":{"x":0,"y":349,"width":1920,"height":1080},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:SRGB, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1920,"height":1080},"displayFrequency":59,"workAreaSize":{"width":1920,"height":1080},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"},{"id":1,"bounds":{"x":1920,"y":0,"width":1920,"height":1080},"workArea":{"x":1920,"y":0,"width":1920,"height":1080},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:SRGB, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1920,"height":1080},"displayFrequency":59,"workAreaSize":{"width":1920,"height":1080},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdium":{"version":"6.0.0-nightly.60","electron":"19.0.4","installedRecipes":[{"id":"android-messages","version":"2.3.0"},{"id":"discord","version":"1.7.4"},{"id":"franz-custom-website","version":"1.2.0"},{"id":"messenger","version":"1.5.2"},{"id":"trello","version":"1.3.0"},{"id":"whatsapp","version":"3.4.1"},{}],"devRecipes":[],"services":[{"id":"3640767e-a440-4e9f-9f01-2c3969d3c0fd","recipe":"android-messages","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"38f78334-2419-4b87-a357-f1c821b9305f","recipe":"messenger","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"a666c63b-8f28-4278-ba7f-4406f44cfb31","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"c5366868-8d5a-40b4-889b-34041f34e891","recipe":"whatsapp","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"9ea6d1f7-a95f-46df-bd70-a7c6fe6f9adc","recipe":"discord","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"78cd93c9-9378-4523-a051-9a700ecc27f0","recipe":"franz-custom-website","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"ccbeaa51-a04e-4a00-a683-365f67467cc5","recipe":"trello","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false}],"messages":[{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.service` of type `Object` supplied to `AppLayoutContainer`, expected instance of `_class`.","\n    at AppLayoutContainer (/snap/ferdium/46/resources/app.asar/containers/layout/AppLayoutContainer.js:1:1742)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at <anonymous> (/snap/ferdium/46/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/snap/ferdium/46/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at Routes (/snap/ferdium/46/resources/app.asar/routes.js:1:2444)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at IntlProvider (/snap/ferdium/46/resources/app.asar/node_modules/react-intl/src/components/provider.js:83:47)\n    at I18N (/snap/ferdium/46/resources/app.asar/I18n.js:1:470)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at Provider (/snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:482:24)"]},{"type":"error","info":["error","Reaction doesn't converge to a stable state after 100 iterations. Probably there is a cycle in the reactive function: Reaction[bound _build]"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.ferdium.org"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.ferdium.org"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.ferdium.org"},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.settings` of type `Object` supplied to `Sidebar`, expected instance of `_class`.","\n    at Sidebar (/snap/ferdium/46/resources/app.asar/components/layout/Sidebar.js:1:1942)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at injectIntl(inject-with-stores-actions(Sidebar))\n    at div\n    at div\n    at ErrorBoundary (/snap/ferdium/46/resources/app.asar/components/util/ErrorBoundary/index.js:1:971)\n    at /snap/ferdium/46/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(ErrorBoundary))\n    at AppLayout (/snap/ferdium/46/resources/app.asar/components/layout/AppLayout.js:1:2631)\n    at /snap/ferdium/46/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(AppLayout))\n    at ThemeProvider (/snap/ferdium/46/resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)\n    at AppLayoutContainer (/snap/ferdium/46/resources/app.asar/containers/layout/AppLayoutContainer.js:1:1742)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at <anonymous> (/snap/ferdium/46/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/snap/ferdium/46/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at Routes (/snap/ferdium/46/resources/app.asar/routes.js:1:2444)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at IntlProvider (/snap/ferdium/46/resources/app.asar/node_modules/react-intl/src/components/provider.js:83:47)\n    at I18N (/snap/ferdium/46/resources/app.asar/I18n.js:1:470)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at Provider (/snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:482:24)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.service` of type `Object` supplied to `QuickSwitchModal`, expected instance of `_class`.","\n    at QuickSwitchModal (/snap/ferdium/46/resources/app.asar/features/quickSwitch/Component.js:1:1976)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at /snap/ferdium/46/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(inject-with-stores-actions(QuickSwitchModal)))\n    at div\n    at div\n    at div\n    at ErrorBoundary (/snap/ferdium/46/resources/app.asar/components/util/ErrorBoundary/index.js:1:971)\n    at /snap/ferdium/46/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(ErrorBoundary))\n    at AppLayout (/snap/ferdium/46/resources/app.asar/components/layout/AppLayout.js:1:2631)\n    at /snap/ferdium/46/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(AppLayout))\n    at ThemeProvider (/snap/ferdium/46/resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)\n    at AppLayoutContainer (/snap/ferdium/46/resources/app.asar/containers/layout/AppLayoutContainer.js:1:1742)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at <anonymous> (/snap/ferdium/46/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/snap/ferdium/46/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at Routes (/snap/ferdium/46/resources/app.asar/routes.js:1:2444)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at IntlProvider (/snap/ferdium/46/resources/app.asar/node_modules/react-intl/src/components/provider.js:83:47)\n    at I18N (/snap/ferdium/46/resources/app.asar/I18n.js:1:470)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at Provider (/snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:482:24)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.service` of type `Object` supplied to `PublishDebugLogModal`, expected instance of `_class`.","\n    at PublishDebugLogModal (/snap/ferdium/46/resources/app.asar/features/publishDebugInfo/Component.js:1:2558)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at /snap/ferdium/46/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(inject-with-stores-actions(PublishDebugLogModal)))\n    at div\n    at div\n    at div\n    at ErrorBoundary (/snap/ferdium/46/resources/app.asar/components/util/ErrorBoundary/index.js:1:971)\n    at /snap/ferdium/46/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(ErrorBoundary))\n    at AppLayout (/snap/ferdium/46/resources/app.asar/components/layout/AppLayout.js:1:2631)\n    at /snap/ferdium/46/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(AppLayout))\n    at ThemeProvider (/snap/ferdium/46/resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)\n    at AppLayoutContainer (/snap/ferdium/46/resources/app.asar/containers/layout/AppLayoutContainer.js:1:1742)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at <anonymous> (/snap/ferdium/46/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/snap/ferdium/46/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at Routes (/snap/ferdium/46/resources/app.asar/routes.js:1:2444)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at IntlProvider (/snap/ferdium/46/resources/app.asar/node_modules/react-intl/src/components/provider.js:83:47)\n    at I18N (/snap/ferdium/46/resources/app.asar/I18n.js:1:470)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at Provider (/snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:482:24)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.app` of type `Object` supplied to `_class`, expected instance of `_class`.","\n    at _class (/snap/ferdium/46/resources/app.asar/features/webControls/containers/WebControlsScreen.js:1:1876)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at div\n    at ServiceView (/snap/ferdium/46/resources/app.asar/components/services/content/ServiceView.js:1:1379)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at div\n    at Services (/snap/ferdium/46/resources/app.asar/components/services/content/Services.js:1:1751)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at /snap/ferdium/46/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(inject-with-actions(Services)))\n    at div\n    at div\n    at div\n    at ErrorBoundary (/snap/ferdium/46/resources/app.asar/components/util/ErrorBoundary/index.js:1:971)\n    at /snap/ferdium/46/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(ErrorBoundary))\n    at AppLayout (/snap/ferdium/46/resources/app.asar/components/layout/AppLayout.js:1:2631)\n    at /snap/ferdium/46/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(AppLayout))\n    at ThemeProvider (/snap/ferdium/46/resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)\n    at AppLayoutContainer (/snap/ferdium/46/resources/app.asar/containers/layout/AppLayoutContainer.js:1:1742)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at <anonymous> (/snap/ferdium/46/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/snap/ferdium/46/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at Routes (/snap/ferdium/46/resources/app.asar/routes.js:1:2444)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at IntlProvider (/snap/ferdium/46/resources/app.asar/node_modules/react-intl/src/components/provider.js:83:47)\n    at I18N (/snap/ferdium/46/resources/app.asar/I18n.js:1:470)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at Provider (/snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:482:24)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.ui` of type `Object` supplied to `SettingsContainer`, expected instance of `_class`.","\n    at SettingsContainer (/snap/ferdium/46/resources/app.asar/containers/settings/SettingsWindow.js:1:1080)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at div\n    at div\n    at div\n    at ErrorBoundary (/snap/ferdium/46/resources/app.asar/components/util/ErrorBoundary/index.js:1:971)\n    at /snap/ferdium/46/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(ErrorBoundary))\n    at AppLayout (/snap/ferdium/46/resources/app.asar/components/layout/AppLayout.js:1:2631)\n    at /snap/ferdium/46/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(AppLayout))\n    at ThemeProvider (/snap/ferdium/46/resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)\n    at AppLayoutContainer (/snap/ferdium/46/resources/app.asar/containers/layout/AppLayoutContainer.js:1:1742)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at <anonymous> (/snap/ferdium/46/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/snap/ferdium/46/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at Routes (/snap/ferdium/46/resources/app.asar/routes.js:1:2444)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at IntlProvider (/snap/ferdium/46/resources/app.asar/node_modules/react-intl/src/components/provider.js:83:47)\n    at I18N (/snap/ferdium/46/resources/app.asar/I18n.js:1:470)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at Provider (/snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:482:24)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.settings` of type `Object` supplied to `SettingsNavigation`, expected instance of `_class`.","\n    at SettingsNavigation (/snap/ferdium/46/resources/app.asar/components/settings/navigation/SettingsNavigation.js:1:1674)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at injectIntl(inject-with-stores-actions(SettingsNavigation))\n    at div\n    at ErrorBoundary (/snap/ferdium/46/resources/app.asar/components/util/ErrorBoundary/index.js:1:971)\n    at /snap/ferdium/46/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(ErrorBoundary))\n    at div\n    at CSSTransitionGroupChild (/snap/ferdium/46/resources/app.asar/node_modules/react-transition-group/CSSTransitionGroupChild.js:83:5)\n    at span\n    at TransitionGroup (/snap/ferdium/46/resources/app.asar/node_modules/react-transition-group/TransitionGroup.js:50:5)\n    at CSSTransitionGroup (/snap/ferdium/46/resources/app.asar/node_modules/react-transition-group/CSSTransitionGroup.js:56:5)\n    at Appear (/snap/ferdium/46/resources/app.asar/components/ui/effects/Appear.js:1:447)\n    at SettingsLayout (/snap/ferdium/46/resources/app.asar/components/settings/SettingsLayout.js:1:883)\n    at injectIntl(SettingsLayout)\n    at ErrorBoundary (/snap/ferdium/46/resources/app.asar/components/util/ErrorBoundary/index.js:1:971)\n    at /snap/ferdium/46/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(ErrorBoundary))\n    at SettingsContainer (/snap/ferdium/46/resources/app.asar/containers/settings/SettingsWindow.js:1:1080)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at div\n    at div\n    at div\n    at ErrorBoundary (/snap/ferdium/46/resources/app.asar/components/util/ErrorBoundary/index.js:1:971)\n    at /snap/ferdium/46/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(ErrorBoundary))\n    at AppLayout (/snap/ferdium/46/resources/app.asar/components/layout/AppLayout.js:1:2631)\n    at /snap/ferdium/46/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(AppLayout))\n    at ThemeProvider (/snap/ferdium/46/resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)\n    at AppLayoutContainer (/snap/ferdium/46/resources/app.asar/containers/layout/AppLayoutContainer.js:1:1742)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at <anonymous> (/snap/ferdium/46/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/snap/ferdium/46/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at Routes (/snap/ferdium/46/resources/app.asar/routes.js:1:2444)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at IntlProvider (/snap/ferdium/46/resources/app.asar/node_modules/react-intl/src/components/provider.js:83:47)\n    at I18N (/snap/ferdium/46/resources/app.asar/I18n.js:1:470)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at Provider (/snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:482:24)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.app` of type `Object` supplied to `EditSettingsScreen`, expected instance of `_class`.","\n    at EditSettingsScreen (/snap/ferdium/46/resources/app.asar/containers/settings/EditSettingsScreen.js:1:8983)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at injectIntl(inject-with-stores-actions(EditSettingsScreen))\n    at div\n    at ErrorBoundary (/snap/ferdium/46/resources/app.asar/components/util/ErrorBoundary/index.js:1:971)\n    at /snap/ferdium/46/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(ErrorBoundary))\n    at div\n    at CSSTransitionGroupChild (/snap/ferdium/46/resources/app.asar/node_modules/react-transition-group/CSSTransitionGroupChild.js:83:5)\n    at span\n    at TransitionGroup (/snap/ferdium/46/resources/app.asar/node_modules/react-transition-group/TransitionGroup.js:50:5)\n    at CSSTransitionGroup (/snap/ferdium/46/resources/app.asar/node_modules/react-transition-group/CSSTransitionGroup.js:56:5)\n    at Appear (/snap/ferdium/46/resources/app.asar/components/ui/effects/Appear.js:1:447)\n    at SettingsLayout (/snap/ferdium/46/resources/app.asar/components/settings/SettingsLayout.js:1:883)\n    at injectIntl(SettingsLayout)\n    at ErrorBoundary (/snap/ferdium/46/resources/app.asar/components/util/ErrorBoundary/index.js:1:971)\n    at /snap/ferdium/46/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(ErrorBoundary))\n    at SettingsContainer (/snap/ferdium/46/resources/app.asar/containers/settings/SettingsWindow.js:1:1080)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at div\n    at div\n    at div\n    at ErrorBoundary (/snap/ferdium/46/resources/app.asar/components/util/ErrorBoundary/index.js:1:971)\n    at /snap/ferdium/46/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(ErrorBoundary))\n    at AppLayout (/snap/ferdium/46/resources/app.asar/components/layout/AppLayout.js:1:2631)\n    at /snap/ferdium/46/resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(AppLayout))\n    at ThemeProvider (/snap/ferdium/46/resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)\n    at AppLayoutContainer (/snap/ferdium/46/resources/app.asar/containers/layout/AppLayoutContainer.js:1:1742)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at <anonymous> (/snap/ferdium/46/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/snap/ferdium/46/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at Routes (/snap/ferdium/46/resources/app.asar/routes.js:1:2444)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at IntlProvider (/snap/ferdium/46/resources/app.asar/node_modules/react-intl/src/components/provider.js:83:47)\n    at I18N (/snap/ferdium/46/resources/app.asar/I18n.js:1:470)\n    at /snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at Provider (/snap/ferdium/46/resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:482:24)"]}],"workspaces":[],"windowSettings":{"width":800,"height":600,"x":2112,"y":37,"isMaximized":true,"isFullScreen":false,"displayBounds":{"x":1920,"y":0,"width":1920,"height":1080}},"settings":{"autoLaunchOnStart":false,"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"confirmOnQuit":false,"minimizeToSystemTray":false,"closeToSystemTray":false,"privateNotifications":false,"clipboardNotifications":true,"notifyTaskBarOnMessage":false,"showDisabledServices":true,"showServiceName":false,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"en-us","darkMode":false,"splitMode":false,"splitColumns":3,"fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"enableGlobalHideShortcut":false,"server":"https://api.ferdium.org","predefinedTodoServer":"https://todoist.com/app","autohideMenuBar":true,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernateOnStartup":true,"hibernationStrategy":"300","wakeUpStrategy":"300","wakeUpHibernationStrategy":"0","wakeUpHibernationSplay":true,"inactivityLock":0,"automaticUpdates":true,"universalDarkMode":true,"userAgentPref":"","adaptableDarkMode":true,"accentColor":"#7266F0","serviceRibbonWidth":68,"sidebarServicesLocation":0,"iconSize":20,"navigationBarBehaviour":"custom","searchEngine":"duckDuckGo","useVerticalStyle":false,"hideRecipesButton":false,"useGrayscaleServices":false,"grayscaleServicesDim":50,"hideWorkspacesButton":false,"hideNotificationsButton":false,"hideSettingsButton":false,"alwaysShowWorkspaces":false,"liftSingleInstanceLock":false,"enableLongPressServiceHint":false,"proxyFeatureEnabled":false,"onlyShowFavoritesInUnreadCount":false,"locale":"en-US"},"features":{},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}

**Comment by jason-mehmel** [comment] 2022-06-15 16:25
I should note, Ctrl-T does open the 'todo' drawer.

**Comment by SpecialAro** [comment] 2022-06-15 17:00
Closing as duplicate of https://github.com/ferdium/ferdium-app/issues/250.

**Closed as completed by SpecialAro** 2022-06-15 17:00 UTC
Labels: duplicate :mirror:
