### ISSUE TITLE
Bug: Wildly inaccurate whatsapp notifications

### ISSUE THREAD

**Issue by jescalan** [ferdium/ferdium-app#768] opened 2022-11-14 16:54 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.0

### What Operating System are you using?

macOS

### Operating System Version

12.5.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

WhatsApp notifications are accurate

### Actual Behavior

I get "4552" as the notification number always, even though I have no unreads. I have tried disabling and re-enabling the service, notifications, and installing a new version of the app but it remains the same. Just started happening out of the blue one day.

### Steps to reproduce

I hope it can be reproduced, but not sure if able. It occurs for me after just installing and logging into the WhatsApp service.

### Debug link

https://debug.ferdium.org/bd242933-d29d-40b1-86f4-801777aa3959

### Screenshots

<img width="99" alt="Screen Shot 2022-11-14 at 11 49 18 AM" src="https://user-images.githubusercontent.com/556932/201718455-5997dfb3-9e8d-4c20-9e4a-430bda338386.png">

### Additional information

If I click on the "unread chats filter" icon, the count drops to zero. But if I un-toggle this mode it goes right back to 4552

**Comment by WouterJansen** [comment] 2022-11-14 16:55
happens to me as well since last week. But this is really a recipe issue, which I also found in the issue tracker for the ferdium recipes: https://github.com/ferdium/ferdium-recipes/issues/230. Including a fix.

**Comment by gabriel-andreescu** [comment] 2022-11-14 16:56
I can confirm this issue

**Comment by cino** [comment] 2022-11-14 17:02
Duplicate of https://github.com/ferdium/ferdium-recipes/issues/230 with PR in process https://github.com/ferdium/ferdium-recipes/pull/235

**Closed as completed by cino** 2022-11-14 17:02 UTC
Labels: duplicate :mirror:
