### ISSUE TITLE
Improve password autofill.

### ISSUE THREAD

**Issue by extropyst** [ferdium/ferdium-app#523] opened 2022-07-27 00:13 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Bitwarden is currently added as a password autofill app, however it does not have compatibility with password autofill in Ferdium, since it is not the Chrome Extension but the user profile web page, which in addition to not filling passwords by itself it has the problem that the session is closed from time to time, causing having to re-enter the master password again (since it is not possible to do it with a PIN or fingerprint, as with the extension).

### Proposed Solution

They should implement the password autofill services in a separate module (similar to how to-do list apps are aggregated) that works based on the Chrome Extensions for the given password autofill service (either Bitwarden, KeeWeb Connect, or AuthPass, which have both a Web version and an Extension version, and in the case of the latter two, they also support the KeePass protocol).

### Alternatives Considered

Otherwise support adding any kind of generic Chrome Extension, so you can either implement password autofill or some other required feature.

**Comment by vraravam** [comment] 2022-07-27 01:08
Duplicate of #135

**Closed as completed by vraravam** 2022-07-27 01:08 UTC
Labels: enhancement :sparkles:
