### ISSUE TITLE
Hotkey to switch services not working

### ISSUE THREAD

**Issue by Zethson** [ferdium/ferdium-app#250] opened 2022-06-14 12:44 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

ferdium-bin 6.0.0.nightly.59-1

### What Operating System are you using?

Other Linux

### Operating System Version

Latest Arch

### What arch are you using?

x64

### Last Known Working Ferdium version

Latest Ferdi

### Expected Behavior

I expect to be able to switch between services with CTRL + NUMBER. 

### Actual Behavior

The hotkey doesn't do anything anymore. CTRL + ALT + NUMBER works for mattermost teams still, but the overall switching between services isn't working.

### Steps to reproduce

Login. Attempt to switch between services with CTRL + NUMBER

### Additional information

Works on latest Ferdi (which is now dead for real)

**Comment by SpecialAro** [comment] 2022-06-14 14:40
Can't reproduce this issue in Windows 11. `CTRL + NUMBER` is working fine.

**Comment by BenBraunstein** [comment] 2022-06-14 15:41
I'm having the same issue in Windows 10 with 6.0.0.nightly.59

Ctrl + Number does nothing

**Comment by ste7enm** [comment] 2022-06-14 16:42
Same issue on Mac 12.4 (CMD + NUMBER) with 6.0.0-nightly.60.

**Comment by SpecialAro** [comment] 2022-06-14 17:43
> Same issue on Mac 12.4 (CMD + NUMBER) with 6.0.0-nightly.60.

Can you. please, try with `⌘ + number` instead of CMD and tell me if that works?

**Comment by ste7enm** [comment] 2022-06-14 17:49
> Can you. please, try with `⌘ + number` instead of CMD and tell me if that works?

@SpecialAro – The ⌘ symbol on the Mac stands for Command, they're the same thing. 🙂

**Comment by thadryanjs** [comment] 2022-06-14 18:08
Same issue, also on up-to-date Arch

**Comment by HenrijsS** [comment] 2022-06-14 18:15
Also not working on Windows 11 Home (Build 22000) with 6.0.0.nightly.59

**Comment by SpecialAro** [comment] 2022-06-14 18:15
> > Can you. please, try with `⌘ + number` instead of CMD and tell me if that works?
> 
> @SpecialAro – The ⌘ symbol on the Mac stands for Command, they're the same thing. 🙂

Sorry 🤣 I noobed out... and I have a mac xd

**Comment by SpecialAro** [comment] 2022-06-14 18:16
> Also not working on Windows 11 Home (Build 22000) with 6.0.0.nightly.59

For real? I'm using the exact Build of Windows and it's working fine... Ctrl + Number?

**Comment by HenrijsS** [comment] 2022-06-14 18:18
> > Also not working on Windows 11 Home (Build 22000) with 6.0.0.nightly.59
> 
> For real? I'm using the exact Build of Windows and it's working fine... Ctrl + Number?

Hmm. Reloading Ferdium fixed it. I'll try to Tinker with stuff and figure out what's the cause for it.

**EDIT:** Also, Right-click context menu shortcuts also don't work. IE CTRL+Left Arrow doesn't go back.
![image](https://user-images.githubusercontent.com/49265222/173661566-49d1cea8-2a52-483d-9c21-4bb479cac20f.png)

**Comment by SpecialAro** [comment] 2022-06-14 18:24
> **EDIT:** Also, Right-click context menu shortcuts also don't work. IE CTRL+Left Arrow doesn't go back. ![image](https://user-images.githubusercontent.com/49265222/173661566-49d1cea8-2a52-483d-9c21-4bb479cac20f.png)

Try Alt+Left Arrow. Should Work

**Comment by HenrijsS** [comment] 2022-06-14 18:25
@SpecialAro Yep. That did it. Need to rename or re-map the controls for that one.
CTRL+Home still not working.

**Comment by ste7enm** [comment] 2022-06-14 18:26
> Hmm. Reloading Ferdium fixed it. I'll try to Tinker with stuff and figure out what's the cause for it.

This worked for me too. 👍

**Comment by vraravam** [comment] 2022-06-14 23:28
I'm on a mac, and these keyboard shortcuts work for me without any issues.

**Comment by leewssam** [comment] 2022-06-15 02:26
Not working on Windows 10, nightly release-60

--- edit ---
working after reloading the app

**Comment by Zethson** [comment] 2022-06-15 08:21
They are now also working for me after reloading the app. However, yesterday I reloaded like 10 times and the issue persisted. In the meantime I updated to the latest nightly (yesterday's) though...
Wish I had a more precise error statement.

**Comment by BenBraunstein** [comment] 2022-06-15 13:35
Randomly started working for me again. Possibly the reload I did this morning did it for me

**Comment by thadryanjs** [comment] 2022-06-15 16:11
> They are now also working for me after reloading the app. However, yesterday I reloaded like 10 times and the issue persisted. In the meantime I updated to the latest nightly (yesterday's) though... Wish I had a more precise error statement.

Same here - fired it up today and it's fine

**Comment by jason-mehmel** [comment] 2022-06-15 18:24
Also flagging the problem. (Didn't find this when searching for bugs, apologies!)

Ubuntu 21.10, Ferdium nightly.

Will try reloading the app multiple times!

**Comment by probablykasper** [comment] 2022-06-16 20:43
The shortcuts aren't working because the services don't show up under `Services` in the menu bar on macOS

**Comment by SpecialAro** [comment] 2022-06-16 21:08
Big question:
Did all of you (who are experiencing this issue) migrated from Ferdi using the scripts or manually transferring the data folder?

**Comment by Zethson** [comment] 2022-06-16 21:10
> Big question: Did all of you (who are experiencing this issue) migrated from Ferdi using the scripts or manually transferring the data folder?

I didn't transfer or migrate at all from Ferdi. From scratch

**Comment by jason-mehmel** [comment] 2022-06-16 22:11
I also didn't transfer or migrate.

~Jason
pronouns: he / him / his
***@***.*** | www.jasonmehmel.com

**Comment by SpecialAro** [comment] 2022-06-21 23:56
Can you please provide this list?
![image](https://user-images.githubusercontent.com/37463445/174915431-75f647b8-f3fb-476a-a11f-b12f03117db0.png)

Also, are you using workspaces?

**Comment by alopix** [comment] 2022-06-22 08:51
I needed to restart Ferdi 2x in order to get the services to appear in the menu (and the shortcuts to work) on macOS with nighly installed just 5 minutes ago for the first time.

**Comment by jonmchan** [comment] 2022-07-18 13:10
I had a clean install of Ferdium on MacOS. While I was adding services, the cmd+1/cmd+2 buttons would not work. After restart, the keybindings worked.

**Comment by ElDelfinito3** [comment] 2022-07-22 22:31
> Hmm. Reloading Ferdium fixed it. I'll try to Tinker with stuff and figure out what's the cause for it.

This worked for me also!

**Comment by delucca** [comment] 2022-08-17 17:39
Same problem here on a fresh Arch install. Reloading it didn´t solve the issue.

Also, `Ctrl+D` (to open the workspaces) isn´t working as well. It seems that no keybinding is working (I'm using Arch with Gnome 42 and Xorg)

**Comment by mcarlton00** [comment] 2022-09-03 01:54
May be relevant: I was seeing this issue on my Arch machines, both from a fresh config and moving over from Ferdi.  It started working after I created a workspace, added services to it, and reloaded Ferdium.  Hope that helps somebody

**Comment by SpecialAro** [comment] 2022-09-03 09:19
If you reload Ferdium after a fresh install it should work (maybe hard reload)

**Comment by johannesleander** [comment] 2022-09-12 10:58
The shortcut for workspace switching (`Ctrl+Alt+*number*`) is actually broken in many locales on Windows since `Ctrl+Alt` is interpreted as `AltGr` ([Wikipedia](https://en.wikipedia.org/wiki/AltGr_key#Ctrl+Alt)).

On Swedish keyboards, for example, `AltGr+2` outputs `@`, `AltGr+3` outputs `£` and so on. 

Could we circumvent this problem by exposing user-configurable shortcuts?

**Comment by koshibb** [comment] 2022-09-28 21:11
Having same issue on Windows. If it helps, this is my view when I go to Services menu bar dropdown, I dont see any listed:
![image](https://user-images.githubusercontent.com/71457437/192889554-39629368-66d0-44bf-ba5a-c611cbb6e2c0.png)

**Comment by jamfx** [comment] 2022-11-12 11:48
I can reproduce the same issue on (ubuntu based) Linux Mint 21. CTRL + ALT + Number isn't working. 
Version: 6.2.0
Server: Ferdium Server
Electron: 20.2.0
Chrome: 104.0.5112.124
Node.js: 16.15.0
Platform: Linux 5.15
Arch: x64
Build date: Thu Sep 22 2022 18:47:12 GMT+0200 (Mitteleuropäische Sommerzeit)
Git SHA: 84613b5b
Git branch: release

**Comment by mcmxcdev** [comment] 2023-07-29 04:13
CTRL + Number works just fine on Ubuntu 23.04, anyone still experiencing this issue?

**Comment by jamfx** [comment] 2023-08-11 07:56
Nope, seems fixed.

**Comment by vraravam** [comment] 2023-08-11 08:56
Closing the issue since its been reported as fixed

**Closed as completed by vraravam** 2023-08-11 08:56 UTC
Labels: bug :beetle:, question :question:

**Comment by tonyrobertcook** [comment] 2024-02-21 17:16
The keyboard shortcuts for switching services, like Ctrl 2 etc they stop working ages ago. I need them to be working please. I have Windows 11. I feel that you have given up on this issue
