### ISSUE TITLE
Buffer recipe makes Ferdiun unusable

### ISSUE THREAD

**Issue by cosmicaug** [ferdium/ferdium-app#1231] opened 2023-06-05 19:46 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that Ferdium Recipes adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22recipe+%3Abookmark_tabs%3A%22+label%3A%22bug+%3Abeetle%3A%22+) for a bug report that matches the one I want to file, without success.

### Ferdium Version

6.26

### Recipe Name

Buffer

### Recipe Version

1.2.0

### Last Known working version of the recipe

Unknown

### Steps to reproduce

1. Run Linux Mint 21.1 x86_64 Cinnamon edition.
2. Install Ferdium from Flatpack
3. Add some service to it such as Whatsapp.
4. Attempt to add the Buffer service (will fail with a "Could not load service recipe" message).
5. Restart Ferdium. It will appear to load as new (no services added); but, in fact, it's just failing to load existing services. See [https://github.com/ferdium/ferdium-app/issues/1025#issuecomment-1577267585](url)

### Expected Behavior

Buffer service should be added. If it fails, it should not make other services fail as well.

### Actual Behavior

Buffer service cannot be added successfully and, instead, gives a "Could not load service recipe" message. It makes other services fail as well after restarting Ferdium.

**Comment by dmytri** [comment] 2023-07-27 08:31
Duplicate of https://github.com/ferdium/ferdium-app/issues/861

**Comment by SpecialAro** [comment] 2023-08-24 11:37
Closing as duplicate https://github.com/ferdium/ferdium-app/issues/861

**Closed as not planned by SpecialAro** 2023-08-24 11:37 UTC
Labels: bug :beetle:, duplicate :mirror:, recipe :bookmark_tabs:
