### ISSUE TITLE
6.7.3-nightly.11 creates purple screen of death on macOS

### ISSUE THREAD

**Issue by ylluminate** [ferdium/ferdium-app#1689] opened 2024-04-16 02:30 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.3-nightly.11

### What Operating System are you using?

macOS

### Operating System Version

14.4

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Ferdium version

6.7.3-nightly.9

### Expected Behavior

Ferdium should start

### Actual Behavior

Currently get a "purple screen of death" where nothing appears beyond this: 

![purple](https://p153.p0.n0.cdn.zight.com/items/KoukxX7L/31820c4f-5827-43fd-b4bd-14ed9267ac11.png?v=6abe303ec6e8fc188bd2660e79415d72)

Developer tools show:
```
/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:29840 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtoolsYou might need to use a local HTTP server (instead of file://): https://reactjs.org/link/react-devtools-faq
node:internal/modules/cjs/loader:1058 Uncaught Error: Cannot find module '@emotion/react'
Require stack:
- /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@emotion/styled/base/dist/emotion-styled-base.cjs.dev.js
- /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@emotion/styled/dist/emotion-styled.cjs.dev.js
- /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@emotion/styled/dist/emotion-styled.cjs.js
- /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@mui/styled-engine/node/index.js
- /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@mui/system/useThemeWithoutDefault.js
- /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@mui/system/useTheme.js
- /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@mui/system/useThemeProps/useThemeProps.js
- /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@mui/system/useThemeProps/index.js
- /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@mui/material/node/styles/useThemeProps.js
- /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@mui/material/node/SvgIcon/SvgIcon.js
- /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@mui/material/node/SvgIcon/index.js
- /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@mui/material/node/utils/createSvgIcon.js
- /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@mui/material/node/utils/index.js
- /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@mui/icons-material/utils/createSvgIcon.js
- /Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@mui/icons-material/Cancel.js
- /Applications/Ferdium.app/Contents/Resources/app.asar/components/downloadManager/DownloadManagerDashboard.js
- /Applications/Ferdium.app/Contents/Resources/app.asar/containers/download-manager/DownloadManagerScreen.js
- /Applications/Ferdium.app/Contents/Resources/app.asar/routes.js
- /Applications/Ferdium.app/Contents/Resources/app.asar/app.js
- /Applications/Ferdium.app/Contents/Resources/app.asar/index.html
    at Module._resolveFilename (node:internal/modules/cjs/loader:1055:15)
    at a._resolveFilename (node:electron/js2c/renderer_init:2:2669)
    at Module._load (node:internal/modules/cjs/loader:908:27)
    at c._load (node:electron/js2c/node_init:2:13672)
    at s._load (node:electron/js2c/renderer_init:2:31018)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@emotion/styled/base/dist/emotion-styled-base.cjs.dev.js:8:13)
    at Object.<anonymous> (/Applications/Ferdium.app/Contents/Resources/app.asar/node_modules/@emotion/styled/base/dist/emotion-styled-base.cjs.dev.js:223:3)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
```

### Steps to reproduce

Download update

**Comment by code-n-go** [comment] 2024-04-16 02:47
Confirmed.  Same issue on my M1 Max MacBook.

**Comment by 0-SamboNZ-0** [comment] 2024-04-16 03:33
Same issue for me on Win10.
Going back to the previous (.9) build restores all functionality.

**Comment by francwalter** [comment] 2024-04-16 08:03
Same issue on Win11 (with the Ferdium-win-AutoSetup-6.7.3-nightly.11-x64.exe)

Going back to [Ferdium-win-AutoSetup-6.7.3-nightly.9-x64.exe](https://github.com/ferdium/ferdium-app/releases/download/v6.7.3-nightly.9/Ferdium-win-AutoSetup-6.7.3-nightly.9-x64.exe) fixed it for me too.


I have pre-releases updates disabled (this screenshot is after I reverted to the nightly.9):

![grafik](https://github.com/ferdium/ferdium-app/assets/927269/23245cb1-197f-46af-8509-e78e177fbdfc)

But always I get these Pre-release Updates anyway:

![grafik](https://github.com/ferdium/ferdium-app/assets/927269/b15fa682-8dd1-4ca7-b68e-1bbaf93c3476)

But this must be another bug. I just ignored it and disabled updates at all, this should help.

**Comment by Axel29** [comment] 2024-04-16 08:06
Same thing on Ubuntu 22.04 with Snap installation.

Reverted to nightly build 10 (`sudo snap revert`) and it worked again.

**Comment by anishda** [comment] 2024-04-16 08:09
Also on Mac M1 2020

**Comment by SpecialAro** [comment] 2024-04-16 08:47
@mcmxcdev can you take a look at this please? I think this issue could be a result of #1682

EDIT: Seems like this issue is fixed by @vraravam on https://github.com/ferdium/ferdium-app/commit/962804e4dc0933cd683f2ee115efa7fb70a1a791. Just built locally and it opened without issues.

**Comment by vraravam** [comment] 2024-04-16 09:53
I am going to delete the [nightly.11](https://github.com/ferdium/ferdium-app/releases/tag/v6.7.3-nightly.11) version since that's not working. Hope that is fine. At least it wont bother folks with the "an update is available" prompt till the next nightly is released.

**Comment by mcmxcdev** [comment] 2024-04-16 12:57
Strange, I didn't encounter this locally and `@emotion/react` wasn't used directly as dependency anywhere.

Thanks for fixing this @vraravam by reinstalling it.

**Comment by yarons** [comment] 2024-04-18 11:14
Has anyone tested nightly 12 to confirm it's gone so we can also close this issue?

**Comment by code-n-go** [comment] 2024-04-18 14:24
@yarons I can confirm that I experienced the issue w/ nightly 11 and no longer experience it with nightly 12.  All good now here.

**Comment by SpecialAro** [comment] 2024-04-18 15:28
@ylluminate can we close this issue ?  😁

**Closed as completed** 2024-04-18 17:23 UTC
Labels: bug :beetle:

**Comment by 0-SamboNZ-0** [comment] 2024-04-18 23:36
Confirmed fixed on Win10 with build 12 also.
