### ISSUE TITLE
Bug: Logging me out Google and Messenger every time I restart my PC

### ISSUE THREAD

**Issue by lizechoo** [ferdium/ferdium-app#538] opened 2022-08-04 17:09 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.1-nightly.4

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 Education 21H2

### What arch are you using?

x64

### Last Known Working Ferdium version

6.0.0 (not sure exactly when)

### Expected Behavior

It used to keep my Google Calendar, Google Mail, and Messenger logged in. Now, I have to re-login every time my PC starts.

### Actual Behavior

My Google Calendar, Google Mail, and Messenger logs out every time the PC starts. 

### Steps to reproduce

1. Turn off PC
2. Turn on PC
3. My google calendar, google mail, and messenger is logged out.

### Debug link

https://debug.ferdium.org/49adba7e-144e-4a47-9563-53b9d0b069f8

### Screenshots

![Screenshot 2022-08-04 100835](https://user-images.githubusercontent.com/16563908/182910050-dd3c69ad-0394-4960-b7c8-4f4f6bad4aca.png)

**Comment by lizechoo** [comment] 2022-08-05 22:48
Does this just happen to me?

**Comment by SpecialAro** [comment] 2022-08-10 17:12
Hello @lizechoo , thank you for logging this issue.

I'm not able to reproduce this on my Windows 11. Have you tried to cleanup the cache?

**Comment by lizechoo** [comment] 2022-08-29 18:02
Hi @SpecialAro,
Thanks for trying to recreate it. I've tried cleaning up the cache, reinstalling it, etc. 
The new current release of 6.1.0 has the same issue and I can't figure out how to fix it

**Comment by SpecialAro** [comment] 2022-08-29 18:09
Hey 👋

Are you using the Ferdium Portable or the installer?

**Comment by lizechoo** [comment] 2022-08-29 18:13
I used the installer. 
Good news, after clearing the cache, logging out of my account and using the "use ferdium without an account" option -> restarting my pc -> then logging back into my ferdium account. 

It's working again. Thanks for the tip @SpecialAro!

**Comment by cino** [comment] 2022-11-11 08:15
Closing based on the latest comment.

**Closed as completed by cino** 2022-11-11 08:15 UTC
Labels: bug :beetle:
