### ISSUE TITLE
Missing flatpak for the latest release 6.7.3

### ISSUE THREAD

**Issue by raulillo82** [ferdium/ferdium-app#1737] opened 2024-05-03 11:56 UTC
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.2

### What Operating System are you using?

Other Linux

### Operating System Version

openSUSE Tumbleweed

### What arch are you using?

x64

### Last Known Working Ferdium version

6.7.2

### Expected Behavior

I would expect to find version 6.7.3 in flatpak.
Do flatpaks get generated automatically after release, or is it a manual process and was forgotten?

### Actual Behavior

Already some days after the release of the last version, I would normally expect to find it in Flatpak.
For instance, 6.7.2 date in flatpak is the same day as 6.7.2 was released:

raul@mordor:~$ flatpak info org.ferdium.Ferdium

```
Ferdium Team - Messenger for the desktop

          ID: org.ferdium.Ferdium
         Ref: app/org.ferdium.Ferdium/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 6.7.2
     License: Apache-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 470.1?MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: abdab709b204486e0c5d0738d8f335d385aebae664e7e205469a415d346c9811
      Parent: ab682e0ef5029b49181feba437012123ea9114fb4328606c2250bedcb1d02c73
     Subject: Remove ozone hint again (cc59abe0)
        Date: 2024-03-27 19:41:17 +0000
```
This is just barely some minutes/hours after the release date shown in Github (not sure about timezones, but probably just a few hours later?)

### Steps to reproduce

`$ flatpak info org.ferdium.Ferdium`

**Comment by SpecialAro** [comment] 2024-05-03 11:59
Closing as duplicate of https://github.com/ferdium/ferdium-app/issues/1730

Please take a look at https://github.com/ferdium/ferdium-app/issues/1730#issuecomment-2090236691

Please search the issue tracker BEFORE opening a new issue. Thank you!

**Closed as not planned by SpecialAro** 2024-05-03 11:59 UTC
Labels: duplicate :mirror:
