### ISSUE TITLE
Bug: WhatsApp - problem with counter notification and dark mode

### ISSUE THREAD

**Issue by eHerbaciarz** [ferdium/ferdium-app#771] opened 2022-11-16 06:42 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.0

### What Operating System are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Ferdium version

IDK

### Expected Behavior

In this version is a two problem with WhatsApp service:

1) Counter notification still show 144 unreaded messages - after "Refresh" problem still occurs

2) After "Refresh" WA service gets a white layout (even though darko mode is still on.

### Actual Behavior

In this version is a two problem with WhatsApp service:

1) Counter notification still show 144 unreaded messages - after "Refresh" problem still occurs

2) After "Refresh" WA service gets a white layout (even though darko mode is still on.

### Steps to reproduce

https://user-images.githubusercontent.com/10764145/202104170-5444fbde-acae-414e-b29c-a06bb69fe439.mp4

**Comment by vraravam** [comment] 2022-11-16 07:16
Please search for "Whatsapp" or other search terms before writing and raising tickets. This issue has so many duplicates that its getting a bit frustrating to the maintainers to close each one. Closing as a duplicate of https://github.com/ferdium/ferdium-recipes/issues/230

**Closed as completed by vraravam** 2022-11-16 07:16 UTC
Labels: bug :beetle:
