### ISSUE TITLE
Bug: Loading indicator never ends

### ISSUE THREAD

**Issue by leandrogehlen** [ferdium/ferdium-app#630] opened 2022-09-22 16:36 UTC
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.1.1-nightly.21

### What Operating System are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

After load page the loading indicator must ends

### Actual Behavior

After start windows some times loading indicator never ends

https://user-images.githubusercontent.com/1750751/191802698-d550d15d-2c80-4904-8a87-9c97cff5f612.mp4

```
Version: 6.1.1-nightly.21
Server: No Server
Electron: 20.2.0
Chrome: 104.0.5112.124
Node.js: 16.15.0
Platform: Windows 11
Arch: x64
Build date: Thu Sep 22 2022 00:08:01 GMT-0300 (Horário Padrão de Brasília)
Git SHA: b9868d8b
Git branch: nightly
```

### Steps to reproduce

Automacally start ferdium on start windows

**Comment by SpecialAro** [comment] 2022-09-22 16:49
Closing as duplicate of https://github.com/ferdium/ferdium-app/issues/590.

Please, also refer to https://github.com/ferdium/ferdium-app/issues/325

**Closed as not planned by SpecialAro** 2022-09-22 16:49 UTC
Labels: duplicate :mirror:
