### ISSUE TITLE
Github sponsors

### ISSUE THREAD

**Issue by Zethson** [ferdium/ferdium-app#262] opened 2022-06-15 12:53 UTC
### Your issue

Hey,

I was a happy contributor to the development of Ferdi until "the incident". I'd be happy to throw a bunch of $ at you again if you enable Github sponsors (or another service).

Cheers

**Comment by dqos** [comment] 2022-06-17 14:33
Thanks, we are still working hard on Ferdium itself, but this has been added to the TODO list.

Reference:
https://opencollective.com/
https://github.com/sponsors

**Comment by SpecialAro** [comment] 2022-06-22 00:00
Duplicate of https://github.com/ferdium/ferdium-app/issues/114

**Closed as not planned by SpecialAro** 2022-06-22 00:00 UTC
Labels: duplicate :mirror:
